### ISSUE TITLE
Invalid target "make analyze" in "pre_push" hook 

### ISSUE THREAD

**Issue by edno** [infection/infection#1032]
| Question    | Answer
| ------------| ---------------
| Infection version | dev-master@cc8b8e906b8f52cc296b2db4fdc20c580b9d4605
| Test Framework version | PHPUnit 8.3.5
| PHP version | 7.4.2
| Platform    | MacOS
| Github Repo | -

The `pre_push` hook for **injection** try to run `make analyze` but ends in error:
```shell
make: *** No rule to make target 'analyze'.  Stop.
```
In fact, the `Makefile` does not contain a target `analyze` that is preventing from pushing PR.

> Workaround: manually remove `make analyze` from the hook.

**Comment by maks-rafalko** [comment]
Thank you @edno
