### ISSUE TITLE
class virtual properties

### ISSUE THREAD

**Issue by calinblaga** [infection/infection#1035]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.15
| Test Framework version | PHPUnit 8.5.2
| PHP version | 7.3
| Platform | Ubuntu
| Github Repo | -

- Mutants escaped when it comes to virtual properties although removing the line in implementation causes the tests to fail. 

Implementation:
```
$metadata
        ->addPropertyConstraints('value', [
            new Type([
                'type' => 'string',
                'groups' => [
                    'DEFAULT'
                ]
            ])
        ])
```
unit test:
```
self::assertSame(['DEFAULT'], $property->getConstraints()[0]->groups);
```
a vendor class:
```
/**
 * @property array $groups
 */
abstract class Constraint
{}
```

**Comment by sanmai** [comment]
Could you provide a diff with a line that is getting removed?

**Comment by calinblaga** [comment]
```
$metadata
        ->addPropertyConstraints('value', [
            new Type([
                'type' => 'string',
                'groups' => [] // <--- the array is emptied 
            ])
        ])```

**Comment by sanmai** [comment]
Have you tried with the version from master to see if the issue remains?

```
cd /tmp
git clone https://github.com/infection/infection
cd infection; composer install
```

and then inside your project:

```
/tmp/infection/bin/infection -j4
```

**Comment by calinblaga** [comment]
sry my bad, it's a Timed Out mutant/Not Covered mutant not an escaped one.

**Comment by sanmai** [comment]
No problem. Shall we close this now?
