### ISSUE TITLE
Conflict with PHPUnit 9

### ISSUE THREAD

**Issue by rask** [infection/infection#1041]
PHPUnit 9 is fresh outta the oven. With it the dependency `sebastian/diff` was bumped from `3.*` to `4.*`.

Infection relies on `sebastian/diff` on version `3.*`. Which means I get the following when I try to install both Infection `0.15.*` and PHPUnit `9.*`:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - infection/infection 0.15.0 requires sebastian/diff ^3.0.2 -> satisfiable by sebastian/diff[3.0.2].
    - infection/infection 0.15.1 requires sebastian/diff ^3.0.2 -> satisfiable by sebastian/diff[3.0.2].
    - Can only install one of: sebastian/diff[4.0.0, 3.0.2].
    - Can only install one of: sebastian/diff[4.0.0, 3.0.2].
    - phpunit/phpunit 9.0.0 requires sebastian/diff ^4.0 -> satisfiable by sebastian/diff[4.0.0].
    - Installation request for phpunit/phpunit ^9.0 -> satisfiable by phpunit/phpunit[9.0.0].
    - Installation request for infection/infection ^0.15 -> satisfiable by infection/infection[0.15.0, 0.15.1].

```

This is not a bug as is, but just a notice that a possible update to the `sebastian/diff` dependency would be nice.

**Comment by sanmai** [comment]
This issue was fixed for master in #1036, but it may worth porting to the latest released version branch.

**Comment by maks-rafalko** [comment]
Released https://github.com/infection/infection/releases/tag/0.15.2

**Comment by rask** [comment]
Thanks @maks-rafalko for the fast update!
