### ISSUE TITLE
Infection not working with phpdbg

### ISSUE THREAD

**Issue by jyggen** [infection/infection#106]
| Question    | Answer
| ------------| ---------------
| Infection version | 47c8350d11ea100184ac20fcd8eb85be2c78194a and later.
| Test Framework version | PHPUnit 6.1.0 and PHPUnit 6.5.5
| PHP version | 7.0.22 and 7.2.1
| Platform    | MacOS

It seems like running Infection using phpdbg (0.5.0) is broken in 0.7.0 and later.

I first tested it on an internal project using PHP 7.2.1, PHPUnit 6.5.5 and Infection 0.7.0 without success (and a colleague verified it with PHP 7.0.22), and then on the Infection codebase itself (69551ba366ca116e56178a8f3c10416e75e1b91f) using PHP 7.2.1 and PHPUnit 6.1.0. In both cases we get the same error message.

I've checked out 0.6.2 of Infection and that version does work. Running Infection on Infection commit by commit since 0.6.2 it seems like 47c8350d11ea100184ac20fcd8eb85be2c78194a is the version that breaks phpdbg, because that commit and every commit after that has the same issue.

I'll do some more digging later and maybe I can put together a failing test case for it.

<details>
 <summary>Output while running Infection on Infection itself:</summary>
 
 ```shell
$ phpdbg -qrr bin/infection
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Running initial test suite...

Phpunit version: 6.1.0

    2 [============================] < 1 sec

Generate mutants...

Processing source code files: 166/166
Creating mutated files and processes:    0/1008

 [ERROR] Code Coverage does not exist. File
         /var/folders/1_/j6pgbhz546g4t92sckw7215c0000gn/T/infection/coverage-xml/index.xml is not found. Check phpunit
         version Infection was run with and generated config files inside
         /var/folders/1_/j6pgbhz546g4t92sckw7215c0000gn/T/infection.
 ```
</details>

**Comment by sidz** [comment]
@jyggen thank you. I've fixed that stupid issue here: https://github.com/infection/infection/pull/107
