### ISSUE TITLE
Files that are excluded from code coverage should not be mutated

### ISSUE THREAD

**Issue by localheinz** [infection/infection#1075]
**Is your feature request related to a problem? Please describe.**

Currently files contained in directories excluded via `phpunit.xml` are not mutated.

```xml
<filter>
  <whitelist processUncoveredFilesFromWhitelist="true">
    <directory suffix=".php">src</directory>
    <exclude>
      <directory>src/Foo/</file>
    </exclude>
  </whitelist>
</filter>
```

However, single files can also be excluded:

```diff
 <filter>
   <whitelist processUncoveredFilesFromWhitelist="true">
     <directory suffix=".php">src</directory>
     <exclude>
       <directory>src/Foo/</file>
+      <file>src/Bar.php</file>
     </exclude>
   </whitelist>
 </filter>
```

As far as I have observed, files listed via `<file>` element are currently **not** excluded from mutation.

**Describe the solution you'd like**

Respect `<file>` element and excluded references files  from mutation.

**Describe alternatives you've considered**

Adding tests.

**Comment by maks-rafalko** [comment]
I did a test (see the diff https://github.com/infection/infection/commit/9f541d2c5280330a8adcbc551dff844f53e45faa) and can confirm that files, marked as excluded from code coverage via both `<directory>` and `<file>` works the same way.

If you run just `infection`, they are mutated, but marked as `U` - uncovered. No mutant processes are created for them, we just display them in the logs:

```
Not Covered mutants:
====================

1) src/SourceClass.php:7    [M] PublicVisibility

--- Original
+++ New
@@ @@
 
 class SourceClass
 {
-    public function hello() : string
+    protected function hello() : string
     {
         return 'hello';
     }
 }
```

If you run `infection` with `--only-covered` option - these files are ignored (again - no matter we use `<directory>` or `<file>`.

And this is from my POV works as expected.

So, closing for now, if you have additional information or reproducible case - please share and reopen.

Thank you.
