### ISSUE TITLE
Removal of MutantWasCreated 

### ISSUE THREAD

**Issue by sanmai** [infection/infection#1091]
After #1082 I've left [MutantWasCreated](https://github.com/infection/infection/pull/1082/files#diff-34bd975c68ddd342c37abe44b3541baaR91) dangling. It isn't used anywhere, but unlike other (removed) events it may be of use.

Say, we can assign every mutation a sequential ID, and pass it along with `MutantWasCreated` and `MutantProcessWasFinished`, later collecting both events and reconciling the time it took to run a mutation. 

Or, better, we can add `MutantProcessWasAdded`, and use `MutantWasCreated` to estimate a lag we have launching processes, making a suggestion to use, say, a different thread count. Or simply include this metric in a some sort of internal performance report.

- Shall we keep it for time being? 
- Shall we remove it and re-add it later? 
- Is it any good for these purposes?

**Comment by theofidry** [comment]
I'm for removing it

>to estimate a lag we have launching processes, making a suggestion to use, say, a different thread count. Or simply include this metric in a some sort of internal performance report.

That's a cool idea but is it really actionable? How can you tell the lag is due to a thread count disparity or a heavy usage of the machine?

**Comment by sanmai** [comment]
Really hard to see that without the data. I'll remove it for now, it'll be easy to get it back later.
