### ISSUE TITLE
PrettyCI is shutting down

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#1100]
@localheinz I'm pretty sure you will be happy! :D

_Original email:_

<details>

PrettyCI is shutting down

PrettyCI started in 2017 as a side project. Initially aiming to solve my needs, I soon opened it to open source projects, and later paid customers.

Given the introduction of free alternatives like GitHub Actions, and after years of maintenance for next to no revenue, I am sorry to say I will be shutting it down. PrettyCI has been useful, but it isn't a commercial success. It is time to move on to new adventures.
How to replace PrettyCI?

You are encouraged to migrate to GitHub Actions. GitHub Actions is free and easy to setup, which makes it a good alternative to PrettyCI.

To help you, I have prepared a guide with examples: Check out the migration guide here.
Is there a transition period?

Yes, builds will continue to run for a while. You projects will not break.

Open source projects will keep building until December 2020.

Paid customers will be switched to a free plan that includes their private projects. To be clear, private projects will continue to build as before, until December 2020.
What will change from now until December 2020?

It will not be possible to add new projects to PrettyCI. PrettyCI will stop receiving updates. Remember this is a transition period, projects should be moved to GitHub Actions.
Thank you for your support

Thank you to everyone who used PrettyCI. Thank you to those who were patient when it needed fixing, who were helpful when it needed improvements. And finally, a big thank you to those who trusted the project to become a paid subscriber.

If you have any question, you can reach out to me at matthieu at mnapoli dot fr.

</details>

I think we need to move it to GitHub Actions. Help is very welcome.

**Comment by localheinz** [comment]
@maks-rafalko 

Going to take a look later!

**Comment by localheinz** [comment]
@maks-rafalko 

Should be fixed with #604!
