### ISSUE TITLE
Suggestion: more mutations

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#114]
I'd like to suggest some mutations.

(Stolen from [Stryker](https://stryker-mutator.github.io/mutators.html))

Original | Mutated
-- | --
for (var i = 0; i < 10; i++) { } | for (var i = 0; false; i++) { }
while (a > b) { } | while (false) { }
do { } while (a > b); | do { } while (false);
if (a > b) { } | if (true) { }
if (a > b) { } | if (false) { }
var x = a > b ? 1 : 2; | var x = true ? 1 : 2;
var x = a > b ? 1 : 2; | var x = false ? 1 : 2;

**Comment by theofidry** [comment]
One thing we need to be careful is redundant mutations. For example:

```php
#original
white (a > b) { }

# mutation °1
white (a <= b) { }

# mutation °2
white (false) { }
```

What is the point of both the mutations? Checking that the condition is well tested. So you want only one mutant to be applied, not both.

The reason for that is the second is redundant, and mutation testing is a brute force testing, the time taken is `nbr of mutants x time to run the tests`, so the more mutants the slower.

I admit I didn't check much all the mutators yet, but two things:

- Checking the other mutation testing tool mutants is definitely a good idea
- The most mature lib is [Pitest](https://github.com/hcoles/pitest) and a more complete list is [here](https://github.com/theofidry/mutation-testing)

So the mutants above are I believe redundant with what we already have, that said they might express better what we want to do.

**Comment by borNfreee** [comment]
Agree, all of the proposed mutation operators are covered by already existing ones. 

Closing it for now. 

Thank you @BackEndTea anyway! There much more interesting mutators we don't have yet (e.g. with try/catch/finally and throwing exceptions) that require deep investigation.
