### ISSUE TITLE
Infection no longer works via a composer global install?

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#1148]
Looks like maybe infection no longer works via a composer global install? https://app.circleci.com/pipelines/github/bdsl/psalm/218/workflows/5dfa1e19-20de-492c-9a58-95c9a03f61f9/jobs/934

```
#!/bin/bash -eo pipefail
php -d memory_limit=4G ~/.composer/vendor/bin/infection --coverage=build/phpunit --only-covered --threads=2 || echo 'Temporarily ignoring unexplained infection failure'


Fatal error: Uncaught OutOfBoundsException: Required package "infection/infection" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files in /home/docker/project/vendor/ocramius/package-versions/src/PackageVersions/Versions.php:89
Stack trace:
#0 /home/docker/.composer/vendor/infection/infection/src/Console/Application.php(81): PackageVersions\Versions::getVersion('infection/infec...')
#1 /home/docker/.composer/vendor/infection/infection/bin/infection(83): Infection\Console\Application->__construct(Object(Infection\Container))
#2 {main}
  thrown in /home/docker/project/vendor/ocramius/package-versions/src/PackageVersions/Versions.php on line 89
Temporarily ignoring unexplained infection failure

CircleCI received exit code 0
```

_Originally posted by @bdsl in https://github.com/infection/infection/issues/705#issuecomment-597313370_

---

Possibly related to https://github.com/infection/infection/issues/876

**Comment by sanmai** [comment]
I've seen this before. See testing notes in #1106 for example.

Also note the Infection is thrown by `...project/vendor/ocramius/package-versions...` which is not globally-installed package. I find myself thinking it is either a bug in `ocramius/package-versions`, or it's us not handling this exception.

**Comment by sanmai** [comment]
@bdsl can you see if you still have the issue with the latest `ocramius/package-versions`?
