### ISSUE TITLE
Senseless changes to visibility modifiers

### ISSUE THREAD

**Issue by foritstep** [infection/infection#115]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.7.0
| Test Framework version | PHPUnit 6.5.5
| PHP version | 7.1.11-0ubuntu0.17.10.1
| Platform    | Ubuntu 17.10
| Github Repo | https://github.com/foritstep/example

Now infection tries to change visibility modifiers for all unit tests. It looks like this
```diff
--- Original
+++ New
@@ @@
-    public function test0()
+    protected function test0()
```
After that infection marks this mutant as escaped so it pollutes log because it is false positive.

If I listen to this advice and change visibility modifiers, I will disable this test because phpunit can't call it.

**Comment by theofidry** [comment]
I'm not following, why are you running infection on your test suite?

**Comment by borNfreee** [comment]
Yeah, just exclude `tests` folder here https://github.com/foritstep/example/blob/master/infection.json.dist#L8

I will add this info to documentation to make it more clear

**Comment by foritstep** [comment]
@theofidry no. I am running test from root of my project.

@borNfreee I'm think that it is bad idea. Are there any cases when you need to test test? How about exclude automatically all that listed on phpunit test list? I'm thinking that isn't needed read all manual for get this result. (Надеюсь перевод получился понятным)

**Comment by borNfreee** [comment]
> I'm think that it is bad idea. Are there any cases when you need to test test?

What do you mean? Mutation testing is a tool to "test your tests", by mutating the source code. Source code here is a driver. No need to mutate test suite itself. MSI gives you a good knowled about how good your test suite.

> How about exclude automatically all that listed on phpunit test list?

If you mean we need to automatically exclude `tests` directory (like we do with `vendor`) as soon as source folder is `.` - yes, this is a good idea. 

Do you want to contribute?

Just small change here 

https://github.com/infection/infection/blob/5b08d3b98369fbe8432be0335d7fa92f2f20c219/src/Config/ValueProvider/ExcludeDirsProvider.php#L54-L57

**Comment by foritstep** [comment]
>What do you mean?

**Comment by theofidry** [comment]
we could automatically exclude the `tests` directory but there's plenty of projects where the tests are not located there so in any case you need to do that configuration.

If there is one thing we could improve IMO is the init command to maybe make clearer you should only include your source files and not the tests directories
