### ISSUE TITLE
ForeachKey mutation

### ISSUE THREAD

**Issue by sanmai** [infection/infection#1248]
```diff
-foreach ($results as $index => $result) {
+foreach ($results as $result) {
```

_Originally posted by @theofidry in https://github.com/infection/infection/pull/1242_

**Comment by maks-rafalko** [comment]
[Q](https://github.com/infection/infection/pull/1242#discussion_r407880498):
> this mutation will in most cases be killed because of "undefined variable", no?

[A](https://github.com/infection/infection/pull/1242#discussion_r407883594): 
> That, unless `$index` in unused.

---

So, in my opinion (although I didn't do any real checks) this can lead to killed mutant in majority of the cases.

We should not do this mutation _if the variable is used_, but at the moment Infection has no such knowledge about variables. As I said many times before, probably we need to integrate PHPStan's engine to track variables usages & types to accomplish it.

**Comment by BackEndTea** [comment]
For what its worth, i found those unused variables with help of the 'find dead code' feature from psalm.

So i'm not convinced this is something that should be part of infection, but rather it should be part of a static analysis tool.

**Comment by maks-rafalko** [comment]
Then let's close it
