### ISSUE TITLE
Visibility issue with inheritance: false positive on changing the visibility of an inherited method

### ISSUE THREAD

**Issue by ecourtial** [infection/infection#1250]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.16.2@9a3bca95fa873fba4a4a37a5fd35c6d572c0f23b
| Test Framework version | PHPUnit version: 9.1.1
| PHP version | PHP 7.4.3 with Xdebug 2.9.2
| Platform    | MacOS
| Github Repo | https://github.com/ecourtial/Fighting-Steel-Dynamic-Campaign-Manager
(use the "release-0.4.0" branch)

- I have a method with protected visibility. This method is overriden in a child class. Both methods are covered by tests. According to the infection report, I should change the visibility of the parent method to private. However, if  I do that, the test of the child class obviously fails since it is the parent code which is executed. I think that the issue comes from that the overriden method is always called in the parent class.

- Clone the repo. Switch on the _release-0.4.0_  branch. Do a composer install. Launch Infection ( __make infection__ ).

<details>
 <summary>phpunit.xml</summary>

 ```xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://phpunit.readthedocs.io/en/latest/configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="tests/bootstrap.php"
         executionOrder="random"
         resolveDependencies="true"
>
    <php>
        <ini name="error_reporting" value="-1" />
        <server name="APP_ENV" value="test" force="true" />
        <server name="SHELL_VERBOSITY" value="-1" />
        <server name="SYMFONY_PHPUNIT_REMOVE" value="" />
        <server name="SYMFONY_PHPUNIT_VERSION" value="7.5" />
        <env name="SYMFONY_DEPRECATIONS_HELPER" value="weak" />
    </php>

    <testsuites>
        <testsuite name="Project Test Suite">
            <directory>tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
            <exclude>
                <file>src/Kernel.php</file>
            </exclude>
        </whitelist>
    </filter>

    <listeners>
        <listener class="Symfony\Bridge\PhpUnit\SymfonyTestsListener" />
    </listeners>
</phpunit>

 ```
</details>

<details>
 <summary>infection.json.dist</summary>

 ```json
{
    "timeout": 10,
    "source": {
        "directories": [
            "src"
        ],
        "excludes": [
            "Kernel.php"
        ]
    },
    "logs": {
        "text": "var/tmp-infection/infection.log",
        "summary": "var/tmp-infection/summary.log",
        "perMutator": "var/tmp-infection/per-mutator.md",
        "badge": {
            "branch": "master"
        }
    },
    "mutators": {
        "@default": true
    },
    "tmpDir": "var/tmp-infection",
    "testFramework":"phpunit",
    "testFrameworkOptions": "-vvv"
}

 ```
</details>

<details>
 <summary>Output with issue</summary>

 ```
Infection - PHP Mutation Testing Framework 0.16.2@9a3bca95fa873fba4a4a37a5fd35c6d572c0f23b

Running initial test suite...

PHPUnit version: 9.1.1

  109 [============================] 4 secs
PHPUnit 9.1.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.3 with Xdebug 2.9.2
Configuration: /Users/eric/Documents/Code/PHP/FSCM/var/tmp-infection/infection/phpunitConfiguration.initial.infection.xml
Random seed:   1586935276

Testing
...............................................................  63 / 102 ( 61%)
.......................................                         102 / 102 (100%)

Time: 2.62 seconds, Memory: 16.00 MB

OK (102 tests, 176 assertions)

Generating code coverage report in PHPUnit XML format ... done [863 ms]



Generate mutants...

Processing source code files: 43/43
.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out

..................................................   ( 50 / 392)
..................................................   (100 / 392)
..................................................   (150 / 392)
..................................................   (200 / 392)
..................................................   (250 / 392)
..................................................   (300 / 392)
....................................M.............   (350 / 392)
..........................................           (392 / 392)

392 mutations were generated:
     391 mutants were killed
       0 mutants were not covered by tests
       1 covered mutants were not detected
       0 errors were encountered
       0 time outs were encountered

Metrics:
         Mutation Score Indicator (MSI): 99%
         Mutation Code Coverage: 100%
         Covered Code MSI: 99%

Please note that some mutants will inevitably be harmless (i.e. false positives).
[warning] Dashboard report has not been sent: The current process is not executed in a CI build

Time: 23s. Memory: 26.00MB
 ```
</details>

<details>
 <summary>Report's content</summary>

 ```

Escaped mutants:
1) /Users/eric/Documents/Code/PHP/FSCM/src/NameSwitcher/Switcher/ClassSwitcher.php:62    [M] ProtectedVisibility

--- Original
+++ New
@@ @@
      *
      * @param \App\Core\Fs\FsShipInterface $fsShip
      */
-    protected function addNewCorrespondence(FsShipInterface $fsShip, Dictionary $dictionary) : Ship
+    private function addNewCorrespondence(FsShipInterface $fsShip, Dictionary $dictionary) : Ship
     {
         $class = $fsShip->getClass();
         $currentName = $fsShip->getName();

$ '/Users/eric/Documents/Code/PHP/FSCM/vendor/phpunit/phpunit/phpunit' '--configuration' '/Users/eric/Documents/Code/PHP/FSCM/var/tmp-infection/infection/phpunitConfiguration.9dea92070cc3578d4ff4ba7a3c4d4cc7.infection.xml' '-vvv'
  PHPUnit 9.1.1 by Sebastian Bergmann and contributors.
  
  Runtime:       PHP 7.4.3
  Configuration: /Users/eric/Documents/Code/PHP/FSCM/var/tmp-infection/infection/phpunitConfiguration.9dea92070cc3578d4ff4ba7a3c4d4cc7.infection.xml
  Random seed:   1586933850
  
  Testing 
  .                                                                   1 / 1 (100%)
  
  Time: 114 ms, Memory: 8.00 MB
  
  OK (1 test, 1 assertion)

 ```
</details>

**Comment by sanmai** [comment]
Well, I can see this happening: we only check for the [parent's method visibility](https://github.com/infection/infection/blob/f8cf148e95a24bd69320e272c65bbbf5e46bd32d/src/Mutator/FunctionSignature/ProtectedVisibility.php#L101). And I don't see how we can solve this, e.g. shall we find all and every class extending this class to see if they override any methods?..

There are several workarounds:
- You can disable this mutator altogether.
- You can tag the child's test as covering the parent, and thus Infection will use both tests when testing against this mutation.

**Comment by ecourtial** [comment]
Hi @sanmai thank you for your answer. For the second solution, what do you mean exactly?

**Comment by sanmai** [comment]
You say that the test of the child class fails, so it may help to add [a `@covers parentClass` annotation](https://phpunit.readthedocs.io/en/9.0/annotations.html#covers) for the test for the child class.

**Comment by ecourtial** [comment]
It fails if I switch the visibility to private, because obviously it will call the parent method, and the output is different of the one expected.

**Comment by theofidry** [comment]
@ecourtial which class tests should we look at?

**Comment by ecourtial** [comment]
@theofidry 

The classes:

- parent one:  https://github.com/ecourtial/Fighting-Steel-Dynamic-Campaign-Manager/blob/release-0.4.0/src/NameSwitcher/Switcher/ClassSwitcher.php
- child one: https://github.com/ecourtial/Fighting-Steel-Dynamic-Campaign-Manager/blob/release-0.4.0/src/NameSwitcher/Switcher/ErrorSwitcher.php

The method which is causing the issue is named _addNewCorrespondence_ .
This method is called only in the parent class, but overrided in the child one.

To covers these two classes, we have the following tests:

- https://github.com/ecourtial/Fighting-Steel-Dynamic-Campaign-Manager/blob/release-0.4.0/tests/NameSwitcher/Switcher/ClassSwitcherTest.php
- https://github.com/ecourtial/Fighting-Steel-Dynamic-Campaign-Manager/blob/release-0.4.0/tests/NameSwitcher/Switcher/ErrorSwitcherTest.php

**Comment by theofidry** [comment]
Ok this is actually expected.

The issue here is neither Infection nor your tests: both are fine. The issue lies with the coverage information: as you are using Symfony with the PHPUnit bridge enabled, by default when you don't mention the `@covers` annotations, the PHPUnit bridge will infer one to say that `FooTest` covers `Foo`.

When Infection run the tests for `ClassSwitcher`, it will only run `ClassSwitcherTest`, not the child `ErrorSwitcherTest` which would fail but is not executed for that mutation.

So you have 3 choices:

- Overlook this mutation or this type of mutation: you can disable it on a file basis or for the whole project
- Add the `@covers` annotations necessary
- Adapt your tests so that you test the extendability of your class in `ClassSwitcherTest`

**Comment by ecourtial** [comment]
Thank you for you explanations.
I will explore the three solutions you mentioned.

The only thing I am curious about, is that I do not use the PHPUnit bridge anymore. It was still installed, but I switched to the "basic" PHPUnit a few weeks ago because it was useless for me. Just in case, I removed the Bridge to be sure, same result.

**Comment by theofidry** [comment]
To be exact this is due to the coverage listener, if not enabled then you should use `@covers` annotations

**Comment by ecourtial** [comment]
OK I used the third solution. Thank you. It's ok for me :)
