### ISSUE TITLE
Feature: Include bootstrap.php entirely

### ISSUE THREAD

**Issue by patrickfunke** [infection/infection#126]
For some projects, PHPUnit's bootstrap.php may contain a very customized setup (e.g. additional autoloading or global test data). Currently, Infection ignores everything but the autoloader generated by composer.

To enable the framework for such complex applications, I'd propose the possibility of including the bootstrap.php entirely as-is to ensure test execution works as intended.

I already tried this out and it seems the further analysis works just fine with such a complete custom bootrap file.

**Comment by theofidry** [comment]
Shouldn't the autoloading of that bootstrap be delegated to PHPUnit?

**Comment by patrickfunke** [comment]
The correct bootstrap.php is defined in phpunit.xml, but it seems to me that Infection builds its own bootstrap.php wich is then referenced in the configuration file created for each mutant. When looking up how Infection builds this bootstrap.php for the mutants, most of the content of the original one is not included.
