### ISSUE TITLE
Option to not validate phpunit.xml

### ISSUE THREAD

**Issue by thewholelifetolearn** [infection/infection#1265]
**Is your feature request related to a problem? Please describe.**
For security reasons, we have very limited access to Internet at work. But for Infection to work, it wants to validate PHPUnit's  configuration file. To validate the file, it needs access to Internet to request the XSD schema file. As it fails, it is not possible to run it.

**Describe the solution you'd like**
I understand the reason to validate PHPUnit's configuration file but I would like a CLI option as well as a configuration file option to deactivate the validation.

**Describe alternatives you've considered**
Comment the lines in `infection/src/TestFramework/PhpUnit/Config/XmlConfigurationHelper.php` locally. But that must be done each time Infection is updated with the risk that the algorithm is done somewhere else in a future version.

**Comment by maks-rafalko** [comment]
you can use XSD schema from the `vendor` folder without any HTTP requests:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd"
>
<!-- ... -->
</phpunit>
```

**Comment by theofidry** [comment]
It also has the merit to use the XSD file coming with your PHPUnit version... so double wins here :)

**Comment by maks-rafalko** [comment]
Adding a new option is not needed here since the above solution can be used. Feel free to ask any questions.

**Comment by thewholelifetolearn** [comment]
Ok. Thanks for the solution.

**Comment by alfredbez** [comment]
I'm running into the same issue, but we use both PHPUnit and infection from a PHAR in our setup. It would also be nice to make it possible to run infection without an internet connection like I do right now (typing this on the train via my phone 😄)

**Comment by theofidry** [comment]
>It would also be nice to make it possible to run infection without an internet connection like I do right now

That should be already possible, the XSD comes from the local PHPUnit installation, surely it does not need to download anything?

**Comment by alfredbez** [comment]
Is it possible to use the xsd from the phpunit.phar? I know that this is possible when installing phpunit via composer
