### ISSUE TITLE
Decrement mutator makes array indexes negative

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#1270]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.16
| Test Framework version | any
| PHP version | x.y.z (`php -v`)

This should not happen

```diff
10) /SourceClass.php:14    [M] DecrementInteger

--- Original
+++ New
@@ @@
         $c = [1, 2, 3];
-        $d = $c[0];
+        $d = $c[-1];
```

**Comment by sanmai** [comment]
[Negative indexes in an array are not forbidden.](https://3v4l.org/GpRED) You can totally have an array with a negative index.

**Comment by maks-rafalko** [comment]
right, but from my experience with this mutator, each time it decrements `0` to `-1` as an index of the array, it leads to undefined index notice

```
Notice: Undefined offset: -1
```

which in its turn always leads to killed Mutant.

So, I think this is a useless mutation in almost 100% cases. I'm speaking only about `0` to `-1`, not about `-99` to `-100`.

**Comment by LoopKarma** [comment]
thank you for labelling issues - I will try to pick up this bug +)  
@maks-rafalko can you please explain why mutation should not be applied if `the number is an index of the array`?

**Comment by maks-rafalko** [comment]
sure, as I said:

> from my experience with this mutator, each time it decrements `0` to `-1` as an index of the array, it leads to undefined index notice
> 
> ```
> Notice: Undefined offset: -1
> ```


So, there are many cases when I have similar code to this:


```php
$items = $object->getItems();

Assert::greaterThan(0, $items); // here we know that there is at least 1 item

$firstItem = $items[0];
```

So, when we have a list of items (array indexed from `0` to `N`) - there is no point in mutating `0` to `-1`, because it will always lead to 

```
Notice: Undefined offset: -1
```
