### ISSUE TITLE
Dashboard report has not been sent - Codeception.

### ISSUE THREAD

**Issue by terabytesoftw** [infection/infection#1272]
|  Q       |  A
| ---------------- | ---
| Infection          | 0.16.3
| PHP version      |  7.4.7
| CI | Github actions. 

[warning] Dashboard report has not been sent: The current process is not executed in a CI build.

Config:
```
{
  "source": {
    "directories": [
      "src"
    ]
  },
  "logs": {
    "text": "php:\/\/stderr",
    "badge": {
      "branch": "master"
    }
  },
  "mutators": {
    "@default": true
  },
  "tmpDir": "/runtime/infection",
  "testFramework": "codeception"
}
```

**Comment by maks-rafalko** [comment]
Hello @terabytesoftw.

I guess this is an issue with the lib we are using to detect CIs: https://github.com/OndraM/ci-detector

Do you have a public URL where Infection is used with GH Actions? From what I see, GH Actions are supported: 

https://github.com/OndraM/ci-detector/blob/5bf171fa198437415bf5bf824f82628e556224ff/src/Ci/GitHubActions.php#L15

I think we need to open an issue in that repository.

**Comment by OndraM** [comment]
See https://github.com/OndraM/ci-detector/issues/74#issuecomment-643996686 .

In short: do not run infection via sudo. CI environment cannot be detected in sudo shell on GitHub actions.

**Comment by theofidry** [comment]
@OndraM is there a possibility to throw a error there which we could catch to provide more context as to why no CI was detected?
