### ISSUE TITLE
Update phpunit.xml to fail on risky tests by default

### ISSUE THREAD

**Issue by sanmai** [infection/infection#1274]
**Is your feature request related to a problem? Please describe.**

#1273 showed that there are cases where a mutation may cause a test to become risky, yet these tests are not a cause of failure for PHPUnit by default.

The fix is a easy as adding [`failOnRisky="true"` to `phpunit.xml`](https://github.com/sebastianbergmann/code-unit/commit/33dcbf5a8ae6a555248e7e3c7b02eb3cbbd74b87), yet it is not as obvious as one may think it is.

**Describe the solution you'd like**

Since PHPUnit won't treat new risky tests as failures by default, and since this behavior causes an unnecessary confusion even for experienced users (see #1273), I suggest that we add `failOnRisky="true"` and `failOnWarning="true"` by default unless a conflicting directive is present, just like we do with `executionOrder="random"`.

That is, if there's already `failOnRisky="false"` then it should not be changed.

**Describe alternatives you've considered**

Another way would be to parse PHPUnit's output to see if there a risky tests, and give some feedback to the user adding a line or two to the mutation log. This looks like a support headache tbh.

**Comment by theofidry** [comment]
👍 on the proposed solution. I also think the alternative is better, but arguably harder to achieve hence can be a later iteration
