### ISSUE TITLE
Maybe give a useful warning when trying to combine `pcov` with an old PHPUnit 

### ISSUE THREAD

**Issue by HenkPoley** [infection/infection#1276]
```
You are running Infection with PCOV enabled.
[..]
Infection - PHP Mutation Testing Framework 0.16.0@b02a5a2e3eabbe8c3630e8159ec2d9b6a0966eb9
[..]
Running initial test suite...

PHPUnit version: 5.7.27
```

pcov support was only added in PHPUnit 8, it would be nice to get a kind of "🤔" hint.

**Comment by maks-rafalko** [comment]
Hi,

and what is happening later? is it the last line of Infection output? `PHPUnit version: 5.7.27`

no exceptions?

**Comment by maks-rafalko** [comment]
We can implement something similar to https://github.com/infection/infection/pull/1227 where we throw an exception if the test framework version is not supported.

**Comment by theofidry** [comment]
@maks-rafalko IIRC we said to not through for better flexibility. I'll come back to my PRs soonish but at the moment I'm in-between two movings so I don't have much time

**Comment by maks-rafalko** [comment]
> IIRC we said to not through for better flexibility

not sure I understand what you mean :) could you please remind?

**Comment by theofidry** [comment]
The idea was that if we for whatever reason want to try/continue on an older (unsupported) version or newer (not supported yet) version or if we did a mistake on our end, none of those will halt the user; but we still provide a proper warning when we can

**Comment by HenkPoley** [comment]
> and what is happening later? is it the last line of Infection output? `PHPUnit version: 5.7.27`
> 
> no exceptions?

Of course there was the exception that some xml file (for coverage I suppose) was not found.

But as a tool external to PHPUnit, it would be nice to tell "pcov will not work with PHPUnit 7 and older" (there are non-standard hacks, sure). As the older version of PHPUnit will of course not know it is running in a newer environment than it was built for. So they cannot tell it themselves.

Just: if pcov, inspect PHPUnit major version, if <=7: helpful error message.

**Comment by maks-rafalko** [comment]
I think this is not actual after 3 years. The modern versions of PHPUnit is 9 and 10, modern PHP is 8.1 ad 8.2

People should upgrade and I don' have time to support old versions
