### ISSUE TITLE
PHPUnit 9.3-dev: Element 'filter': This element is not expected.

### ISSUE THREAD

**Issue by terabytesoftw** [infection/infection#1282]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.16.x-dev@c1ef0b16b3e8d171f10ba8bfe8b6c93d482a68b4
| Test Framework version | PHPUnit 9.3-dev
| PHP version | 7.4.8
| Platform    | Github/Actions - Ubuntu Latests
| Github Repo | https://github.com/yiisoft/view/actions

phpunit.xml.dist:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="vendor/autoload.php"
         colors="true"
         verbose="true"
         failOnRisky="true"
         failOnWarning="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         stopOnFailure="false"
         executionOrder="random"
         resolveDependencies="true">
    <php>
        <ini name="error_reporting" value="-1" />
    </php>
    <testsuites>
        <testsuite name="Yii View tests">
            <directory>./tests</directory>
        </testsuite>
    </testsuites>

    <coverage>
        <include>
            <directory>./src</directory>
        </include>
    </coverage>
</phpunit>
```

infection.json.dist
```json
{
    "source": {
        "directories": [
            "src"
        ]
    },
    "logs": {
        "text": "php:\/\/stderr",
        "badge": {
            "branch": "master"
        }
    },
    "mutators": {
        "@default": true
    }
}
```

Error:

https://github.com/yiisoft/view/runs/874554924?check_suite_focus=true

**Comment by sanmai** [comment]
Apparently there's an issue in PHPUnit 9.3-dev. This might also be a compatibility issue in Infection, but since this PHPUnit version is not yet released we can't say this is true.

```
    Warning - The configuration file did not pass validation!                  
    The following problems have been detected:                                 
                                                                               
    Line 11:                                                                   
    - Element 'filter': This element is not expected.                          
```
Please use a released version of PHPUnit.

**Comment by sanmai** [comment]
The provided `phpunit.xml` is not the same that [used within the PR](https://github.com/yiisoft/view/blob/62c153b780f63b7064cfb43a96027233ff79d88a/phpunit.xml.dist). This file is indeed incorrect, which fact can be verified like so:

```
curl -o phpunit.xml.yiisoft-view-85 https://raw.githubusercontent.com/yiisoft/view/62c153b780f63b7064cfb43a96027233ff79d88a/phpunit.xml.dist
xmllint --noout --schema ./vendor/phpunit/phpunit/phpunit.xsd phpunit.xml.yiisoft-view-85 
```

The last command will report that the file fails to validate with the following explanation:

> phpunit.xml.yiisoft-view-85:24: element include: Schemas validity error : Element 'include': This element is not expected. Expected is ( whitelist ).

This is not a problem in Infection.

**Comment by terabytesoftw** [comment]
Phpunit change terms whitelist/blacklist to incluye/exclude.

**Comment by sanmai** [comment]
Would you mind providing a linked reference?

**Comment by terabytesoftw** [comment]
https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-9.3.md#930---2020-08-07

**Comment by sanmai** [comment]
Thanks, I'll open a separate issue.
