### ISSUE TITLE
False possitive with PHPUnit 9.3.x

### ISSUE THREAD

**Issue by dominikzogg** [infection/infection#1289]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.16.4
| Test Framework version | PHPUnit 9.3.x (tested with 9.3.0, 9.3.1, 9.3.2)
| PHP version | 7.4.8
| Platform    | Ubuntu 20.04
| Github Repo | https://github.com/chubbyphp/chubbyphp-framework-skeleton

I get a false positives since phpunit 9.3.x (9.2.6) worked. 

```
1) /chubbyphp-framework-skeleton/app/ServiceFactory/Framework/RoutesFactory.php:19    [M] ArrayItemRemoval

--- Original
+++ New
@@ @@
      */
     public function __invoke(ContainerInterface $container) : array
     {
-        return [Route::get('/ping', 'ping', new LazyRequestHandler($container, PingRequestHandler::class))];
+        return [];
     }
 }
```

Source: https://github.com/chubbyphp/chubbyphp-framework-skeleton/blob/master/app/ServiceFactory/Framework/RoutesFactory.php
Test: https://github.com/chubbyphp/chubbyphp-framework-skeleton/blob/master/tests/Unit/ServiceFactory/Framework/RoutesFactoryTest.php

**Comment by sanmai** [comment]
[The report tells that this is an uncovered mutation.](https://travis-ci.org/github/chubbyphp/chubbyphp-framework-skeleton/jobs/717313115#L598) This means Infection isn't to blame here. There's a defect somewhere in your coverage procedure. It might be a misplaced or misdirected `@covers` annotation.

You can verify that this file is indeed not covered by this test following these steps:

```
phpdbg -qrr vendor/bin/phpunit --coverage-html=coverage tests/Unit/ServiceFactory/Framework/RoutesFactoryTest.php
open coverage/ServiceFactory/Framework/RoutesFactory.php.html
```

**Comment by dominikzogg** [comment]
It seems to be an issue in phpunit 9.3 itself

![phpunit 9.2](https://ibb.co/Rhb8ZJJ)
![phpunit 9.3](https://ibb.co/1sSNYHk)

**Comment by dominikzogg** [comment]
https://github.com/sebastianbergmann/php-code-coverage/commit/081faa0834dee80268716e5c43f941ce8b3a975b fixes the issue
