### ISSUE TITLE
Feature: Config setting for temp files

### ISSUE THREAD

**Issue by ryan7273** [infection/infection#129]
For those on shared hosting or just wanting to separate multiple projects, it would be nice to have a setting in the config file for specifying the location of temp files. Using /tmp/infection as a default makes sense, but is not best in all cases.

**Comment by borNfreee** [comment]
Thank you for suggesting this feature. As always, I encourage people to make a PR, this one should be easy. 

Otherwise, I will pick it up when I have a chance after 0.7.1 is released (not in this month I guess)

**Comment by sidz** [comment]
https://github.com/infection/infection/pull/140

**Comment by borNfreee** [comment]
Implemented

**Comment by borNfreee** [comment]
@ryan7273 released under 0.7.1

**Comment by ryan7273** [comment]
Thank you!!
