### ISSUE TITLE
Add Mutator that removes cases from switch-Statements

### ISSUE THREAD

**Issue by Khartir** [infection/infection#1290]
I would like to suggest a new mutator, that removes `case`s from `switch`-Statements. I'm not 100% sure, but this is probably only needed, if the `case` has an empty body or if there are multiple `case`s with the same body. In the first case, there is no code that can be otherwise mutated, in the second case it is possible that not all `case`s are actually covered by tests.

Example:
Assume code like this:
```
switch ($value) {
  case 'a':
    doSomething();
    break;
  case 'b':
  case 'c':
  default:
    doSomethingElse();
    break;
}
```
If all tests only execute this code with `$value = 'a'` or `$value = 'b'` infection should report an escaped mutant if `case 'c':` or `default:` is removed.

**Comment by maks-rafalko** [comment]
Interesting! Feel free to implement, shouldn't be hard.
