### ISSUE TITLE
MSI at zero make infection fails

### ISSUE THREAD

**Issue by ecourtial** [infection/infection#1291]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.16.4
| Test Framework version | PHPUnit 9.2.6
| PHP version | 7.4.x
| Platform    | e.g. Debian Alpine (for CI)/MacOS (for dev)

When starting a new project with no tests, configured with a minimum MSI requirement, infection triggers an error since the score equals 0.

This issue also applies if you have, let's say, only one test, very basic - like a healthcheck controller, where infection is unable to create mutant.

<details>
 <summary>Output with issue</summary>

 ```

0 mutations were generated:
       0 mutants were killed
       0 mutants were not covered by tests
       0 covered mutants were not detected
       0 errors were encountered
       0 time outs were encountered

Metrics:
         Mutation Score Indicator (MSI): 0%
         Mutation Code Coverage: 0%
         Covered Code MSI: 0%

Please note that some mutants will inevitably be harmless (i.e. false positives).

                                                                                                       
 [ERROR] The minimum required MSI percentage should be 90%, but actual is 0%. Improve your tests! 
 ```
</details>

**Comment by sanmai** [comment]
Please try using `--ignore-msi-with-no-mutations` to see if it helps your cause.

**Comment by ecourtial** [comment]
@sanmai Seems to be working yes :) thanks.
