### ISSUE TITLE
differences between documentation and suggestions from algolia

### ISSUE THREAD

**Issue by zdenekgebauer** [infection/infection#1297]
There are differences between content of https://infection.github.io/ and suggestions from algolia. Steps to reproduce:
1. on https://infection.github.io/ fill "codeception" in search box
2. popup with suggestion contains words "codeception" (see attached image)
3. click on some suggestion
4. page does not contains any mention about "codeception" (see attached image).

![suggestions](https://user-images.githubusercontent.com/6378486/90329987-bd807180-dfa9-11ea-82eb-ceb3d25a6aed.jpg)
![documentation](https://user-images.githubusercontent.com/6378486/90329981-ae012880-dfa9-11ea-84f3-588e470f84d8.png)

**Comment by maks-rafalko** [comment]
Seems like you have a cached version in your browser.

Could you please

1. try opening the same page in Incognito private mode
2. try removing the Service Worker cache

So it works fine for me

**Comment by zdenekgebauer** [comment]
Thank you,  clearing cache solved problem
