### ISSUE TITLE
Do not generate mutants for assert()

### ISSUE THREAD

**Issue by Slamdunk** [infection/infection#1300]
Hi, on projects where I cannot use `webmozart\assert` nor `thecodingmachine\Safe`, I rely on `assert()` to guard basic clauses (and make static analysis tools happy), and Infection alter them like this:

```diff
 $stringValues = explode(PHP_EOL, $string);
-assert($stringValues !== false);
+assert($stringValues === false);
```

I find this mutations useless: is there any way to tell Infection to skip mutating `assert()` content?

**Comment by maks-rafalko** [comment]
Unfortunately, no at the moment. This is being discussed in https://github.com/infection/infection/issues/697 with more generic approach

**Comment by Slamdunk** [comment]
Duplicate of #697
