### ISSUE TITLE
Add support for Kahlan testing framework

### ISSUE THREAD

**Issue by marcosh** [infection/infection#1321]
I'm currently working on a library which is tested using https://github.com/kahlan/kahlan. I would like to add `infection` to my workflow but that is not possible at the moment, if I understand the situation correctly.

I saw there was some discussion for a general solution in #96 but that seems not to have reached a conclusion.

It would be nice to be able to provide a generic process as a killer for mutators

**Comment by maks-rafalko** [comment]
Hello! 

I think the best way to move it forward is to help with the implementation. I am, as a person who added support for PHPUnit, PHPSpec, Codeception and started the work for Pest, personally won't work on Kahlan integration as I don't think there is much demand on it.

But I will be happy to help someone who wants to do it. We had [similar request for Atoum](https://github.com/infection/infection/issues/381) test framework, however, topic starter just disappeared and we closed that request.

I will be happy to move external Kahlan integration with Infection as part of Infection organization and give someone write access.

**Comment by marcosh** [comment]
Thanks @maks-rafalko  for your reply and sorry if I'm late at getting back to this.

Personally I'm not sure I'll have time soon to dedicate to such an implementation.

I guess an implementation of #1323 would make things easier for such an integration

**Comment by maks-rafalko** [comment]
There is no demand on this feature, and it won't be a part of infection/infection anyway. If someone is interested - please comment here and I can probably help with creating a plugin, like we did for Codeception for example https://github.com/infection/codeception-adapter
