### ISSUE TITLE
Correct the Phpunit version

### ISSUE THREAD

**Issue by terabytesoftw** [infection/infection#1336]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.17.4
| Test Framework version | PHPUnit
| PHP version | 7.4.10
| Platform    | Windows

In the composer.json of infection you have in require-dev `"phpunit/phpunit": "^9.3.11"`, but in conflict `"phpunit/php-code-coverage": ">9 <9.1.4"`, phpunit 9.3.11 used php-code-coverage 9.1.5, php-code-coverage < 9.1.4 its phpunit 9.3.7,

Thks.

**Comment by sanmai** [comment]
`require-dev` is not considered when installing packages with Composer, so it does not negate the need to conflict with broken versions of sub-dependencies #1289.

**Comment by vjik** [comment]
0.18 not conflicted with phpunit 9.4

**Comment by sanmai** [comment]
What means?.. Infection itself does not depend on PHPUnit, as if `composer require infection` won't automatically pull PHPUnit.

**Comment by terabytesoftw** [comment]
Fixed thks @sanmai
