### ISSUE TITLE
Don't mutant $limit 0, -1 in preg_split 

### ISSUE THREAD

**Issue by vjik** [infection/infection#1345]
In function [preg_split](https://www.php.net/manual/en/function.preg-split.php) argument `limit` with values 0 and -1 behaves the same way. It would be cool if there was no mutation 0 to -1 and -1 to 0.

**Comment by maks-rafalko** [comment]
Hello, totally agree that this shouldn't be mutated.

Feel free to help us and fix it, shouldn't be hard. Mutator that does it is:

https://github.com/infection/infection/blob/81099171f3e43fc600e73f515e80858a49d240fb/src/Mutator/Number/DecrementInteger.php#L48

**Comment by maks-rafalko** [comment]
Fixed in https://github.com/infection/infection/pull/1347
