### ISSUE TITLE
Add GitHub Sponsors to the Infection organization

### ISSUE THREAD

**Issue by carusogabriel** [infection/infection#1346]
Hello there 👋 

I use Infection in my daily life as a developer, and it has helped me a lot to improve my code and my tests 🔥 

Could you please enable [GitHub Sponsors](https://github.com/sponsors) for the Infection [organization](https://docs.github.com/en/free-pro-team@latest/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-organization)? So we all could give it back to this amazing project, so it can continue to grow 🚀

**Comment by maks-rafalko** [comment]
@carusogabriel thanks for pushing it forward.

We have set up GitHub Sponsors for Infection Organization, and currently testing how it works and playing with tiers.

https://github.com/sponsors/infection

Feel free to be a sponsor! And thank you very much.
