### ISSUE TITLE
Call to undefined function Safe\getcwd()

### ISSUE THREAD

**Issue by greg0ire** [infection/infection#1366]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.18.2@05685f8e97ec2d42455fdaad6984446d5af2f67e
| Test Framework version | PHPUnit 9.4.1
| PHP version | 7.4.10
| Platform    | Gitlab runner, so I'm not sure
| Github Repo | -

I'm getting this crash when attempting to run `vendor/bin/infection` on my CI (I don't reproduce the issue locally):

```
PHP Fatal error:  Uncaught Error: Call to undefined function Safe\getcwd() in /builds/redacted/vendor/infection/infection/bin/infection:78

```

<details>
 <summary>phpunit.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://phpunit.readthedocs.io/en/latest/configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="tests/bootstrap.php"
>
    <php>
        <ini name="error_reporting" value="-1" />
        <server name="APP_ENV" value="test" force="true" />
        <server name="SHELL_VERBOSITY" value="-1" />
    </php>

    <testsuites>
        <testsuite name="Project Test Suite">
            <directory>tests/</directory>
        </testsuite>
    </testsuites>

    <coverage>
        <include>
            <directory>src</directory>
        </include>
        <exclude>
            <file>src/Kernel.php</file>
        </exclude>
    </coverage>
</phpunit>

```
</details>

<details>
 <summary>Output with issue</summary>

```
PHP Fatal error:  Uncaught Error: Call to undefined function Safe\getcwd() in /builds/redacted/vendor/infection/infection/bin/infection:78
Stack trace:
#0 /builds/redacted/vendor/infection/infection/bin/infection(81): {closure}()
#1 {main}
  thrown in /builds/redacted/vendor/infection/infection/bin/infection on line 78
```
</details>

**Comment by maks-rafalko** [comment]
Hello @greg0ire 

hard to say what's going on without a reproducible case. I suspected that probably the lowest version of `thecodingmachine/safe` was installed without `getcwd` function, but it's there [even in `1.0.0` version](https://github.com/thecodingmachine/safe/blob/25c39690b0e3f976c7177884a1f4980b29096711/generated/dir.php#L61) which Infection requires

Any way to debug it?

**Comment by greg0ire** [comment]
I used `cat vendor/thecodingmachine/safe/generated/dir.php`, and I see the file with the function, so this has to be purely about autoloading.

**Comment by greg0ire** [comment]
I don't know where the issue is, but I think it will have nothing to do with this library. Sorry for bothering you!
