### ISSUE TITLE
Separate options for path to xml coverage and junit log

### ISSUE THREAD

**Issue by vkhramtsov** [infection/infection#1377]
Hello,

Currently I'm adding `infection` to my project. I already have junit logs, but they have non default name of file (due to historical reasons). Currently `infection` has only one `--coverage` parameter, which point to directory with xml coverage and junit log with predefined names (directory and file). What do you think about adding two new CLI parameters (and two config options) for pointing to xml coverage directory and junit log? Something like `--coverage-xml-dir` and `--junit-log-file` (`coverage-xml-dir` and `junit-log-file` in config). In this case we could create more flexible command line (and configuration) for run `infection`.

Thank you in advance

**Comment by maks-rafalko** [comment]
Hi,

as I understood, you already have JUnit report, and probably (it's not clear) - already have xml coverage report.

 What if, instead of adding 2 new CLI options, you create a symlink with needed names for Infection to your reports?

Let's say your JUnit report is located at `./reports/custom.junit.xml` and xml report is located at `./reports/xml/coverage` - then you can create 2 symlinks so that they are compatible with what Infection requires:

* `./reports/infection/junit.xml` -> `./reports/custom.junit.xml` (file symlink)
* `./reports/infection/coverage-xml` -> `./reports/xml/coverage` (folder symlink)

and then use `infection --coverage=./reports/infection`.

Would it work for you?

Adding new CLI options is possible, but requires maintaining and increases complexity of Infection, which I would personally better avoid if what is requested from developers can be done by symlinks.

**Comment by sanmai** [comment]
And yet another way to work around this is by copying the JUnit report to other location. And, IIRC, it is not very expensive to make, thus if you'd ask PHPUnit to make two copies, it might take the same amount of time.

I agree with @maks-rafalko that adding these options will require a substantial amount of work with marginal benefits. Even though I had the idea on several occasions, I just don't see myself doing it. The same amount of work could bring much more sustainable benefits from other new features and improvements. 

If you wish to do it yourself, and do it in a non-BC-breaking way (keeping `--coverage` intact), well, go ahead. Who knows, it might be not as bad as, and as annoying as we think it is.

**Comment by vkhramtsov** [comment]
Hi @maks-rafalko, @sanmai ,
> as I understood, you already have JUnit report, and probably (it's not clear) - already have xml coverage report.

You are right about `JUnit` report, but not right with xml coverage report. Anyway I could easily generate it

> What if, instead of adding 2 new CLI options, you create a symlink with needed names for Infection to your reports?

It could be quick and dirty solution for now, but I don't like half working and hard to maintain (especially on windows hosts) solutions.

> And yet another way to work around this is by copying the JUnit report to other location. And, IIRC, it is not very expensive to make, thus if you'd ask PHPUnit to make two copies, it might take the same amount of time.

This is also not so good solution from my point of view, because we need to duplicate (generate/copy) files with same content.

> Adding new CLI options is possible, but requires maintaining and increases complexity of Infection, which I would personally better avoid if what is requested from developers can be done by symlinks.

I agree with you about complexity, but it also increase flexibility. Possible solution is to create two new options, but show error, when we have both new options and `--coverage` option in command line at the same time. From my point of view it looks like I could process this options almost the same as `--coverage` processed and just correct names of files (without duplication of code of course). Note: this way also could help with decreasing length and complexity of command line because I want to add these options to configuration too, so I could run infection without command line parameters, just gather all information from configuration (of course I plan to preserve possibility to override this configuration options via command line).

> If you wish to do it yourself, and do it in a non-BC-breaking way (keeping --coverage intact), well, go ahead. Who knows, it might be not as bad as, and as annoying as we think it is.

Actually that was my goal with creating this issue. I don't want to spend time with implementing functionality and then just close PR because nobody wants it. I'm going to implement this and return back with PR.

**Comment by vkhramtsov** [comment]
Unfortunately I don't have time to work with this feature. I'm closing this PR.
