### ISSUE TITLE
YieldValue mutator does not generate any mutations

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#1380]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.19.0, master
| Test Framework version | PHPUnit
| PHP version | 7.4
| Platform    | -

See https://infection-php.dev/r/4r6

Introduced in https://github.com/infection/infection/pull/1342

**Comment by sanmai** [comment]
There's something wrong with the playground:

> [mutators] The property YieldValue is not defined and the definition does not allow additional properties

**Comment by maks-rafalko** [comment]
it's in progress, I've updated JSON schema locally, but it still does not work when I add it explicitly

```json
{
    "mutators": {
        "@default": true,
        "YieldValue": true
    }
}
```

**Comment by sanmai** [comment]
```
$ php vendor/bin/infection --version
Infection - PHP Mutation Testing Framework version 0.19.0@e28e9ed25217dd8a9f5ffb480347ba96e3a39d3f

$ grep -A2 mutators infection.json.dist
    "mutators": {
        "YieldValue": true
    },

$ php vendor/bin/infection -j2

Processing source code files: 4/4
.: killed, M: escaped, U: uncovered, E: fatal error, T: timed out, S: skipped

..                                                   (2 / 2)

2 mutations were generated:
       2 mutants were killed
```

**Comment by maks-rafalko** [comment]
I took this example from tests :)

```php
$a = function () {
    (yield $a => $b);
};
```

so this is still an issue

**Comment by sanmai** [comment]
Well, I can't reproduce it no matter how I try :(

**Comment by sanmai** [comment]
What PHP version are you using on the playground?

**Comment by maks-rafalko** [comment]
Reason of the bug: two different mutators mutated the same Node. Nodes must be immutable
