### ISSUE TITLE
Mutator proposal: Flip null coalescing operator sides

### ISSUE THREAD

**Issue by MidnightDesign** [infection/infection#1387]
I couldn't find a mutator that mutates `$a ?? $b` to `$b ?? $a`. It would uncover the following case:

```php
function pickOne(?string $a, ?string $b): ?string {
    return $b ?? $a;
}

// The test to kill the mutant:
public function testPrefersBOverA(): void
{
    $picked = pickOne('foo', 'bar');

    self::expectSame('bar', $picked);
}
```

Playground link: https://infection-php.dev/r/v4d

**Comment by maks-rafalko** [comment]
Sounds good. Feel free to implement it, shouldn't be hard. And we are here to help!

**Comment by sidz** [comment]
Implemented in: https://github.com/infection/infection/pull/1389
