### ISSUE TITLE
PcreException should mention which regexp is actually invalid

### ISSUE THREAD

**Issue by sstok** [infection/infection#1406]
**Is your feature request related to a problem? Please describe.**
When a regex in the `ignoreSourceCodeByRegex` is invalid this crashes the application with:

```
[PHP Warning:  preg_match(): Compilation failed: missing closing parenthesis at offset 58 in [...]/infection/vendor/thecodingmachine/safe/generated/pcre.php on line 590]

In PcreException.php line 19:

  [Safe\Exceptions\PcreException (1)]
  PREG_INTERNAL_ERROR: Internal error
``` 

**Describe the solution you'd like**
This is not very helpful because it doesn't show which regex is invalid. Making debugging rather challenging.

I'm not sure this should be resolved here or in the `thecodingmachine/safe` package?
Instead when this exception is thrown it should show which regexp is invalid. Even better if it's able to mention which config-line is happens at but that's just dreaming 😁

**Comment by sidz** [comment]
Implemented in https://github.com/infection/infection/pull/1412
