### ISSUE TITLE
Escaping issues in `ignoreSourceCodeByRexeg` feature

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#1414]
when the regexp contains a `/` this will fail the schema validation, by escaping this, it passes the validation but because the https://github.com/infection/infection/blob/master/src/Differ/DiffSourceCodeMatcher.php#L47 escapes all slashes this causes it to be double escaped, meaning the regex becomes invalid.

For now I solved this by using `\x{2f}` but as the regexp is already invalid with `/` unescaped this line can be removed.

_Originally posted by @sstok in https://github.com/infection/infection/pull/1412#issuecomment-721350069_

**Comment by sanmai** [comment]
So the problem is in the schema validation.
