### ISSUE TITLE
Paths in config should be relative to config file

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#142]
Currently the paths in the config file need to be relative to the directory infection was executed from.

I think it would be better to have these paths be relative to the config file. Which is the same as for example phpunit does things.

**Comment by BackEndTea** [comment]
This breaks BC for projects where the config file is not in the same directory as where the command is ran from. 

So i'm not sure if this should wait for v1.0.0, or if were not following semantic versioning exactly. 

What do you think @borNfreee ?

**Comment by borNfreee** [comment]
I think we follow (at least I hope so) sem ver. `0.x.y` allows breaking BC at any time

https://semver.org/#spec-item-4

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

https://getcomposer.org/doc/articles/versions.md#caret-version-range-

> For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0.

I'm ok to introduce this in 0.8.0

**Comment by BackEndTea** [comment]
Ah thats great, i didn't know version 0 had different 'rules'.

**Comment by theofidry** [comment]
That said this is indeed a BC break, so I think we should document it in the changelog to make it easy to upgrade still if there's something breaking for some users
