### ISSUE TITLE
Include schema file in the generated infection.json.dist & docs

### ISSUE THREAD

**Issue by theofidry** [infection/infection#1432]
If you have:

```json
{
    "$schema": "./vendor/infection/infection/resources/schema.json",

    "source": {
        "directories": [
            "src"
        ]
    },
    "logs": {
        "text": "infection.log"
    },
    "mutators": {
        "@default": true,
        "MBString": false,
        "global-ignoreSourceCodeByRegex": [
            "Assert::.*"
        ]
    }
}
```

Then as you type "Me" you will get the auto-completion in some IDEs such as PhpStorm, which IMO is a nice to have. There is several places where we can add it:

- The docs
- The generated infection.json.dist (will change to a URL I think depending of if it's generating a PHAR or not)
- Our own infection.json.dist

**Comment by localheinz** [comment]
Also see https://github.com/json-schema-org/json-schema-spec/issues/828.
