### ISSUE TITLE
Mutator suggestion: String concatenation operator

### ISSUE THREAD

**Issue by MidnightDesign** [infection/infection#1439]
Is there a reason why there is no mutator that mutates `$x = 'foo' . 'bar'` to `$x = 'foo'` and `$x = 'bar'` (and maybe also to `$x = 'bar' . 'foo'`). Seems like a pretty obvious thing to me. Here's a use case:

```php
final class PrefixingStorage implements StorageInterface
{
    private string $prefix;
    private StorageInterface $innerStorage;

    public function __construct(string $prefix, StorageInterface $innerStorage)
    {
        $this->prefix = $prefix;
        $this->innerStorage = $innerStorage;
    }

    public function assign(string $key, string $value): void
    {
        $this->innerStorage->assign($this->prefix . $key, $value); // Is $this->prefix actually used?
    }

    public function get(string $key): ?string
    {
        return $this->innerStorage->get($this->prefix . $key); // Is $this->prefix actually used?
    }
}
```

I'd be happy to make my first code contribution to this project if you think this is something that Infection should be able to do.

**Comment by sanmai** [comment]
From the looks of it, it should not be very hard to make. Have a look at PRs for other mutators for an inspiration.

**Comment by MidnightDesign** [comment]
> From the looks of it, it should not be very hard to make. Have a look at PRs for other mutators for an inspiration.

Will do. I think you'll just have to help me out with the tests a little.

Also, do you think the flipping of the operands should be a separate mutator?

**Comment by sanmai** [comment]
Yes, if we'd think that someone might want to disable it.

**Comment by sanmai** [comment]
This is one of the most recent ones: https://github.com/infection/infection/pull/1411/files

**Comment by MidnightDesign** [comment]
@sanmai Do you prefer two separate PRs or a single one?

**Comment by MidnightDesign** [comment]
@sanmai Both PRs (+ documentation) are open.
