### ISSUE TITLE
Redundant increment mutations

### ISSUE THREAD

**Issue by theofidry** [infection/infection#1441]
Provided you have the following code:

```
protected function formatValue($value, $format = 0) : string {}
```

You will have 3 mutations:

```
DecrementInteger:
-    protected function formatValue($value, $format = 0) : string
+    protected function formatValue($value, $format = -1) : string

IncrementInteger:
-    protected function formatValue($value, $format = 0) : string
+    protected function formatValue($value, $format = 1) : string

OneZeroInteger:
-    protected function formatValue($value, $format = 0) : string
+    protected function formatValue($value, $format = 1) : string
```

As you can see the 2 & 3rd are strictly identical. I am not sure yet what's the best way to detect this in infection in a performant way, but it looks like something we could manage.

**Comment by sidz** [comment]
I saw this "issue" when I worked on improvement on those bunch of mutators and from my point of view - OneZeroInteger is redundant mutator and it will be better to get rid of it.
