### ISSUE TITLE
Behat support

### ISSUE THREAD

**Issue by lucascourot** [infection/infection#147]
Would it be possible to add Behat support to Infection so that we could have mutation testing when running Behat specifications with PHPUnit?

**Comment by borNfreee** [comment]
Hi, thanks for your interest in this project!

In a nutshell: yes, it's possible.

I will refer to my comment about the same question with Codecepton test framework: https://github.com/infection/infection/issues/45#issuecomment-332168173

> Several points to consider before implementation:
> 
> 1. We need to be able to pass such parameters as (they may have different names in Behat) 
> 1.1 `--stop-on-failure` - to stop executing tests when the first is failed
> 1.2 `--configuration` - to override location of configuration file
> 
> 2. Ideally we need to be able to generate `junit.xml` report. This is needed to fetch execution time of > each test and sort them during mutation testing for performance reason
> 
> 3. And the most important thing: we need to be able to run only particular tests (e.g. test `C`, `D`) from the whole {`A`, `B`, `C` , `D`, `E`} testsuite. This is also for performance reason. But if it's impossible in Behat, it does not block integration.

-------

Btw, are you sure you need mutation testing for Behat Scenarios? Behat is not fast by definition (please correct me if I'm wrong) so with mutation testing it can take hours.

Feel free to contribute. A good start point and the diff are with Codeception integration: https://github.com/infection/infection/pull/143

**Comment by sidz** [comment]
as far as I know behat doesn't support code coverage without additional library (https://github.com/leanphp/behat-code-coverage)

**Comment by borNfreee** [comment]
yes, the same like PHPSpec. Infection requires 3rd party plugin to be installed in order to generate code coverage.

**Comment by maks-rafalko** [comment]
There is no demand on this feature, and it won't be a part of infection/infection anyway. If someone is interested - please comment here and I can probably help with creating a plugin, like we did for Codeception for example https://github.com/infection/codeception-adapter
