### ISSUE TITLE
Element 'filter': This element is not expected.

### ISSUE THREAD

**Issue by ricardoboss** [infection/infection#1474]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.20.2
| Test Framework version | PHPUnit 9.5.1
| PHP version | 8.0.1 w/ xdebug 3.0.2
| Platform    | Windows & GitHub Actions Runner (Ubuntu latest)
| Github Repo | https://github.com/ricardoboss/Philly/tree/datastructures

When running infection without any arguments, I get an invalid PHPUnit configuration generated.

I think this issue is related to #1473.

<details>
 <summary>phpunit.xml</summary>

 ```xml
<?xml version="1.0"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd"
         executionOrder="random">
    <coverage>
        <include>
            <directory suffix=".php">src/</directory>
        </include>
    </coverage>
    <testsuites>
        <testsuite name="Unit Tests">
            <directory>test/Unit/</directory>
        </testsuite>
    </testsuites>
</phpunit>
 ```
</details>

<details>
 <summary>infection.json.dist</summary>

 ```json
{
	"source": {
		"directories": [
			"src"
		],
		"excludes": [
			"/.*Exception\\.php/",
			"Exceptions/ExceptionHandler.php"
		]
	},
	"logs": {
		"text": "php:\/\/stdout",
		"badge": {
			"branch": "master"
		}
	},
	"minMsi": 90,
	"minCoveredMsi": 100
}
 ```
</details>

Output with issue: https://github.com/ricardoboss/Philly/runs/1756185885?check_suite_focus=true#step:6

**Comment by ricardoboss** [comment]
Didnt see the other issue is still open...

**Comment by iamsalnikov** [comment]
Hi! I had the same problem. Did you try to run it like this:

```
XDEBUG_MODE=coverage vendor/bin/infection
```

**Comment by ricardoboss** [comment]
Yes, the linked issue already resolved this, hence why this issue is already closed.

**Comment by maks-rafalko** [comment]
it should work without `XDEBUG_MODE=coverage` on the new Infection versions (I guess starting from 0.26.0), see https://github.com/infection/infection/pull/1518
