### ISSUE TITLE
Invalid mutator config

### ISSUE THREAD

**Issue by theofidry** [infection/infection#1479]
At first glance:

```json
{
    "mutators": {
        "MBString": {
            "settings": {
                "mb_strcut": false
            }
        }
    }
}
```

results in an error although I believe it's the correct way to configure it or at least it's the one suggested from the schema...

Error (in PHP 7.4, infection 0.21.0):

```
PHP Fatal error:  Uncaught TypeError: Return value of Infection\Mutator\MutatorResolver::Infection\Mutator\{closure}() must be of the type array, object returned in /path/to/vendor/infection/infection/src/Mutator/MutatorResolver.php:142
Stack trace:
```

**Comment by maks-rafalko** [comment]
I also can't reproduce the issue for 0.21 and master locally for Infection itself. 

It works for 0.20.1

* for disabling case: https://infection-php.dev/r/5g2p
* for enabling case: https://infection-php.dev/r/60rw

Could you please provide the whole config (probably it's a combination of settings leading to this issue), or minimal reproducible case?

**Comment by theofidry** [comment]
Hm for some reasons I cannot reproduce it anymore locally... I'll close it for now and open it again with a more thorough investigation or a reproducer

**Comment by Spomky** [comment]
Hi,

I have the same issue updating from `v0.20` to `v0.21`.
Surprisingly, if I removed `global-ignoreSourceCodeByRegex` or `MBString` keys it works fine (but not as expected).
Both keys cannot be used together.

Hereafter the trace:

```sh
./vendor/bin/infection -s --threads=$(nproc) --min-msi=95 --min-covered-msi=95
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Infection\Mutator\MutatorResolver::Infection\Mutator\{closure}() must be of the type array, object given in /mnt/vendor/infection/infection/src/Mutator/MutatorResolver.php:142
Stack trace:
#0 [internal function]: Infection\Mutator\MutatorResolver::Infection\Mutator\{closure}()
#1 /mnt/vendor/infection/infection/src/Mutator/MutatorResolver.php(143): array_map()
#2 /mnt/vendor/infection/infection/src/Mutator/MutatorResolver.php(90): Infection\Mutator\MutatorResolver::resolveSettings()
#3 /mnt/vendor/infection/infection/src/Configuration/ConfigurationFactory.php(196): Infection\Mutator\MutatorResolver->resolve()
#4 /mnt/vendor/infection/infection/src/Configuration/ConfigurationFactory.php(137): Infection\Configuration\ConfigurationFactory->resolveMutators()
#5 /mnt/vendor/infection/infection/src/Mutator/MutatorResolver.php on line 142
```

My configuration file:
```json
{
    "source": {
        "directories": [
            "src"
        ]
    },
    "logs": {
        "text": "infection.log"
    },
    "mutators": {
        "@default": true,
        "global-ignoreSourceCodeByRegex": [
           "\\$this->logger.*",
           "\\$this->cache->save.*",
           "parent::build(\\$container);"
        ],
        "MBString": {
            "settings": {
                "mb_substr": false,
                "mb_strlen": false
            }
        }
    }
}
```

**Comment by theofidry** [comment]
Can't reproduce it on the playground but it has not been updated to 0.21 yet: https://infection-php.dev/r/yg6k

**Comment by maks-rafalko** [comment]
Fixed and released https://github.com/infection/infection/releases/tag/0.21.4

**Comment by Spomky** [comment]
Excellent! I will update ASAP my projects and check if it is fine now.
Thank you for the quick fix.
