### ISSUE TITLE
Slack Links

### ISSUE THREAD

**Issue by MGatner** [infection/infection#1481]
Hi, I've been trying to reach out on the support routes before opening an issue. Gitter and Discord both seem pretty sparsely populated but I'll be patient on those. The Slack links don't work - the one in the README (https://symfony.com/slack) says "invitation expired" and the one on the Issue template (https://symfony-devs.slack.com/messages/C78M7A4BY/) requires login (i.e. it is not an invitation).

**Comment by maks-rafalko** [comment]
Seems like this is a coincidence that no one from us answered to your, sorry! Discord is a preferred place to have a discussion, I'm there.

Regarding Slack, I think we should remove that link completely and force people use Discord, where all the tools/authors have been moved recently.

Closing for now, feel free to get in touch in Discord and/or open an issue
