### ISSUE TITLE
TypeError: Argument 1 passed to PhpParser\Node\Scalar\LNumber::__construct() must be of the type int, float given

### ISSUE THREAD

**Issue by DeepDiver1975** [infection/infection#1484]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.21.0
| Test Framework version | PHPUnit 9.5.2
| PHP version | 7.4.15
| Platform    | Debian
| Github Repo | -

<details>
 <summary>Output with issue</summary>

Running initial test suite...

PHPUnit version: 9.5.2

  318 [============================] 7 mins

Generate mutants...

Processing source code files: 214/305PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpParser\Node\Scalar\LNumber::__construct() must be of the type int, float given, called in /home/deepdiver/Development/......../vendor/infection/infection/src/Mutator/Number/IncrementInteger.php on line 81 and defined in /home/deepdiver/Development/......../vendor/nikic/php-parser/lib/PhpParser/Node/Scalar/LNumber.php:25
Stack trace:
#0 /home/deepdiver/Development/......../vendor/infection/infection/src/Mutator/Number/IncrementInteger.php(81): PhpParser\Node\Scalar\LNumber->__construct()
#1 /home/deepdiver/Development/......./vendor/infection/infection/src/Mutator/NodeMutationGenerator.php(143): Infection\Mutator\Number\IncrementInteger->mutate()
#2 /home/deepdiver/Development/......./vendor/infection/infection/src/Mutator/NodeMutationGenerator.php(112): Infection\Mutator\NodeMutationGenerator->generateForMutator()
#3 /home/deepdiver/Development/......../vendor/infection/infection/src/PhpParser/Visitor/MutationC in /home/deepdiver/Development/......../vendor/nikic/php-parser/lib/PhpParser/Node/Scalar/LNumber.php on line 25
</details>

**Comment by sidz** [comment]
@DeepDiver1975  could you please provide code sample which produces this issue? At the first glance I do not see the reason why it may happens.

**Comment by DeepDiver1975** [comment]
Quite hard with the hugh codebase at hand.
Let's see if I can debug this further.

**Comment by DeepDiver1975** [comment]
>  could you please provide code sample which produces this issue?

```
            $value[] = random_int(10000000, 9223372036854775807);

```

When incrementing this max int by one it is not longer an int but a float ..... funny ...

**Comment by sidz** [comment]
Thanks for the code sample.

So
> PHP can only represent big integer values as real integers on systems with a 64-bit architecture and would fall back to approximated float values.

explanation from Doctrine documentation.

also some information you may find here https://www.xspdf.com/resolution/50024441.html

**Comment by maks-rafalko** [comment]
@DeepDiver1975 in case you didn't mentioned in the issue template, we have a Playground that can be used for reproducers, here is the one for the issue you found: https://infection-php.dev/r/v1r1

Thank you!
