### ISSUE TITLE
It would be nice if Infection warned that none of the set up directories are covered by the configured pcov

### ISSUE THREAD

**Issue by HenkPoley** [infection/infection#1497]
I understand that this should be done by PhpUnit and/or pcov, but they are not talking with each other. So I guess it's up to all the unittest runners to check it for them (maybe I need to open tickets for ~~PhpStorm and~~ Visual Studio Code as well 🤔).

* https://github.com/krakjoe/pcov/issues/49
* https://github.com/sebastianbergmann/php-code-coverage/issues/741
* https://youtrack.jetbrains.com/issue/WI-52914

**Comment by sanmai** [comment]
We can check if `ini_get('pcov.directory') === ""`, the default value, and if so update it as we see fit, or just to `"."`. Infection actually in a good position to do this.

**Comment by HenkPoley** [comment]
I'm not sure if changing it live, works (does anything). But sure, good idea, I didn't think of that.

**Comment by sanmai** [comment]
True it can't be changed live (as with `ini_set()`) but we don't need to.
