### ISSUE TITLE
It would be useful if you could kill infection in a way that it still writes out some partial log

### ISSUE THREAD

**Issue by HenkPoley** [infection/infection#1498]
Currently you can have it running for hours on your dev machine, and then you are at a point that you _have_ to edit the code for some reason. So you kill the test run. But nothing useful for all that work gets stored (as far as I know).

**Comment by HenkPoley** [comment]
So.. the default configuration (infection.json.dist) doesn't write any logs?

**Comment by sanmai** [comment]
Probably you are. There are no logs because they're big users of buffer space, and, getting back to the feature request, logs are written after the fact, in a pretty sorted fashion. Using `--show-mutations` is way more efficient.

**Comment by HenkPoley** [comment]
Okay, so maybe have a little thing show up "hmm, your initial test suite is taking longer than 30 seconds, are you sure you want to run without --show-mutations?" 😅

**Comment by HenkPoley** [comment]
In what way is `--show-mutations` more efficient? It's not outputting mutations in-line during runtime. So it still needs to buffer them?

**Comment by sanmai** [comment]
It is, but it only buffers escaped mutations. In your case example it'll be only 8 out of other 1500.

**Comment by maks-rafalko** [comment]
@HenkPoley released in `0.27.0`

**Comment by HenkPoley** [comment]
Ah, thank you, a colleague recently even discovered my CI run from back when I entered this issue 😅
