### ISSUE TITLE
RuntimeException: The process has been signaled with signal "11" / "13"

### ISSUE THREAD

**Issue by kelunik** [infection/infection#150]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.7.1 (`composer show infection/infection`)
| Test Framework version | PHPUnit 6.5.5
| PHP version | 7.2.1-dev (`php -v`)
| Platform    | Ubuntu
| Github Repo | [amphp/aerys @ a883912ae74eff1ff8b2ac650cc0cc8dffecbf9f]( https://github.com/amphp/aerys/tree/a883912ae74eff1ff8b2ac650cc0cc8dffecbf9f)

I tried running Infection on the Aerys test suite, but it always aborts with a `RuntimeException` saying the process has been signaled. How do I debug this? If fails with a different signal and at a different progress with `phpdbg` and `php`.

<details>
 <summary>Output of <code>phpdbg -qrr ./vendor/bin/infection --test-framework-options="--exclude-group hpack"</code></summary>
 
 ```
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____ 
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/
 
Running initial test suite...

PHPUnit version: 6.5.5

   19 [------------------->--------] 10 secs
                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "13".         
                                                          

run [--test-framework TEST-FRAMEWORK] [--test-framework-options TEST-FRAMEWORK-OPTIONS] [--threads THREADS] [--only-covered] [-s|--show-mutations] [-c|--configuration CONFIGURATION] [--mutators MUTATORS] [--filter FILTER] [--formatter FORMATTER] [--min-msi MIN-MSI] [--min-covered-msi MIN-COVERED-MSI] [--log-verbosity [LOG-VERBOSITY]]
```
</details>

<details>
 <summary>Output of <code>php ./vendor/bin/infection --test-framework-options="--exclude-group hpack"</code></summary>
 
```
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____ 
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/
 
Running initial test suite...

PHPUnit version: 6.5.5

  115 [--->------------------------] 18 secs
                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "11".         
                                                          

run [--test-framework TEST-FRAMEWORK] [--test-framework-options TEST-FRAMEWORK-OPTIONS] [--threads THREADS] [--only-covered] [-s|--show-mutations] [-c|--configuration CONFIGURATION] [--mutators MUTATORS] [--filter FILTER] [--formatter FORMATTER] [--min-msi MIN-MSI] [--min-covered-msi MIN-COVERED-MSI] [--log-verbosity [LOG-VERBOSITY]]
```
</details>

**Comment by theofidry** [comment]
I have no idea for now :( Could you give your infection config so that I can give it a try? Not sure when I can, maybe end of the week or next one

**Comment by kelunik** [comment]
@theofidry It's in the repository, but I linked one commit too early.

https://github.com/amphp/aerys/blob/a883912ae74eff1ff8b2ac650cc0cc8dffecbf9f/infection.json.dist

**Comment by sidz** [comment]
seems like it's a segfault. potentially smth went wrong on php side.

tried on latest 7.2.2 and got signal "11" as well.

**Comment by sidz** [comment]
@kelunik yup, it's segfault in phpunit:
<details>
 <summary>Output of <code>vendor/bin/phpunit</code></summary>

```
PHPUnit 6.5.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.2-1+ubuntu17.10.1+deb.sury.org+1 with Xdebug 2.6.0
Configuration: /var/www/amphp/phpunit.xml.dist

...............................................................  63 / 535 ( 11%)
............................................................... 126 / 535 ( 23%)
............................................................... 189 / 535 ( 35%)
............................................................... 252 / 535 ( 47%)
............................................................... 315 / 535 ( 58%)
............................................................... 378 / 535 ( 70%)
............................................................... 441 / 535 ( 82%)
........................Segmentation fault (core dumped)

```

</details>

**Comment by kelunik** [comment]
I kinda expected that, but couldn't reproduce, guess I used the wrong binary, because it doesn't segfault without xdebug.

**Comment by sidz** [comment]
@kelunik on my ubuntu 17.10 with php7.1/7.2.2 + xdebug 2.6 as well as phpdbg are returning segfault. So this issue is not related on infection.

**Comment by wikando-km** [comment]
Got the same problem but inside docker, without phpdbg everything works fine.
