### ISSUE TITLE
Unable to generate prefixed PHAR

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#1507]
Seems like after upgrading `ocramius/package-versions` to 1.11.0 in #1496, it's now not possible to generate prefixed PHAR (`make compile`).

When I use Box 3.10.0, the PHAR is generated, but when it's run, I get the following error:

```
PHP Fatal error:  Uncaught Error: Class "_HumbugBoxb4b9e03217d0\Composer\InstalledVersions" not found in phar:///home/maksrafalko/apps/infection/build/infection.phar/vendor/ocramius/package-versions/src/PackageVersions/Versions.php:28
Stack trace:
#0 phar:///home/maksrafalko/apps/infection/build/infection.phar/src/Console/Application.php(36): _HumbugBoxb4b9e03217d0\PackageVersions\Versions::getVersion()
#1 phar:///home/maksrafalko/apps/infection/build/infection.phar/bin/infection(71): _HumbugBoxb4b9e03217d0\Infection\Console\Application->__construct()
#2 /home/maksrafalko/apps/infection/build/infection.phar(14): require('phar:///home/ma...')
#3 {main}
  thrown in phar:///home/maksrafalko/apps/infection/build/infection.phar/vendor/ocramius/package-versions/src/PackageVersions/Versions.php on line 28
```

When I try to upgrade Box to the latest version, I got the following error (reported to Box project): https://github.com/box-project/box/issues/549

So I'm not sure if this is an issue on our side with misconfiguration or the issue on incompatibility between `ocramius/package-versions` and 3.10.0 Box version.

@theofidry probably you can help here

**Comment by sidz** [comment]
@maks-rafalko shouldn't this issue be closed? As I can see you have already updated Box in https://github.com/infection/infection/commit/cb9e8a709e308745bf7fe689cbdc919a0de9d81e.

Also did a quick test locally and I am able to compile Infection with `ocramius/package-versions` 1.11.0 or 2.1.0

**Comment by maks-rafalko** [comment]
> Also did a quick test locally and I am able to compile Infection with ocramius/package-versions 1.11.0 or 2.1.0

then let's close it

I think we need at some point to look at https://github.com/infection/infection/issues/1508 to make sure it always compiles
