### ISSUE TITLE
PublicVisibility check fails when testing values come from a dataprovider

### ISSUE THREAD

**Issue by thiagocordeiro** [infection/infection#1513]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.21.2
| Test Framework version | PHPUnit
| PHP version | 8.0.1
| Platform    | Ubuntu/MacOS
| Error | https://infection-php.dev/r/m3lz

PublicVisibility check fails when testing values come from a dataprovider

<details>
 <summary>phpunit.xml</summary>

 ```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://phpunit.de/manual/current/en/appendixes.configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/8.4/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         testdox="true"
         bootstrap="vendor/autoload.php">

    <filter>
        <whitelist>
            <directory>src</directory>
        </whitelist>
    </filter>

    <testsuites>
        <testsuite name="Unit">
            <directory>tests/Unit</directory>
        </testsuite>
    </testsuites>

</phpunit>
 ```
</details>

<details>
 <summary>Output with issue</summary>

 ```
PHPUnit 9.3.11 by Sebastian Bergmann and contributors.

E

Time: 00:00.001, Memory: 18.00 MB

There was 1 error:

1) Infected\ReferenceTest::testReference with data set #0 (Infected\Reference Object (...), 'foo', 'foo-0001')
Error: Call to protected method Infected\Reference::getValue() from context 'Infected\ReferenceTest'

/app/infection-builds/m3lz/tests/SourceClassTest.php:18

ERRORS!
Tests: 1, Assertions: 1, Errors: 1.
 ```
</details>

**Comment by sanmai** [comment]
Frankly I don't see what we can do here. Infection does not analyze tests.

**Comment by thiagocordeiro** [comment]
I'm not completely aware how infections works under the hood, but tests fail when in this situation, isn't it the expectation to kill a mutant?

**Comment by sanmai** [comment]
From what it looks like this is 100% expected behavior here.

**Comment by maks-rafalko** [comment]
I think this is related to the issue reported here: https://github.com/infection/infection/pull/1240

After that issue, we've mentioned this problem in our docs: https://infection.github.io/guide/caveats.html

If something can be improved here, please let us know.

**Comment by thiagocordeiro** [comment]
Sounds about right, I've worked around by creating a new test for each static method. A suggestion could be throwing an error the same way it does when tests are not passing, saying tests should be passing and maybe refer to this caveat. Anyhow Infection is amazing ❤️
