### ISSUE TITLE
Speed up Infection runs by remembering which test killed a mutant

### ISSUE THREAD

**Issue by MidnightDesign** [infection/infection#1519]
As @maks-rafalko pointed out to me on Discord, Infection currently runs the tests for a mutant in order from fastest to slowest, but if the killing test is the slowest, it will always be run last.

It might be beneficial for Infection to remember (i.e. save in a file on disk, for example) which test killed a mutant so it can run that test first the next time. If that test wasn't run the last time or or if it doesn't kill the mutant, it could fall back to the current system.

This strategy would be most beneficial in development environments, but it could potentially also be used in CI by committing the mutant -> test map to the repository.

**Comment by maks-rafalko** [comment]
@MidnightDesign feel free to experiment with the first implementation https://github.com/infection/infection/pull/1549

**Comment by maks-rafalko** [comment]
Implemented in #1549
