### ISSUE TITLE
Mutate private method and constants

### ISSUE THREAD

**Issue by TiMESPLiNTER** [infection/infection#1525]
**Problem**
As I understood this package does not mutate private methods and/or constants. This leads to some mutants not being generated/detected which would make sense in my opinion. 

**Example**

```php
// Code
final class Infection
{

    private const MIN_LINE_LENGTH = ' ' . 'hello world';

    public function split(): string
    {
        return self::MIN_LINE_LENGTH;
    }
}

// Test
final class InfectionSpec extends ObjectBehavior
{
    public function it_does_not_split_lines(): void
    {
        $this->split()->shouldContain('hello world');
    }
}
```

In this case I can remove the concatenation (a mutator that actually exists) in the private constant's value and change it to: `private const MIN_LINE_LENGTH = 'hello world';`

And no test will fail and because the inspection package does not do any mutations on private-scoped code there's also no mutant to escape.

Wheras the following code:

```php
final class Infection
{
    public function split(): string
    {
        return ' ' . 'hello world';
    }
}
```

would generate a mutant which actually escapes.

**Describe the solution you'd like**
A solution would be to have an option to enable code mutation on private-scoped code as well.

**Comment by BackEndTea** [comment]
One of the problems is code coverage. We don't know where a const is used in the code, so we woudl have to run all tests.

Another one is that in quite some cases the value of the const is irrelevant. Its used so that everything refers to the same value. E.g. for infection we have some consts which define under what key an attribute on a node is stored. This key can be anything, and changing it won't matter for the end result.

**Comment by sanmai** [comment]
Next, imagine we'd actually mutate class constants. How would you test that, by recording the same constant in a test? What non-trivial value will that bring?

**Comment by TiMESPLiNTER** [comment]
> Next, imagine we'd actually mutate class constants. How would you test that, by recording the same constant in a test? What non-trivial value will that bring?

Well it would force me to write a better/more strict test. Using `shouldBe` instead of `shouldContain`:

```
final class InfectionSpec extends ObjectBehavior
{
    public function it_does_not_split_lines(): void
    {
        $this->split()->shouldBe(' hello world');
    }
}
```

This test then would kill the `const` mutation. So it clearly shows that my tests are not testing the subject good enough.

**Comment by maks-rafalko** [comment]
Just to be clear here: Infection does *not* mutate constants, but it *does* mutate private methods.

**Comment by maks-rafalko** [comment]
@TiMESPLiNTER if you would like to continue discussion, feel free to post here or in our Discord channel https://discord.gg/ZUmyHTJ
