### ISSUE TITLE
Using the splat operator (`...`) to copy an array

### ISSUE THREAD

**Issue by AlexandruGG** [infection/infection#1528]
Hello!

**Is your feature request related to a problem? Please describe.**
Copying an array using the `...` operator is different from copying via assignment because the array pointer is maintained in the second case. It would be great if there would be a mutator which switches one for the other. 

**Describe the solution you'd like**
```PHP
$array = [1, 2, 3];
$array2 = [...$array]; // -> this could be mutated to $array2 = $array;
```

**Additional context**
See example here, I hope this clarifies what I mean: https://3v4l.org/gfW5D#v8.0.8

I noticed there is already a [Spread Mutator](https://github.com/infection/infection/blob/master/src/Mutator/Operator/Spread.php) so I thought this could be something similar to that one, let me know if this makes sense.

**Comment by maks-rafalko** [comment]
Hi, thanks for this feature request. You are very welcome to implement it, shouldn't be hard :)

**Comment by AlexandruGG** [comment]
I'm going to try get familiar with the codebase and give it a shot 😄
