### ISSUE TITLE
How to install and user Infection with Laravel Sail

### ISSUE THREAD

**Issue by piterog** [infection/infection#1530]
How can I install and use Infection on Laravel Sail?

**Comment by sanmai** [comment]
Please see here: https://laravel.com/docs/8.x/sail#executing-composer-commands

**Comment by piterog** [comment]
Let's go..

Thank you for the help..
My problem was not exactly how to install, but how to execute.

Now I have success on this and I will list here my steps:

1) I have installed locally:
`composer require infection/infection`

2) How can I execute?
I can't execute using sail sintaxe, but I have found two ways to do it:
- `sail bash` then `/vendor/bin/infection`
or
`docker-compose exec laravel.test bash -c "vendor/bin/infection"`

**laravel.test** is my container name


Thats it folks.
I hope I can help someone
