### ISSUE TITLE
Infection stops with `[debug] Restarted process exited 9` message

### ISSUE THREAD

**Issue by remorhaz** [infection/infection#1534]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.23.0
| Test Framework version | PHPUnit 9.5.6
| PHP version | 7.4.21
| Platform    | Ubuntu/MacOS
| Github Repo | -

I've stumbled upon a weird crush that occurs with my tests under combination of PHP 7.4 and `amphp/process` >=1.0.3: it just stops with `ERROR: 9` message. I've just figured out the combination playing with `"conflicts"` section of `composer.json` experimentally; so the breaking change should be [in a diff between 1.0.2 and 1.0.3](https://github.com/amphp/process/commit/e7e28219da753f865f9055e87d0b9b110ea607ba).

It's interesting that everything works OK under PHP 8.0.

It's relatively hard for me to provide minimal code that reproduces error: the repo is private and I don't know what exactly causes problem. My tests use custom PHPUnit extension that works with Amp, too - maybe that triggers the problem somehow.

**Comment by maks-rafalko** [comment]
Closing as PHP 7.4, 8.0 are not supported anymore and nobody has reported the same issue
