### ISSUE TITLE
Allow sending stryker-mutator.io reports for multiple branches

### ISSUE THREAD

**Issue by Ocramius** [infection/infection#1536]
Since approximately 2019, I started moving away from the `master` branch naming, and started to use the minor version of libraries as branch name, such as:

 * `1.0.x`
 * `2.1.x`
 * ...

Infection has a configuration for sending information to `stryker-mutator.io`, but only when the branch name matches **precisely**:

https://github.com/infection/infection/blob/f2290b58fff988d17577d43fabf7bb64a1f6049f/src/Logger/BadgeLogger.php#L86

Would a patch to change this into a regex (perhaps new setting, if necessary?) be welcome?

**Comment by maks-rafalko** [comment]
> Would a patch to change this into a regex (perhaps new setting, if necessary?) be welcome?

Absolutely!

related to 

* https://github.com/infection/infection/issues/814
* https://github.com/infection/infection/issues/1137
* https://github.com/infection/infection/pull/1149
