### ISSUE TITLE
`test_it_sorts_faster_than_quicksort` test fails on local environment (and potentially on newer hardware)

### ISSUE THREAD

**Issue by Ocramius** [infection/infection#1537]
| Question    | Answer
| ------------| ---------------
| Infection version | 8c97e07391b9f9b7cf977a62616fc458d435edb1
| Test Framework version | PHPUnit 9.5.0
| PHP version | 8.0.8
| Platform    | Ubuntu 18.04
| Github Repo | -

Running the test suite on latest `master` ( 8c97e07391b9f9b7cf977a62616fc458d435edb1 ), I get following failure:

```
There was 1 failure:

1) Infection\Tests\TestFramework\Coverage\JUnit\TestLocationBucketSorterTest::test_it_sorts_faster_than_quicksort with data set "Ten times the minimal amount of locations" (ArrayIterator Object (...))
Failed asserting that 0.009709596633911133 is equal to 0.01 or is greater than 0.01.

/home/ocramius/Documents/infection/infection/tests/phpunit/TestFramework/Coverage/JUnit/TestLocationBucketSorterTest.php:192
```

The test is probably a bit too fragile, designed perhaps to only run on slower environments. Needs some re-design.

**Comment by maks-rafalko** [comment]
@sanmai probably it's for you. I also notice that (from my point of view) the `abs()` function is dangerous in the test:

https://github.com/infection/infection/blob/master/tests/phpunit/TestFramework/Coverage/JUnit/TestLocationBucketSorterTest.php#L192

Let's say `$totalQuickSort = 1s` and `$totalBucketSort = 30s` (much slower), than with `abs()` this test will pass

**Comment by sanmai** [comment]
Interestingly [the PHP manual suggests to use the same formula](https://www.php.net/manual/en/language.types.float.php) `abs($a-$b) < $epsilon` where other sources point that [this formula is sub-optimal](https://stackoverflow.com/questions/4915462/how-should-i-do-floating-point-comparison) which is indeed what we found here.
