### ISSUE TITLE
Assignment produces infinite loop

### ISSUE THREAD

**Issue by bastianschwarz** [infection/infection#1541]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.23.0
| Test Framework version | PHPUnit 9.5.7
| PHP version | 7.4.21
| Platform    | Debian
| Github Repo | -

Assignment in a for loop runs into a timeout without any clear way to fix it. Yes, if you change += into = the loop will never finish ...

https://infection-php.dev/r/r5yg (here it errors because of memory, it runs into a timout on my dev machine)

Obviously the result of the loop is tested but I don't think this is desired behaviour?

 ```
Timed Out mutants:
==================

1) /.../src/strategy/Suggestions.php:123    [M] Assignment

--- Original
+++ New
@@ @@
             }
         }
         $countFacets = count($facets);
-        for ($index = 0; $index < $countFacets; $index += 2) {
+        for ($index = 0; $index < $countFacets; $index = 2) {
 ```

**Comment by sanmai** [comment]
You should be able to ignore this mutation: https://infection.github.io/guide/usage.html#infection-ignore-all-support

**Comment by bastianschwarz** [comment]
TBH that's a bit disappointing. Sure, I could start adding annotations into my code to silence the QA tool ... do I want to? No. ;)

Also I didn't want to say the whole mutation isn't productive. Of course it's useful to check assignments. But producing endless loops isn't since the only way to guard against this is checking the result which cannot happen because ... endless loop or adding annotations.

Just my 2 cents on this. Thanks anyway ;)

**Comment by sanmai** [comment]
IIRC it's a well known and documented issue. You can see a dedicated class for these mutations in the end report. 
There are other options, for example you can ignore this mutation from the config file, but I tend to think an annotation is simple to comprehend. Either way, you have choices.

But I digress. If you think there's a way to avoid these mutations with some novel workaround, we'll be happy to learn about it.

**Comment by bastianschwarz** [comment]
General question: Is there ever a reason to run the assignment mutator on for loops?

They should be covered by the for loop mutator and you kind of have to test the result your loop produces anyway. Maybe I have to think about this more but I don't see any clear case where the assignment would change result in a way your tests would miss.

**Comment by sanmai** [comment]
It is not, but everything has the cost. For example, we can figure out if we're dealing with exactly this occurrence, but we will have to do this for every mutation, even outside of a loop. Yes, these checks will be fruitless as they are, but they'll take time, they'll make the mutator more complex... In the end who's going to pay for this? It's you, the user.

**Comment by bastianschwarz** [comment]
True. I just had a quick glance and don't know exactly how the mutators work yet so I can't tell what the overhead would be but sure, adding complexity has to be justified.

Just to be clear: I already accepted my fate since I lean towards having false positives instead of punching holes in your QA tools. I think the disappointment was more due to the fast "Just ignore it" and probably a misunderstanding so thanks for reopening and discussing this.

Another cost that should be considered: In my experience a lot of developers (especially in the PHP world) are still not used to solid QA pipelines and tools and get frustrated really fast with false positives (My team wasn't too happy with everything Psalm threw at them and now the next hammer is going to hit :D ) And I have to pay for this by people complaining to me. ;)

I will look into it if I can find some spare time.

**Comment by maks-rafalko** [comment]
Will something like this https://infection-php.dev/r/p2ld resolve your issue? (see config on the right)

* you will not have such mutations in our project
* you will not pollute your source code with Infection-specific annotations to ignore mutations
* we won't need to add complexity to `Assignment` mutator - this will be done on your side - in `infection.json` config

**Comment by bastianschwarz** [comment]
Yes, I didn't see this config or at least my brain did not connect this to my issue. ;) Thanks!
