### ISSUE TITLE
Automatically activate --logger-github in github CI

### ISSUE THREAD

**Issue by mfn** [infection/infection#1560]
I've come up with an infection script / command line combination I would like to use locally as well as on GHA CI.

However in github CI I want to add `--logger-github` but not locally.

No I know I can find ways to do this, but I learned to like that tools use library like https://github.com/OndraM/ci-detector and just auto-detect and activate, like e.g. phpstan did it: https://github.com/phpstan/phpstan-src/commit/6fd85e3b7dae790061b278852b1b34a17e3679c6

I realized infection is already depending on this package https://github.com/infection/infection/blob/8cc8140db3302b990d824dc33b40ffc3b7d9b3ab/composer.json#L56 but it seems it's used for other cases .

What do you think, does something like this make sense?

**Comment by maks-rafalko** [comment]
Sounds good. The only question is do we then need `--logger-github` if it will be detected automatically?

**Comment by mfn** [comment]
I guess a reasonable behaviour would be:
- nothing explicitly specified? detect it
- otherwise the provided option is considered authoritative

does that make sense?

**Comment by maks-rafalko** [comment]
Probably yes. Feel free to contribute

**Comment by mfn** [comment]
@maks-rafalko thanks, I gave it a shot with #1645
