### ISSUE TITLE
Library internal exception, when integer boundry values are present in the source code

### ISSUE THREAD

**Issue by Danon** [infection/infection#1574]
| Question    | Answer
| ------------| ---------------
| Infection version | `0.25.0`, but really all of them
| Test Framework version | PhpUnit 9.5
| PHP version | `8.0.10`, but the bug is on all PHP versions
| Platform    | Ubuntu, but bug is present on all platforms
| Github Repo | https://github.com/T-Regx/T-Regx

When there's an integer boundry value in the source code, like here: 
https://github.com/T-Regx/T-Regx/blob/be5b5f0b585a7b6693f32eca58d67b2ea783e7db/src/CleanRegex/Internal/Number/NumberLowerBound.php#L94
then infection fails to even run mutations on them, because of an internal exception.

## My investigation of the bug

Infection tries to decrease the already lowest possible integer, and gets `float`, which then is used as `int`, which causes an exception.

In my opinion, `DecrementInteger` shouldn't be run on lower integer bounds. I suspect `IncrementInteger` will have a similar bug with upper bound.

## About PHP integers

PHP integers caused me a lot of trouble, when I was working on my `isInt()`/`toInt()` functions in my T-Regx library, so let me share my knowledge.

Things you need to know, before you can understand PHP integers:
 - PHP runtime and PHP parsers are two different beasts
 - Anything too large to fit into `int` gets converted to `float`
 
Now here's the rub.

The boundries of integers, that can be manipulated by PHP in memory (addition, multiplication, etc.) are `9223372036854775807` to `-9223372036854775808` (on 64-bit machines) and `2147483647` to `-2147483648` on 32-bit machines. If you add `1` to the positive boundry, or remove `1` from the negative boundry, you'll get a `float.`

```php
9223372036854775807 + 1
(float) 9.2233720368548E+18
```
```php
-9223372036854775807 - 2
(float) -9.2233720368548E+18
```

This would make sort of sence, but here's another kicker. PHP Parser is dumb. And I mean really dumb. PHP parser, if it sees value above the maximum (so `9223372036854775807` is **parses** it as `float`, even if it's negative :|).

So:
```
// positives work fine
9223372036854775807 // int 9223372036854775807
9223372036854775808 // float 9.2233720368548E+18

// negatives are fucked up
-9223372036854775808 // float -9.2233720368548E+18 - wtf, why is this not an int?
-9223372036854775809 // float -9.2233720368548E+18
```

You may say, "well, how do you know `-9223372036854775808` is a valid int in PHP, maybe `-9223372036854775807` is the lowest?". Well, it isn't, and here' the proof:

```
9223372036854775806 + 1 // int 9223372036854775807
9223372036854775807 // int 9223372036854775807

-9223372036854775807 - 1 // int -9223372036854775808  - actual boundry
-9223372036854775807 - 2 // int -9.2233720368548E+18  - actual boundry exceeded
-9223372036854775808 // float -9.2233720368548E+18 - improper parsing
``` 

PHP can work with `-9223372036854775808`, it just can't parse it :| 

<details>
 <summary>phpunit.xml</summary>

 ```xml
<phpunit bootstrap="vendor/autoload.php"
         forceCoversAnnotation="true"
         failOnRisky="true">
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./src</directory>
            <exclude>
                <directory suffix=".php">./vendor</directory>
            </exclude>
        </whitelist>
    </filter>
    <logging>
        <log type="coverage-clover" target="build/logs/clover.xml"/>
        <log type="coverage-php" target="build/cov/coverage.cov"/>
    </logging>
    <testsuite>
        <directory suffix='.php'>test/</directory>
    </testsuite>
</phpunit>

 ```
</details>

<details>
 <summary>Output with issue</summary>

 ```
Processing source code files: 120/400PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpParser\Node\Scalar\LNumber::__construct() must be of the type int, float given, called in C:\Users\Danon\AppData\Roaming\Composer\ven
dor\infection\infection\src\Mutator\Number\DecrementInteger.php on line 91 and defined in C:\Users\Danon\PhpstormProjects\T-Regx\vendor\nikic\php-parser\lib\PhpParser\Node\Scalar\LNumber.php:25
Stack trace:
#0 C:\Users\Danon\AppData\Roaming\Composer\vendor\infection\infection\src\Mutator\Number\DecrementInteger.php(91): PhpParser\Node\Scalar\LNumber->__construct(9.2233720368548E+18)
#1 C:\Users\Danon\AppData\Roaming\Composer\vendor\infection\infection\src\Mutator\NodeMutationGenerator.php(143): Infection\Mutator\Number\DecrementInteger->mutate(Object(PhpParser\Node\Scalar\LNumber))
#2 C:\Users\Danon\AppData\Roaming\Composer\vendor\infection\infection\src\Mutator\NodeMutationGenerator.php(112): Infection\Mutator\NodeMutationGenerator->generateForMutator(Object(PhpParser\Node\Scalar\LNumber), Object(Infection\Mu
tator\Number\DecrementInte in C:\Users\Danon\PhpstormProjects\T-Regx\vendor\nikic\php-parser\lib\PhpParser\Node\Scalar\LNumber.php on line 25

Fatal error: Uncaught TypeError: Argument 1 passed to PhpParser\Node\Scalar\LNumber::__construct() must be of the type int, float given, called in C:\Users\Danon\AppData\Roaming\Composer\vendor\infection\infection\src\Mutator\Number
\DecrementInteger.php on line 91 and defined in C:\Users\Danon\PhpstormProjects\T-Regx\vendor\nikic\php-parser\lib\PhpParser\Node\Scalar\LNumber.php:25
Stack trace:
#0 C:\Users\Danon\AppData\Roaming\Composer\vendor\infection\infection\src\Mutator\Number\DecrementInteger.php(91): PhpParser\Node\Scalar\LNumber->__construct(9.2233720368548E+18)
#1 C:\Users\Danon\AppData\Roaming\Composer\vendor\infection\infection\src\Mutator\NodeMutationGenerator.php(143): Infection\Mutator\Number\DecrementInteger->mutate(Object(PhpParser\Node\Scalar\LNumber))
#2 C:\Users\Danon\AppData\Roaming\Composer\vendor\infection\infection\src\Mutator\NodeMutationGenerator.php(112): Infection\Mutator\NodeMutationGenerator->generateForMutator(Object(PhpParser\Node\Scalar\LNumber), Object(Infection\Mu
tator\Number\DecrementInte in C:\Users\Danon\PhpstormProjects\T-Regx\vendor\nikic\php-parser\lib\PhpParser\Node\Scalar\LNumber.php on line 25
 ```
</details>

**Comment by Danon** [comment]
If I remove the lowest possible integer from the source then infection works, and doesn't throw the internal exception, but my unit tests start to fail (because of a bug in the code).

I can't reliably use infection now, because it doesn't understand the lower bounds of integers.

**Comment by sanmai** [comment]
It seems like 

$node->value

**Comment by Danon** [comment]
@sanmai But `-9223372036854775807` is not `PHP_INT_MIN` ;)

`PHP_INT_MIN` is `-9223372036854775808`. The problem I'm describing is with `-9223372036854775807`.

Here's the reproduction: https://infection-php.dev/r/w0l5

I explained the parser bug in my first post. `PHP_INT_MIN` is `-9223372036854775808`, but if you type that into source code, it will become `float`. Php parser simply can't parse `-9223372036854775808` as `int`. The only way to put it into source code with with tricks, like `-9223372036854775807-1` or `-9223372036854775806-2` (the bug is probably due to the fact that Php Parser doesn't see negative `-9223372036854775808`, but a positive `-9223372036854775808`, just with an unary minus. And that's just `1` above the `PHP_MAX`).

**Comment by sanmai** [comment]
I appears to me we should be able to fix this problem, as far as Infection is concerned.

```php
    private const PHP_INT_MIN_8 = -9223372036854775808;
    private const PHP_INT_MIN_4 = -2147483648;

    public function minimalValue(): int
    {
        if (\PHP_INT_SIZE === 8) {
            return self::PHP_INT_MIN_8;
        }
        return self::PHP_INT_MIN_4;
    }
```
If you can structure your code like this, the [Infection won't even try to mutate these numbers](https://infection-php.dev/r/022l).

**Comment by Danon** [comment]
> I appears to me we should be able to fix this problem, as far as Infection is concerned.

That's nice to hear, I'm looking forward to it!

> Meanwhile I'd like to propose a workaround.
> [...]
> If you can structure your code like this, the [Infection won't even try to mutate these numbers](https://infection-php.dev/r/022l).

Unfortunately, that doesn't work, because
```php
private const PHP_INT_MIN_8 = -9223372036854775808;
private const PHP_INT_MIN_4 = -2147483648;

public function minimalValue(): int
{
    is_int(PHP_INT_MIN_8); // false
}
```

Because, as I already explained, PHP parses those values as float. I'll be waiting for the infection fix.

**Comment by maks-rafalko** [comment]
Released: https://github.com/infection/infection/releases/tag/0.25.2

please let us know if it works for you

**Comment by Danon** [comment]
@maks-rafalko `Avoid parser bugs for very large negative numbers` hmm... did you mean "very small"? :D haha, cause they're negative. Just joking. Let me check.
