### ISSUE TITLE
Stop generating by default `>` -> `>=` and `<` -> `<=` mutations

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#1587]
I suggest to stop doing the following mutations:

```diff
- if ($a > $b) {
+ if ($a >= $b) {

- if ($a < $b) {
+ if ($a <= $b) {
```

* Mutant lib [did the same](https://github.com/mbj/mutant/pull/1020/files)

Why?

I will copy my question and the answer of `mbj` (author of Ruby's Mutant library):

Question: https://discord.com/channels/767914934016802818/767914934490628138/826567100083994635

> In our PHP project (using Infection) we found that it's sometimes impossible to kill `>` -> `>=` (and `<` -> `<=`) mutations. I found the following PR in Mutant https://github.com/mbj/mutant/pull/1020/files (cc @mbj)
> 
> the question is - did anyone experience the same feelings? and question to @mbj in particular - what does "canonical" term mean in Mutant?

Answer: https://discord.com/channels/767914934016802818/767914934490628138/827197189872025650

> Canonical in mutants terms means strict semantic reduction or orthognal replacement.
> ```
> a >= b
> ```
> 
> is short for:
> ```
> a > b || a == b
> ```
> 
> Now: If I where to mutate `a > b` to `a >= b` I'm semantically mutating to (assuming pure `a` and `b`) to: `a > b || a == b`.
> 
> Which is a clear "addition to a thruth table" (no semanitc reduction or ortogonal replacement)
> 
> Yes its possible to sometimes kill semantic additions, but: Mutant is meant as a "as most generically useful" mutation testing engine) and sticking to canonical operators (that are strict reductions / AKA: remove a column or a row of the "semantic table") or orthognal replacements (flipping a value of a cell) makes mutant scale into many more domains generically. 
> Its also often possible to kill:
> 
> `a`
> 
> 
> to 
> 
> `a; b`
> 
> 
> But its "way harder" if the mutation testing adds new "states".
> Mutant aims to be useful generically, hence I'm removing operators that do not comply to the strict 'canonicalisms' mutant adheres to.
> 

Also, there was a qustion in `#infection` channel with an example where such Mutant is impossible (or not trivial) to kill:

https://discord.com/channels/767914934016802818/771020567343136831/893621965036847125

> I feel like this is going to be a common question, or I'm not seeing the answer easily. How would you counter this escaped mutant? 🙂 https://infection-php.dev/r/z5kx 
> My first thought would be to throw an exception if they're the same and test that is thrown, but in my project, that wouldn't be an option. 

You can see the playground example, killing that mutation is not possible (or I don't see how)

**Comment by Ocramius** [comment]
IMO, `>` to `>=` mutation leads to "did you really test your edge cases" mutations escaping.

You can see it, for example, with `if ($a > Some::LIMIT) {`, and it quickly exposes whether there is an uncovered edge case.

The fact that it may lead to "untestable" edge cases seems minor, compared to this huge advantage.

**Comment by mewejo** [comment]
I raised the example in @maks-rafalko message (https://infection-php.dev/r/z5kx) - My only thought to catch this mutant would be to throw an exception if they're the same and test for that, but that's pretty aggressive if you just need to find the greatest number and don't care if they're the same.

Originally I thought I needed to write tests to kill all mutants, and aim for a perfect MSI, but that's never going to happen with things like this which I can't catch.

Reading @maks-rafalko's message above, it felt like a good idea to remove the `>=`+ mutations, but now I think @Ocramius is right. Mutating to test `if ($a > Some::LIMIT)` is far more valuable than a few escaped mutants.

**Comment by drupol** [comment]
I also find it useful for testing edge cases, but I fully agree with @mbj and the truth table proof.

**Comment by mbj** [comment]
Mutant will actually introduce `>` to `>=` back, once I've a release that allows to opt into "semantic additions". But the default set is exclusively orthogonal replacement and semantic reduction. As this is generically more useful.

Mutant has a huge userbase commercially, and I prefer to ship a default set of operators that is 100% useful. I'll allow the extra set to be run in addition but do NOT by default count against alives. As they are "weaker" in sense of universal usefulness.

**Comment by maks-rafalko** [comment]
ok, let's close then. If particular mutant is escaped, it can be ignored from the config file
