### ISSUE TITLE
Displayed Infection version is not correct

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#1589]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/3725595/136178834-c125f5ad-fd54-4a33-af91-a5018071b152.png">

Probably related to https://github.com/infection/infection/pull/1588

Also, we need to check how schema URLs are generated during the configuration step for new projects (example: https://github.com/infection/infection/blob/master/infection.json#L2 but for the particular version)

*reported by @sidz*

**Comment by yakovakulov** [comment]
Also PHAR version of package shows version as dev-master, but actually i'm using v0.25.3 downloaded from
https://github.com/infection/infection/releases/download/0.25.3/infection.phar
```
php bin/infection.phar --version
Infection - PHP Mutation Testing Framework version dev-master@04f5ab61d309ef1e4825f4a53eb23e3869399b33
```
