### ISSUE TITLE
[Support request] Infection tests are either `uncovered` or `skipped`.

### ISSUE THREAD

**Issue by drupol** [infection/infection#1615]
Hello,

I'm currently making a huge pull request in a project of mine: [`loophp/collection`](https://github.com/loophp/collection/pull/227).
This PR is about migrating from PHPSpec to PHPUnit.

I've always been using infection with PHPSpec and it was working perfectly fine and this is the first time I'm setting up infection with PHPUnit.

The `phpunit.xml` is:

<details>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="./vendor/autoload.php"
         colors="true"
         executionOrder="random"
         failOnWarning="true"
         failOnRisky="true"
         verbose="true"
>
    <testsuites>
        <testsuite name="Test Suite">
            <directory>./tests/unit</directory>
        </testsuite>
    </testsuites>

    <coverage pathCoverage="true" processUncoveredFiles="true">
        <include>
            <directory suffix=".php">src</directory>
        </include>
        <report>
            <xml outputDirectory="build/logs/coverage/coverage-xml"/>
            <html outputDirectory="build/logs/coverage/html-coverage"/>
            <clover outputFile="build/logs/coverage/clover.xml"/>
        </report>
    </coverage>

    <logging>
        <junit outputFile="build/logs/coverage/junit.xml"/>
    </logging>
</phpunit>
```

</details>

The `infection.json` file:

<details>

```json
{
    "timeout": 10,
    "source": {
        "directories": [
            "src"
        ]
    },
    "logs": {
        "github": true,
        "text": "build/logs/infection/infection.log",
        "summary": "build/logs/infection/summary.log",
        "debug": "build/logs/infection/debug.log",
        "perMutator": "build/logs/infection/per-mutator.md",
        "badge": {
            "branch": "master"
        }
    },
    "testFramework":"phpunit"
}
```

</details>

When tests are running (see https://github.com/loophp/collection/runs/4517257659?check_suite_focus=true), I get either a `S` or a `U`, skipped or uncovered.

Could you help me finding what I'm doing wrong?

**Comment by sanmai** [comment]
You have one test that is supposed to test everything, yet it is set to cover only the main class:
```
@covers \loophp\collection\Collection
```
Remove this line, and things should start working as you expected them.

**Comment by drupol** [comment]
Thanks @sanmai for the help.

In order to fix this:

* Remove `@covers` annotation in tests
* Increase `timeout` property in `infection.json`
