### ISSUE TITLE
Avoid using `webmozart/path-util`

### ISSUE THREAD

**Issue by ricardoboss** [infection/infection#1634]
Apparently, [webmozart/path-util](https://packagist.org/packages/webmozart/path-util) is no longer maintained and infection has it as a dependency.

You should consider changing it to a maintained package or the proposed one: [symfony/filesystem](https://packagist.org/packages/symfony/filesystem).

**Comment by maks-rafalko** [comment]
Thanks. `symfony/filesystem` is already [in our composer.json](https://github.com/infection/infection/blob/e55f980bcd73d365d2c15be786cf026cf063e72f/composer.json#L62) / lock file, so feel free to help with getting rid of `webmozart/path-util`

**Comment by ricardoboss** [comment]
Will look into it!

**Comment by ricardoboss** [comment]
The question is, are you willing to drop support for everything below Symfony 5.4? An alternative could be to just "borrow" the small set of functions used (like `isAbsolute` or `canonicalize`) and put them as static functions somewhere in the infection codebase.

What do you think?

**Comment by maks-rafalko** [comment]
> The question is, are you willing to drop support for everything below Symfony 5.4?

hm.. didn't think about it, I guess now, because now we support `"symfony/filesystem": "^3.4.29 || ^4.1.19 || ^5.0 || ^6.0",`

> An alternative could be to just "borrow" the small set of functions used 

then the question is what is better - just continue depending on the abandoned package or copy the code to our codebase? What is the drawbacks of using `webmozart/path-util` except warning message?

**Comment by ricardoboss** [comment]
IMHO it's more of an emotional drawback. It's not really assuring when installing a package and the first thing you see is: "This package has an abadoned dependency!"

Technically it should be fine, I think. (at last as long as it's available on packagist...)

**Comment by theofidry** [comment]
Pretty mch as @ricardoboss pointed out. AFAIK path-util is very stable and didn't require a single patch for several years so code-wise it is unlikely to get out of sync any time soon. So it's mostly about whether the message is prohibitive or not

**Comment by maks-rafalko** [comment]
> IMHO it's more of an emotional drawback. It's not really assuring when installing a package and the first thing you see is: "This package has an abadoned dependency!"

Well, keeping in mind that we can't upgrade to `symfony/filesystem:^5.4` and keeping in mind that _any_ project will see this orange warning message - personally I'm ok to get rid of  `webmozart/path-util` and copy 4 used functions to Infection codebase.

**Comment by RodideBoer** [comment]
I am in favor of this. I hate that abandoned message. If it really is just a handful of functions, please copy them into your own project.
