### ISSUE TITLE
Incompatible declaration of RealPathFilterIterator::toRegex()

### ISSUE THREAD

**Issue by andreasfernandez** [infection/infection#1635]
| Question               | Answer                              |
|------------------------|-------------------------------------|
| Infection version      | 0.25.5 (`infection.phar --version`) |
| Test Framework version | PHPUnit/PhpSpec 9.5.11              |
| symfony/finder version | 4.4.36                              |
| PHP version            | 7.4.26 (`php -v`)                   |
| Platform               | Ubuntu                              |
| Github Repo            | -                                   |

Run infection with active filters is not possible anymore for us as we're hitting type incompatibilities (see the output in the summary).
The following command is sufficient to trigger the error:

```bash
php ./bin/infection --configuration=build/infection.json --filter=oh-noes
```

We're suspecting https://github.com/infection/infection/commit/6844063ee1347c7942734b85ead95ad6226a4a02 to cause the issue.

<details>
 <summary>Output with issue</summary>

```
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Infection - PHP Mutation Testing Framework version 0.25.5

PHP Fatal error:  Declaration of Infection\FileSystem\Finder\Iterator\RealPathFilterIterator::toRegex(string $str): string must be compatible with Symfony\Component\Finder\Iterator\MultiplePcreFilterIterator::toRegex($str) in /var/www/html/vendor/infection/infection/src/FileSystem/Finder/Iterator/RealPathFilterIterator.php on line 80

Fatal error: Declaration of Infection\FileSystem\Finder\Iterator\RealPathFilterIterator::toRegex(string $str): string must be compatible with Symfony\Component\Finder\Iterator\MultiplePcreFilterIterator::toRegex($str) in /var/www/html/vendor/infection/infection/src/FileSystem/Finder/Iterator/RealPathFilterIterator.php on line 80
```
</details>

**Comment by maks-rafalko** [comment]
if I understand the issue correctly, we need to do the following change in Infection source code:

```diff
- protected function toRegex(string $str): string
+ protected function toRegex($str): string
```

then, Symfony 4-6 will be supported, see https://3v4l.org/gbbY7

Feel free to help

**Comment by andreasfernandez** [comment]
Thank you for fixing this issue so fast!

**Comment by maks-rafalko** [comment]
Released as [0.25.6](https://github.com/infection/infection/releases/tag/0.25.6)

Let us know if it doesn't work please :)

**Comment by andreasfernandez** [comment]
I've pushed an update of infection to our CI and everything is fine again. Cheers! :beers:

**Comment by maks-rafalko** [comment]
Cool, thank you!
