### ISSUE TITLE
Consider dropping unpkg remote dependency

### ISSUE THREAD

**Issue by rodber** [infection/infection#1646]
**Is your feature request related to a problem? Please describe.**
I just started using Infection and I noted that the generated HTML log includes [a call](https://github.com/infection/infection/search?q=https%3A%2F%2Fwww.unpkg.com%2Fmutation-testing-elements) to a remote resource:

```html
<script defer src="https://www.unpkg.com/mutation-testing-elements"></script>
```

Unfortunately, this URL is not available 100% of the time and I'm getting constant timeout issues that restrict me from seeing the HTML logs.

**Describe the solution you'd like**
I would like to be able to work with Infection without having to depend on a remotely hosted resource that could fail at any time.

**Describe alternatives you've considered**
I believe that the `mutation-testing-elements` js should be included in local, otherwise host it in a more reliable place (GitHub pages?)

**Additional context**
![image](https://user-images.githubusercontent.com/20590102/149580407-bb7bc5bd-6f84-4db4-9af7-9915bd7a39a0.png)

**Comment by maks-rafalko** [comment]
Interesting, didn't get this error so far.

I see that Stryker Dashboard uses the same url:

```diff
<script src="https://www.unpkg.com/mutation-testing-elements@1.7.8/dist/mutation-test-elements.js"></script>
```

cc @nicojs - did you experience (or Stryker users) anything like this?

**Comment by nicojs** [comment]
Yeah unpkg isn't the most reliable CDN out there. Might be time to switch over to a locally served one, or include it in the JS bundle.

Feel free to open an issue at the dashboard GH repo

**Comment by nicojs** [comment]
True, we would get new updates through dependabot

**Comment by jimaek** [comment]
Consider using https://www.jsdelivr.com/, its built for high availability.
https://cdn.jsdelivr.net/npm/mutation-testing-elements@1.7.8/dist/mutation-test-elements.js

**Comment by nicojs** [comment]
Closed with https://github.com/stryker-mutator/stryker-dashboard/issues/215

**Comment by maks-rafalko** [comment]
Thank you guys for you help and recommendations, made the same change on generated HTML by Infection.
