### ISSUE TITLE
"infection.json does not match the expected JSON schema" when adding both stryker badge and report

### ISSUE THREAD

**Issue by acelaya** [infection/infection#1647]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.1
| Test Framework version | N/A
| PHP version | 8.1
| Platform    | N/A
| Github Repo | N/A

I'm not sure if this is a bug or it's just not supported, but I haven't found any explicit mention in the docs, so reporting just in case.

Basically, after updating to infetion 0.26.0, I have started to use the stryker logger for the badge (I was already using it with the old approach).

However, I also wanted to add the stryker html report, but I have noticed the infection.json schema does not validate if you try to add both, but it does if you add only one of them.

So, both of these are valid, and I can run infection normally:

```json
{
    [...]
    "logs": {
        "stryker": {
            "badge": "develop"
        }
    }
}
```

```json
{
    [...]
    "logs": {
        "stryker": {
            "report": "develop"
        }
    }
}
```

But If I add both:

```json
{
    [...]
    "logs": {
        "stryker": {
            "badge": "develop",
            "report": "develop"
        }
    }
}
```

I get this error when trying to run infection:

```
  "/app/infection.json" does not match the expected JSON schema:                                        
   - [logs.stryker] The property badge is not defined and the definition does not allow additional properties   
   - [logs.stryker] The property report is not defined and the definition does not allow additional properties  
   - [logs.stryker] Failed to match exactly one schema
```

**Comment by maks-rafalko** [comment]
I've added more info to the docs to make it clear.

> You can use either `badge` or `report`, but not both.
> 
> Using HTML report automatically enables badge on Stryker Dashboard.

**Comment by acelaya** [comment]
Thanks!
