### ISSUE TITLE
Negative default parameter value causes mutations to be uncovered

### ISSUE THREAD

**Issue by Riimu** [infection/infection#1648]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.1
| Test Framework version | PHPUnit 9.5.11
| PHP version | 8.1.1
| Platform    | Windows
| Github Repo | -

It seems that when a parameter in a method has a negative default value, infection considers the mutations to the parameters to be uncovered, even if the mutations would be killed successfully.

Reproduction clearly seen here: https://infection-php.dev/r/5kv0

Notice that the only difference between `covered` and `uncovered` method is the default value of the parameter, yet only the mutations to `covered` are considered to be covered and killed.

**Comment by sanmai** [comment]
I wonder if #1633 has anything to do with this.

**Comment by maks-rafalko** [comment]
No, because playground used 0.25.3 and does not have that commit

**Comment by maks-rafalko** [comment]
Fixed indirectly https://infection-php.dev/r/ylyd (the issue was in underlying packages that work with PHP coverage)
