### ISSUE TITLE
Infection crashes when using PHP 8.1 reserved keywords as enum cases

### ISSUE THREAD

**Issue by ABSAhmad** [infection/infection#1656]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.3
| Test Framework version | PHPUnit 9.5.11
| PHP version | 8.1.1
| Platform    | php:8.1-fpm Dockerimage
| Github Repo | -

When using a PHP 8.1 enum with a reserved keyword e.g. `empty` as a case, infection will crash.

Error message:

```
In UnparsableFile.php line 13: Could not parse the file "[removed]/DepotState.php". Check if it is a valid PHP file                                                                                   

In ParserAbstract.php line 161: Syntax error, unexpected T_EMPTY, expecting T_STRING on line 9  
```

Enum example:
```php
enum DepotState : string
{
    case empty = 'empty';
    
    public static function fromLabel(string $stateCode): ?self
    {
        return match ($stateCode) {
            '00' => self::empty,
            default => null
        };
    }
}
```

As far as I can tell, this is an issue with the [nikic/PHP-Parser](https://github.com/nikic/PHP-Parser) package but has been fixed in version [4.13.1](https://github.com/nikic/PHP-Parser/releases/tag/v4.13.1).

See: https://github.com/nikic/PHP-Parser/issues/807

Can I just create a PR updating the PHP parser package or is there something I should pay attention to/take care of?

**Comment by maks-rafalko** [comment]
Am I right that you are using PHAR? 

Released https://github.com/infection/infection/releases/tag/0.26.4

**Comment by ABSAhmad** [comment]
Yes, sorry for not including that information.

Many thanks for the quick fix and release. This solved the issue :)

**Comment by maks-rafalko** [comment]
Thank you @ABSAhmad for sponsoring us!
