### ISSUE TITLE
Missing context for NoLineExecuted

### ISSUE THREAD

**Issue by theofidry** [infection/infection#1665]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.4
| Test Framework version | PHPUnit 9.5.3
| PHP version | 7.4.21
| Platform    | OSX
| Github Repo | https://github.com/humbug/php-scoper

Trying some stuff I had:

```
In NoLineExecuted.php line 47:

  [Infection\TestFramework\Coverage\XmlReport\NoLineExecuted]
  No line of code was executed during tests. This could be due to "@covers" annotations or your
  PHPUnit filters not being set up correctly.
```

While this may be perfectly legit, I think it would be great to be able to provide more information such as which test this is about.

**Comment by manhunto** [comment]
Any updates of workarounds to this error? :)

In my case, this error pop up when I changed files which are not covered by my unit tests. Example: I changed something in the controller which is not covered by my unit tests.

**Comment by theofidry** [comment]
@manhunto if you can provide a reproducer that would be really cool, it's been a very long time since this happened and I failed to provide a reproducer at that time

**Comment by maks-rafalko** [comment]
@theofidry @manhunto were there any reproducer for this issue afer your last message?

**Comment by theofidry** [comment]
Nope, I'll re-open it if I find one...
