### ISSUE TITLE
Show where the log file is located after execution (if there is one)

### ISSUE THREAD

**Issue by theofidry** [infection/infection#1675]
When trying the library on a work project a colleague was a bit confused as to where the log file was (he did not see the infection configuration file). I wonder if maybe it could be useful to display the log file path (if there is any) after the execution.

**Comment by maks-rafalko** [comment]
Related to https://github.com/infection/infection/issues/222#issuecomment-373512682

**Comment by maks-rafalko** [comment]
Related to https://github.com/infection/infection/pull/1472, see discussion
