### ISSUE TITLE
Add possibility to prepend a file to generated bootstrap 

### ISSUE THREAD

**Issue by shvlv** [infection/infection#1681]
**Is your feature request related to a problem? Please describe.**
I'm relatively new to Infection. There is an amazing library. Thanks a lot!

I'm trying to combine Infection with https://github.com/antecedent/patchwork (don't ask me why I need that magic: I work with WordPress so global functions are everything).

The problem is `Patchwork.php` file should be included first. But Infection creates the new bootstrap file and adds user-generated bootstrap in the end. So magic doesn't work.

**Describe the solution you'd like**
I tested a dirty workaround: add `require '/global_path/vendor/antecedent/patchwork/Patchwork.php';` to the https://github.com/infection/infection/blob/804227770afbb876b4cbd24552535ddc0cdd331a/src/TestFramework/PhpUnit/Config/Builder/MutationConfigBuilder.php#L146. All works as expected.

So is it possible to add a CLI flag/configuration to allow prepending to auto-generated bootstrap?

**Describe alternatives you've considered**
I tried PHP Unit flags like `--test-framework-options="--prepend=vendor/antecedent/patchwork/Patchwork.php --process-isolation"` but without success.

**Additional context**

**Comment by maks-rafalko** [comment]
Hello, thanks for using Infection!

Have you tried `bootstrap` configuration setting? (see https://infection.github.io/guide/usage.html)

` infection.json`:

```json
{
    "bootstrap": "./custom-bootstrap.php"
}
```

**Comment by shvlv** [comment]
Hi, @maks-rafalko!
I've tried the `bootstrap` setting but without success. Looks like bootstrap is included once (before command run) but we need to include the file before every test. 

I will try to prepare PR with `prepend` configuration option.

**Comment by maks-rafalko** [comment]
I see.

Are you sure it works as expected when you do "dirty workaround"? Does Infection have killed **and** escaped mutants in this case?

Why I'm asking is because Patchwork [uses Stream Wrapper](https://github.com/antecedent/patchwork/blob/573e93e75b7de11519f0d2cbc4a39a14aa6c82eb/src/CodeManipulation/Stream.php), and I'm not sure it is compatible with Infection's stream wrapper.

We have a similar issue with `bypass-finals`:

* https://github.com/dg/bypass-finals/issues/9
* https://github.com/infection/infection/issues/1275

Please, make sure it's (not) the same issue, just to not waste your time on the implementation.

**Comment by shvlv** [comment]
I've created a test repository.
There is my quick fix - https://github.com/shvlv/infection/commit/ba60d31d16ab986096effdd6d0a2a32993f97fe9

There is the branch with the original infection - https://github.com/shvlv/infection-patchwork (GitHub Action - https://github.com/shvlv/infection-patchwork/actions/runs/2157223680)

There is the branch with the patched infection - https://github.com/shvlv/infection-patchwork/tree/patched-infection (GitHub Action - https://github.com/shvlv/infection-patchwork/actions/runs/2157215149)

I'm not sure about internal logic but seems the fix works for my case...

**Comment by maks-rafalko** [comment]
ok, seems like you are right. One more question: do you have an understanding why **without** patched Infection version all the mutants are escaped?

**Comment by shvlv** [comment]
My new insight.
The assumption about including `Patchwork.php` file as early as possible is not valid (`setUp` place plays nicely, especially with `processIsolation` PHP Unit option). For this case, mutations are escaped https://github.com/shvlv/infection-patchwork/actions/runs/2166059365 because the Patchwork file stream overrides the Infection stream so the tests are run for non-mutated files in fact.

So only possible for me without deep coding is only to ignore classes that have global functions. So Infection could do mutation for normal tests and ignores Patchwork-required tests. https://github.com/shvlv/infection-patchwork/actions/runs/2166073422 

The solution is not very good because the same class could be tested in a functional way (without mocking) and with mocking. 

But my knowledge is not enough to handle the issue properly...

**Comment by maks-rafalko** [comment]
yes, I also have no right solution, unfortunately.

Since Infection doesn't support mutation functions and does not work with any libs that use Stream Wrappers, can we close this particular feature request?

**Comment by shvlv** [comment]
yes, we can. thanks for your support!
