### ISSUE TITLE
It's not clear that coverage driver is not installed when Infection can not generate coverage

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#1691]
![image](https://user-images.githubusercontent.com/3725595/169036347-e14e7ead-32b4-4e8c-9cd3-d4b82b0dece6.png)

Probably, we need to add information in the beginning of this error message that neither `Xdebug` nor `pcov` are installed/enabled.

**Comment by peter279k** [comment]
Just notice that the `XDebug` need to add some options about setting environment variable or PHP ini setting when running the `PHPUnit` command with evaluating the code coverage.

For example, it should be `XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=./build/logs/clover.xml`.

The infection will not do above work and I think the Infection should improve the `phpunitConfiguration.initial.infection.xml` file.

![image](https://user-images.githubusercontent.com/9021747/174577462-b9d536e9-0818-4cc2-af70-20032b73e8a5.png)

When the PHP is with `XDebug` extension support, it should generate the `phpunitConfiguration.initial.infection.xml` with PHP ini setting with `XDebug`.

When the PHP is with `pcov` extension support, it can use the original `phpunitConfiguration.initial.infection.xml` file.

**Comment by sanmai** [comment]
Hey @peter279k I believe we had this issues filed as #1473, and I see that it should be fixed in a recent version. Can you confirm you're using the latest version and still have the issue? If that's the case, please open another issue. Thanks!

**Comment by peter279k** [comment]
My fault. I forgot the `XDEBUG_MODE=coverage` option when running the `./vendor/bin/infection`.

The issue is resolved now.

**Comment by sanmai** [comment]
Well, the thing is you should not be require to add `XDEBUG_MODE=coverage` unless you have it set [to something else](https://xdebug.org/docs/all_settings#mode) (i.e. `develop`).

**Comment by maks-rafalko** [comment]
@peter279k please open a new issue if this is reproduced with 0.26.11 with more details

**Comment by peter279k** [comment]
Just notice that neither the `XDebug` nor `pcov` coverage driver is installed in targeted PHP that it will get clear message in latest Infection version. (0.26.11)

And the error message is as follows:

```
In CoverageChecker.php line 88:
                                                                               
  Coverage needs to be generated but no code coverage generator (pcov, phpdbg  
   or xdebug) has been detected. Please either:                                
  - Enable pcov and run Infection again                                        
  - Use phpdbg, e.g. `phpdbg -qrr infection`                                   
  - Enable Xdebug (in case of using Xdebug 3 check that `xdebug.mode` or envi  
  ronment variable XDEBUG_MODE set to `coverage`) and run Infection again      
  - Use the "--coverage" option with path to the existing coverage report      
  - Enable the code generator tool for the initial test run only, e.g. with `  
  --initial-tests-php-options -d zend_extension=xdebug.so`                     
```

I think this issue is resolved now.

**Comment by maks-rafalko** [comment]
Original issue has been resolved, closing.
