### ISSUE TITLE
Add mbstring in the list of required php extensions

### ISSUE THREAD

**Issue by khalyomede** [infection/infection#1696]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.10
| Test Framework version | Pest 1.2
| PHP version | 8.1.6
| Platform    | Ubuntu
| Github Repo | -

I tried to run infection for the first time, answered all questions, only to end up with an error saying I need mbstring extension installed. It would have been great to prevent installing the package if the extension is not present in the first place.

**Comment by maks-rafalko** [comment]
Totally agree. Feel free to send a PR, will be much appreciated.
