### ISSUE TITLE
Console output when using threads only showing a single muatation

### ISSUE THREAD

**Issue by apps4u** [infection/infection#1704]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.13
| Test Framework version | PHPUnit/Pest
| PHP version | PHP 8.1.7
| Platform    |  Ubuntu WSL2
| Github Repo | -

When I run infection without any threads It takes around 10 minutes to run and I have output showing around 20 `M` from the scanned files as an example.

`UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU.....   ( 3350)
.........MMMMMMMMM.M`

When I run on the same project but I use the `--thread=8` options I only ever get a single `M` in the output and it's a different mutation each time, and I only get a single Diff on the console output as well.

I also have `--show-mutations` options and that is why I noticed this. the HTML report still has the correct info so it's not a show-stopping, But it would be nice to be able to use threads as my run time goes from 10 minutes down to 1 minute but I then miss the console diff output.

**Comment by sanmai** [comment]
If you run your tests in a random order, will you get different failures each time?
```
php vendor/bin/phpunit --order=random
```

**Comment by maks-rafalko** [comment]
Also, please read and try `--noop` option to debug this issue https://infection.github.io/guide/debugging-issues.html

**Comment by maks-rafalko** [comment]
Please reopen if you still have the issue
