### ISSUE TITLE
Mutators break formatting

### ISSUE THREAD

**Issue by danepowell** [infection/infection#1712]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.13
| Test Framework version | PHPUnit
| PHP version | 8.1
| Platform    | MacOS
| Github Repo | https://github.com/acquia/cli/pull/1118

I'm trying to bulk-fix a bunch of mutants (in this case, PublicVisibility and ProtectedVisibility). I've generated a json report of the mutants and I'm applying the changes via a simple PHP script:

```
$json = file_get_contents('infection-report.json');
$decoded = json_decode($json, FALSE);
foreach ($decoded->escaped as $mutant) {
  file_put_contents($mutant->mutator->originalFilePath, $mutant->mutator->mutatedSourceCode);
}
```

The problem is that this completely breaks the code formatting / style of the affected files.

For instance, looking at `$mutant->mutator->originalSourceCode` (and hence `$mutant->mutator->mutatedSourceCode`) reveals this:

```
...
class AcsfCredentials implements ApiCredentialsInterface\n{\n
...
```

This is incorrect because the [actual source for that file](https://github.com/acquia/cli/blob/ebb1cca2cefbc981a7bd7b9fc80b8ca52f71d408/src/AcsfApi/AcsfCredentials.php#L11) keeps the brace on the same line as the class declaration, it should be:

```
...
class AcsfCredentials implements ApiCredentialsInterface {\n
...
```

I understand that our code violates PSR-12 in this particular case, but I still think Infection should respect the original formatting. In another case Infection was inserting a space between a function declaration and the colon before its return type, [violating PSR-12](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-12-extended-coding-style-guide.md#45-method-and-function-arguments). In yet another it was consolidating multi-line control structures into a single ridiculously-long line.

**Comment by sanmai** [comment]
As of writing the pretty printer Infection uses [provides no options to control brace placement or similar](https://github.com/nikic/PHP-Parser/blob/master/doc/component/Pretty_printing.markdown#customizing-the-formatting). You're welcome to improve this situation, although you could just as well look into tools more suited for the job, such as [Rector](https://github.com/rectorphp/rector).

**Comment by danepowell** [comment]
I guess I see the challenge and why I was confused. The "original code" is not just the raw PHP file (as the name would imply), it's actually a parsed and then re-printed version of the file. Maybe the property name could be changed to better reflect that, but yeah, I see why once you've parsed the PHP file into a syntax tree there's no trivial way to restore the original formatting.

Thanks for the link to Rector, although that seems like overkill unless it has a pre-existing integration with Infection.

The code snippet I ended up using as a workaround is here: https://github.com/acquia/cli/pull/1118

**Comment by sanmai** [comment]
Rector has internal integration with PHPStan, so in theory it should be able to infer if a public method isn't used.

Please feel free to close this issue if you no longer need it.
