### ISSUE TITLE
Uncovered Mutants only visible with -vv on console

### ISSUE THREAD

**Issue by mimmi20** [infection/infection#1716]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.13
| Test Framework version | PHPUnit 9.5.21
| PHP version | 8.1.8
| Platform    | Ubuntu 22.04
| Github Repo | https://github.com/mimmi20/device-detector-factory

The uncovered Mutants are only visible on the console output if the `-vv` option is present. 

The tests were run with different options

| Options | Github Testrun | Uncovered Mutants visible | |
|----------|-----------------|-------------------------------|--
| infection --show-mutations --logger-github | https://github.com/mimmi20/device-detector-factory/runs/7733779066?check_suite_focus=true#step:8:1 | no |
| infection --show-mutations --logger-github --log-verbosity=all | https://github.com/mimmi20/device-detector-factory/runs/7733709143?check_suite_focus=true#step:8:1 | no |
| infection --show-mutations --logger-github --log-verbosity=all --debug | https://github.com/mimmi20/device-detector-factory/runs/7733779066?check_suite_focus=true#step:8:1 | no |
| infection --show-mutations --logger-github -vv | https://github.com/mimmi20/device-detector-factory/runs/7733957592?check_suite_focus=true#step:8:1 | yes | the Box Requirements Checker is twice in the console output
| infection --show-mutations --logger-github --log-verbosity=all -vv | https://github.com/mimmi20/device-detector-factory/runs/7734049924?check_suite_focus=true#step:8:1 | yes | the Box Requirements Checker is twice in the console output
| infection --show-mutations --logger-github --log-verbosity=all --debug -vv | https://github.com/mimmi20/device-detector-factory/runs/7734049924?check_suite_focus=true#step:8:1 | yes | the Box Requirements Checker is twice in the console output

**Comment by maks-rafalko** [comment]
Those are **uncovered** mutants and by default they are not shown by `--show-mutations` option, only with. This option only shows **escaped** mutants.

So functioning as developed.

**Comment by theofidry** [comment]
Just for clarify: checking uncovered mutants is very likely not helpful. It is more effective to take a look at the (PHPUnit or other) coverage and see what code is not covered
