### ISSUE TITLE
Problems with autoload when using infection from phive. 

### ISSUE THREAD

**Issue by tomasnorre** [infection/infection#1732]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.15
| Test Framework version | PHPUnit 9.5.25
| PHP version | 8.0.24 (`php -v`)
| Platform    | Ubuntu
| Github Repo | https://github.com/tomasnorre/crawler/pull/944

When installing infection with Phive, using the phar or globe compose require, the autoloading isn't working, my classes aren't found any more.

Any suggestions what it could be? My psalmphp is working after the switch.

This started from https://twitter.com/infection_php/status/1565822628337680384

Unfortunately I haven't been able to reproduce this in other reprositories, to it's a clear indication that something in wrong in my setup. But haven't figure it out yet. 

When running the infection command I get following error: 

```shell 
In CoreClassReflection.php line 15:
                                                                   
  Class "AOE\Crawler\Backend\Helper\ResultHandler" does not exist  
                                                                   
```

But when looking into the composer autoloader the file is defined: 

```shell
grep -rn 'AOE\\\\Crawler\\\\Backend\\\\' .Build
.Build/Web/typo3conf/autoload-tests/autoload_classmap.php:10:    'AOE\\Crawler\\Backend\\Helper\\ResultHandler' => $typo3InstallDir . 'typo3conf/ext/crawler/Classes/Backend/Helper/ResultHandler.php',
``` 

As mentioned I'm pretty sure this is a problem in my repository, but I don't know how to solve this based on the information I have right now, so I would really appreciate some hints that could help me out. 

<details>
 <summary>phpunit.xml</summary>

 ```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.5/phpunit.xsd"
         bootstrap="../.Build/vendor/nimut/testing-framework/res/Configuration/UnitTestsBootstrap.php"
         cacheResultFile=".phpunit.cache/test-results"
         executionOrder="depends,defects"
         forceCoversAnnotation="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTodoAnnotatedTests="true"
         failOnRisky="true"
         failOnWarning="true"
         verbose="true">
    <testsuites>
        <testsuite name="default">
            <directory>../Tests/Unit</directory>
        </testsuite>
    </testsuites>

    <coverage cacheDirectory=".phpunit.cache/code-coverage"
              processUncoveredFiles="true">
        <include>
            <directory suffix=".php">../Classes</directory>
        </include>
    </coverage>
</phpunit>

 ```
</details>

**Comment by maks-rafalko** [comment]
I'm going to close it as this seems to be a local issue. Personally, I'm not able to spend time these days on finding issue in particular repo (I'm sorry but it's reality), so I think this will be never solved unless we have a volunteer.

**Comment by Seb35** [comment]
I saw this error, which is emitted by [ReflectionClass](https://github.com/php/php-src/blob/master/ext/reflection/php_reflection.c). In my case, I had a "bootstrap" entry in phpunit.xml.dist, but I did not configure the parameter "bootstrap" in infection.json5 (I thought it was automatically configured from phpunit.xml.dist), and then infection worked fine when I configured this parameter.
