### ISSUE TITLE
Errors encountered

### ISSUE THREAD

**Issue by danepowell** [infection/infection#1737]
In a recent PR, Infection started reporting errors using the Git Diff filter and I cannot figure out why or what the errors even are.

Here's the PR and associated test run, with all debugging enabled:
- https://github.com/acquia/cli/pull/1209 (I may merge this by the time you see it)
- https://github.com/acquia/cli/actions/runs/3245703460/jobs/5323575106

I've tried Infection 0.26.13 and 0.26.15 with the same results. I've only seen this happen on this one PR so far. I just want to figure out what the errors are so I can start to debug.

**Comment by maks-rafalko** [comment]
Please run Infection with `--log-verbosity=all` and add `text` logger here https://github.com/acquia/cli/blob/main/infection.json#L8

Infection will generate a file with errors inside, so we can understand better what is the output.

I think the easiest wayis to `cat infection.log` (or whatever you name it) after infection execution to see its content.

**Comment by danepowell** [comment]
Thanks! I think this is progress, but I still don't understand why these are being reported as "errors" instead of just plain old escaped mutants, as I see no error messages in the logs.

https://github.com/acquia/cli/actions/runs/3261870030/jobs/5357717577#step:5:166

(Thanks for the link btw, I didn't see that in the docs because I saw [this page](https://infection.github.io/guide/debugging-issues.html) first and didn't see the debugging info at the bottom)

**Comment by maks-rafalko** [comment]
Going to close it as nobody reported the same problem. If it still the issue, please reopen and provicde new reproducible
