### ISSUE TITLE
Same change counted as two failures

### ISSUE THREAD

**Issue by Bilge** [infection/infection#1738]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.15
| Test Framework version | PHPUnit 9.5.25
| PHP version | 8.x
| Platform    | All
| Github Repo | https://github.com/ScriptFUSION/Porter

As shown in the [job output](https://github.com/ScriptFUSION/Porter/actions/runs/3255738487/jobs/5345363994#step:9:43), the same change is generated by _[M] Assignment_ and _[M] AssignCoalesce_, thus counting against the MSI score twice for the same issue. This does not seem fair. I understand they are separate mutators, but if they generate the same code they should collapse into one test, not two.

**Comment by sidz** [comment]
Good catch. Thank you for the bug report.

here is a PR https://github.com/infection/infection/pull/1739
