### ISSUE TITLE
Add an option to pass additional parameters to the PHP binary

### ISSUE THREAD

**Issue by addiks** [infection/infection#174]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.7.1
| Test Framework version | PHPUnit 6.5.6
| PHP version | PHP 7.1.14-1+ubuntu16.04.1+deb.sury.org+1
| Platform    | Ubuntu 16.04.3 LTS
| Github Repo | Not specific to one repo; It's specific to my machine

TL;DR: This is a feature-request for a new parameter "--php-arguments" for infection with that one can specify additional parameters to be given to the php executable that is used to start phpunit.

On my machine i enable xdebug on a per-process basis. Per default, xdebug is disabled. This is bebause xdebug can seriously slow down some processes. If i need xdebug to be enabled in a process, it pass the parameter "-d zend_extension=xdebug.so" to the process (mostly by using bash-aliases).

```bash
# ~/.bash_rc
...
alias phpd='php -d zend_extension=xdebug.so -d xdebug.remote_autostart=1 '
alias phpp='php -d zend_extension=xdebug.so -d xdebug.profiler_enable=1 '
alias phpx='php -d zend_extension=xdebug.so'
...
```
Xdebug is per default disabled in the php-module-config "/etc/php/7.1/cli/conf.d/20-xdebug.ini":
```ini
;zend_extension=xdebug.so

[xdebug]

xdebug.remote_enable=On
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_port=9000
xdebug.remote_host=127.0.0.1
xdebug.remote_autostart=Off
xdebug.remote_log=/var/log/xdebug_remote.log

```
With this configuration infection does not work out of the box, instead it tells me to use phpdbg or xdebug:
```bash
$ infection
You need to use phpdbg or install and enable xdebug in order to allow for code coverage generation.
$
```
And when i try to run infection with xdebug (see above), this happens:
```bash
$ phpx ~/.config/composer/vendor/infection/infection/bin/infection
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____ 
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/
 
Running initial test suite...

PHPUnit version: 6.5.6

   44 [============================] < 1 sec

Generate mutants...

Processing source code files: 78/78
Creating mutated files and processes:   0/278
In CoverageDoesNotExistException.php line 18:
                                                                                                                                                                                         
  Code Coverage does not exist. File /tmp/infection/coverage-xml/index.xml is not found. Check phpunit version Infection was run with and generated config files inside /tmp/infection.  
                                                                                                                                                                                         

run [--test-framework TEST-FRAMEWORK] [--test-framework-options TEST-FRAMEWORK-OPTIONS] [--threads THREADS] [--only-covered] [-s|--show-mutations] [-c|--configuration CONFIGURATION] [--mutators MUTATORS] [--filter FILTER] [--formatter FORMATTER] [--min-msi MIN-MSI] [--min-covered-msi MIN-COVERED-MSI] [--log-verbosity [LOG-VERBOSITY]]

$
```
Infection iteself runs with xdebug enabled but then (probably) goes on and starts another php-process without the needed parameter to enable xdebug. PHPUnit then fails to create coverage because xdebug is not active in it's php process and infection fails without it's coverage report.

The only way i have found to get infection to work is if i permanently activate xdebug, which is not a long-term solution because other processes require xdebug to be turned off to achieve any viable performance.

The best permant solution in my opinion would be a new parameter to tell infection that it has to pass additional parameters (like "-d zend_extension=xdebug.so") to the php binary. Then something like this would be possible:
```bash
$ phpx ~/.config/composer/vendor/infection/infection/bin/infection --php-arguments="-d zend_extension=xdebug.so"
```
On my machine i then would wrap this long command into another alias called "infection" and all would be well.

If nobody is able (or willing) to implement this short term i could do it myself and create a PR (if the maintainer(s) give me their OK). I'm just currently involved in other things and that would take some time before i can begin working on this (and i would have to make myself known with the inner workings of infection first).

**Comment by sidz** [comment]
Good point. 👍  

But I'm not sure about the naming. As for me `--php-arguments` it's smth like should be global for Infection itself + all inner process builders as well. Maybe we can use smth like --test-framework-php-args' or smth similar. 

Also right now we need to have this argument only for the `InitialTestsRunner` and these options shouldn't pass into the `MutationTestingRunner`.
What will we do if need to add additional extra options for the `MutationTestingRunner`?

It'll be good to find the best approach to avoid any BC break changes in the future.

I'd say that `php -d zend_extension=xdebug.so bin/infection` will be the best case. We can try to parse it and still disable xdebug on fly but also we can save somewhere (env) these options and push all of them into the InitialTestsRunner and all options except `xdebug.` to the MutationTestingRunner.

@addiks, @borNfreee, @theofidry, @BackEndTea thoughts?

**Comment by borNfreee** [comment]
> I'd say that php -d zend_extension=xdebug.so bin/infection will be the best case but seems like we can't get these params right in Infection.

I also can't find a way how to get php arguments with such a command line :(.

So then we should pass it as an option unless someone has a better idea.

My thoughts:

1. Since we already have [--test-framework-options](https://infection.github.io/guide/command-line-options.html#test-framework-options), I would suggest to be consistent here and use `options` word instead of `args`. Moreover, `-d zend_extension=xdebug.so` is actually an option, argument is a `bin/infection`.

```bash
$ php --help
Usage: php [options] [-f] <file> [--] [args...]
...
```

2. `What will we do if need to add additional extra options for the MutationTestingRunner?` - this is a good concern. Then, to make it precise, I would suggest something like

*  `--initial-tests-php-options="-d zend_extension=xdebug.so"`
*  `--mutation-testing-php-options="..."`

or something similar

**Comment by addiks** [comment]
I think that a parameter/argument/option should be the preferred solution, whatever it's names will be. 
Parsing and guessing the parameters given to php by infection relies on too many assumptions, for example that the module's filename is actually "xdebug.so" or that the include does not happen in some custom php-ini-file ("php -c my-xdebug-incuding-config.ini vendor/bin/infection").

Although i'm not sure "--initial-tests-php-options" is the best name for that option because it does not tell the purpose of the tests that are run with these options, just that they are the first (and even that could theoretically change at some point). I would propose something along the lines of "--coverage-collection-php-options".

**Comment by borNfreee** [comment]
> Parsing and guessing the parameters given to php by infection relies on too many assumptions

👍 

> I would propose something along the lines of "--coverage-collection-php-options".

On the other side, providing already existing in master`--coverage` option, we do not generate coverage anymore by Infection, so `--coverage-collection-php-options` is not always point to the actual behaviour. It would be confusing to pass coverage options when no coverage is being generated.

Internally, we have 2 phases 1) Initial tests and 2) Mutation testing. I would stick to them or think about the third solution, but have no idea atm.

**Comment by sidz** [comment]
@addiks, @borNfreee here is the PR https://github.com/infection/infection/pull/185. Feel free to add any recommendations.

**Comment by sidz** [comment]
🚢
