### ISSUE TITLE
Support readonly class being introduced by 8.2

### ISSUE THREAD

**Issue by fefas** [infection/infection#1748]
I am already trying PHP 8.2 and I get the following error:

```
Syntax error, unexpected T_READONLY, expecting T_CLASS on line ***
```

The files are like
```php
<?php

namespace MyApp;

final readonly class MyClass
{
    // ...
}
```

Opening this issue since I could not find any related to this problem.

**Comment by fefas** [comment]
Started debugging it and realized this issue should go to https://github.com/nikic/PHP-Parser, right?

**Comment by maks-rafalko** [comment]
Seems like yes.

`readonly` classes were added to PHP-Parser [on 4.14.0](https://github.com/nikic/PHP-Parser/blob/4.x/CHANGELOG.md#version-4140-2022-05-31), but Infection [uses 4.13.2](https://github.com/infection/infection/blob/d646aafe530ba21b8479694cd151570c93c72312/composer.lock#L476)

Feel free to open a PR upgrading PHP-Parser

**Comment by fefas** [comment]
Thx! PR is already created :)
