### ISSUE TITLE
Revisit the supported versions

### ISSUE THREAD

**Issue by theofidry** [infection/infection#1760]
I think Infection reached a good level of stability. Of course we can all find more features, bugs & co, but there is now a good set of versions behind it and a good usage adoption.

PHP 7.4 is EOL, 8.0 is in security fix only and 8.2 around the corner. What do you think of dropping support for PHP 7.4 & 8.0?

I think users that are still on 7.4 / 8.0 can live with the current infection versions and don't need (or cannot anyway) be on the bleeding edge.

Disclaimer: I do use infection in a few PHP 7.4 repo still.

**Comment by sidz** [comment]
we support the lowest PHP version till the end of its life. My 2 cents is to keep support 8.0

**Comment by theofidry** [comment]
FWIW I feel supporting PHP 8.0 is like at a time supporting 7.0 instead of 7.1... Upgrading to 8.0 might not be trivial, but 8.0 to 8.1 is and the feature set is quite significant. The property promotion alone or first-class callable support for example. The infection codebase would benefit _a lot_ from those two alone

**Comment by maks-rafalko** [comment]
> we support the lowest PHP version till the end of its life.

do we? As far as I see, each year we drop support of the PHP version that is not maintained anymore (green background here https://www.php.net/supported-versions.php)

This January we dropped support for PHP 7.4: https://github.com/infection/infection/pull/1641
IMO, now we *can* drop support of PHP 8.0.

PHP 8.1 is used by 61% of our uses and PHP 8.0 by 26: https://packagist.org/packages/infection/infection/php-stats#0.26

![image](https://user-images.githubusercontent.com/3725595/205090319-d11c71a2-a8c6-45bc-bee6-cb304fac2583.png)

So, personally I'm ok with PHP 8.0 drop (users still can use the older versions of Infection if needed)
