### ISSUE TITLE
[Repo Settings] Require to resolve comments before merge

### ISSUE THREAD

**Issue by theofidry** [infection/infection#1764]
To enable: Settings -> Branches -> Rules -> Require conversation resolution before merging 

I think this setting is useful to ensure the merge does not miss any comments. For example you do a review but also feel the notes are nitpicks, you don't feel strongly about them or you are confident the author will address them the way you want, then you can submit the review and approve and the merge doesn't risk to merge it without taking a look at your comments.

WDYT?

**Comment by maks-rafalko** [comment]
Makes sense to me, enabled. Let's see how it will go

**Comment by sanmai** [comment]
I would argue against it. 
- Conversations often contain valuable points and arguments, needed to understand the PR.
- Resolving every conversation hides valuable arguments from the view and forces the reader to open every conversation even those not worthy being unresolved.
- This could also lead to an opposite effect: conversations getting resolved without first addressing the question in them. And then nobody ever will know there was an unresolved question.

This is a great option for projects such as related to documentation where you can truly resolve a question for good. For a really complex project such as Infection it doesn't make as much sense. 

Can we have it back to the default?

**Comment by maks-rafalko** [comment]
Reverted
