### ISSUE TITLE
RFC: temporarily add `"conflict": {"phpunit/php-code-coverage": ">9.2.17"}`  to constraints

### ISSUE THREAD

**Issue by Ocramius** [infection/infection#1773]
As mentioned in the title, it would be useful to (temporarily) add `"conflict": {"phpunit/php-code-coverage": ">9.2.17"}` to the constraints of this package.

The reason: coverage report became massively unreliable for the purposes of mutation testing starting with `phpunit/php-code-coverage:9.2.18`, as reported by @kukulich and acknowledged by @Slamdunk in https://github.com/sebastianbergmann/php-code-coverage/issues/953

This is only a temporary measure: @Slamdunk has been talking with me about it, and he's hard at work on it in https://github.com/sebastianbergmann/php-code-coverage/pull/964, which should fix the problem, but which may take more time to land.

At this moment, many mutation test suites keep going red due to invalid reduced coverage (some packages were even at 100%, and need constant adjustments when `composer.lock` gets changed).

Therefore, it would be healthy to declare an incompatibility in a new minor release, for now.

Sorry if this puts more load on your end :-(

**Comment by Ocramius** [comment]
Note: I can send a patch as soon as I get feedback - didn't want to butt in directly with a PR :)

**Comment by sanmai** [comment]
Sounds good to me. Infection has this issue too.

**Comment by Ocramius** [comment]
@sanmai what would be the correct target branch for a PR here?

I generally do new minor releases for dependency changes, but `infection/infection` is still `0.x` :D

**Comment by theofidry** [comment]
@Ocramius I reckon master is good enough, although that may mean the release is going to be a few days/weeks away still.
