### ISSUE TITLE
False positive: `Throw_` mutant not covered by tests

### ISSUE THREAD

**Issue by ghostwriter** [infection/infection#1778]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.16
| Test Framework version | PHPUnit 9.5.27
| PHP version | 8.1.13
| Platform    | MacOS & Ubuntu
| Github Repo | `ghostwriter/option` `ghostwriter/result`

1) [`ghostwriter/option/src/Traits/OptionTrait.php:70`](https://github.com/ghostwriter/option/blob/31398c8d01e4be899ebb880b5fbf2750a133b9af/src/Traits/OptionTrait.php#L67-L74)    [M] Throw_
```diff
--- Original
+++ New
@@ @@
     public function expect(Throwable $throwable) : mixed
     {
         if ($this instanceof NoneInterface) {
-            throw $throwable;
+            $throwable;
         }
         return $this->value;
     }
```

This test explicitly checks that the method throws a specific exception with a specific exception message, but that doesn’t satisfy infection. [`ghostwriter/option/tests/Unit/NoneTest.php:102`](https://github.com/ghostwriter/option/blob/31398c8d01e4be899ebb880b5fbf2750a133b9af/tests/Unit/NoneTest.php#L93-L106)

I keep seeing multiple instances of this same error in many repositories.

I believe it is a false positive or bug because, in each instance, I have 100% test coverage.

eg. :
https://github.com/ghostwriter/option/actions/runs/3710778536/jobs/6290589145
https://github.com/ghostwriter/result/actions/runs/3710486045/jobs/6290051681

**Comment by sanmai** [comment]
Please try:
```
composer require --dev phpunit/php-code-coverage:^9.2.21
```
And report if you still have the issue.

**Comment by ghostwriter** [comment]
I still have the same issue.

**Comment by sanmai** [comment]
Here's what I did.

I generated a coverage report with `php vendor/bin/phpunit --coverage-html=coverage` and saw:

![](https://user-images.githubusercontent.com/139488/208084228-69b6b134-bb64-4a0e-a110-941a8ebecada.png)
Then I downgraded the package to the earliest known working version as per #1773:
```
composer require --dev phpunit/php-code-coverage:=9.2.16
```
And saw:
![](https://user-images.githubusercontent.com/139488/208084334-a8bb0156-33db-4ad5-92da-48d2066367ee.png)

**Comment by Slamdunk** [comment]
Yup, an easy fix is needed in `phpunit/php-code-coverage` indeed, hope to propose it today

**Comment by romm** [comment]
I can confirm with a similar issue, see https://dashboard.stryker-mutator.io/reports/github.com/CuyZ/Valinor/master#mutant/Type/Types/UnresolvableType.php

**Comment by Slamdunk** [comment]
Fix proposed in https://github.com/sebastianbergmann/php-code-coverage/pull/969

**Comment by ghostwriter** [comment]
@sanmai Thanks for your help pinpointing the main issue and @Slamdunk Thanks for providing the solution.

**Comment by sanmai** [comment]
Shall we close this as completed?

**Comment by ghostwriter** [comment]
Personally, I’d wait until there’s a new tag released for `sebastianbergmann/php-code-coverage`, but ultimately the issue has been addressed so I’m okay with your decision.

**Comment by sanmai** [comment]
Thanks for raising this issue. I don't see we can do anything more here. If there is more to the issue, please inspect the coverage report and raise any issues with the packages where they appear. Thanks.
