### ISSUE TITLE
`LogicalOr` to `&&` must not be applied to same variable test

### ISSUE THREAD

**Issue by Neirda24** [infection/infection#1796]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.16
| Test Framework version | PHPUnit 9.5.27
| PHP version | 8.1.13
| Platform    | MacOS
| Github Repo | https://infection-php.dev/r/yl6e

```php
$numberOfMatches = preg_match_all('something', $string, $matches); 

if (false === $numberOfMatches || 0 === $numberOfMatches) {
    // do something
}
```

cannot be replaced with

```php
$numberOfMatches = preg_match_all('something', $string, $matches); 

if (false === $numberOfMatches && 0 === $numberOfMatches) {
    // do something
}
```

using the `LogicalOr` mutator.

The same variable can't be both `false` and `int` using the `===` strict comparison.

**Comment by maks-rafalko** [comment]
Feel free to submit the PR to fix this issue. The place to start: 

https://github.com/infection/infection/blob/a222e757657f252bce05505ce5910520a9c21fc7/src/Mutator/Boolean/LogicalOr.php#L75

**Comment by Neirda24** [comment]
Sure will try to take a look. Thanks for the heads up.
