### ISSUE TITLE
ProtectedVisibility False positive on implementation of abstract methods

### ISSUE THREAD

**Issue by luispabon** [infection/infection#180]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.7.1
| Test Framework version | PHPUnit 7.0.1
| PHP version | 7.2.2
| Platform    | Ubuntu

I'm getting some false positives that I believe are avoidable.

Given the following classes:

```php
abstract class Foobar
{
    abstract protected function yay(): void;
}

class Doom extends Foobar
{
    protected function yay(): void
    {
        return;
    }
}
```

I get the following false positive on the logs
```diff
14) /home/luis/stuff/sumfile:21    [M] ProtectedVisibility

--- Original
+++ New
@@ @@
-    protected function yay(): void
+    protected function yay(): void
     {
          return;
     }
```

It is a false positive as abstract methods and their implementations cannot possibly be private.

**Comment by BackEndTea** [comment]
Thank you for reporting this bug. It is a known issue, and being worked on in #67, which we hope to implement soon.

**Comment by sidz** [comment]
we already have issue in the tracker: https://github.com/infection/infection/issues/63.

**Comment by luispabon** [comment]
Thank you, although that issue on the tracker refers to interfaces and not abstract methods.
