### ISSUE TITLE
New feature: provide a summary-json report

### ISSUE THREAD

**Issue by niconoe-** [infection/infection#1807]
I am experiencing a size issue using the JSON logger from PHP Infection. On some of my projects with more than 5k mutants to kill, it weight more than 700Mb. I'm using this file only for main statistics (nb killed mutants, nb still alive, …) but through a parser as I need to programmatically find those information.
I used to use the "summary" logger which was very small, but it's hard to programmatically parse a text file, so I moved to "json" logger, which is really more convinient but I did not expect a JSON file as big as a 720p DVDRip movie :smile: 

Do you think it would be possible to have a new logger "json-summary" that will just give the same information than the "summary" logger, but in a JSON format? 

My current alternative is to either get back on the text file (brr...) or to use `jq` in my process to only pick up the stats from the big json file, but I'm not a fan of putting 700Mb in RAM with `jq` just to extract a list of maximum 10 integers…

If this idea is not rejected, I'm ready to provide a PR to support this new logger.

Thanks a lot.

**Comment by maks-rafalko** [comment]
Thanks for the detailed issue. I'm personally ok with introducing a new logger (json summary).

The only one minor point, can we name it `summary-json` instead of `json-summary`, to make it sound more natively as `summary.json` :)

**Comment by niconoe-** [comment]
> The only one minor point, can we name it `summary-json` instead of `json-summary`, to make it sound more natively as `summary.json` :)

I don't mind about the name :slightly_smiling_face: . `summary-json` is OK to me.

Just to let you know, I would prefer to wrap the list of sum-up statistics into a `stats` object just like the original `json` logger so that we will be homogeneous between the 2 loggers. If you disagree about it and prefer to have all values at root level, I'm fine, too, so tell me as soon as you can so I will adapt my (in progress) PR :slightly_smiling_face:
