### ISSUE TITLE
[Logs] Add colorful text log for CLI output

### ISSUE THREAD

**Issue by Slamdunk** [infection/infection#1810]
Hi, I'd like to have a colorful text log for CLI.
I am aware of the precious logs that are already present, like `HTML`, `JSON`, `Summary` and `Stryker`, but they are not very TDD friendly.
This is particularly necessary since Infection removes all indentation, so murators like `ArrayItemRemoval` are very hard to read when hundreds of LoC are compressed in a single line in `text` output.

I'm currently workarounding this with the `text` log, making it a compatible `diff --unified` format and redirecting it to [`diff-so-fancy`](https://github.com/so-fancy/diff-so-fancy), with this little bash script:

<details>
<summary><code>text-to-colorful-diff.sh</code></summary>
<pre>
cat - \
  | sed \
    -e ':a' \
    -e 'N' \
    -e '$!ba' \
    -e 's#) \(\S\+\):\(\S\+\)    \[M\] \(\S\+\)\n\n--- Original\n+++ New\n@@ @@#) Mutant failed: \x1B[1;33m\3\x1B[0m\n\ndiff --git a/\1 b/\1\n--- a/\1\n+++ b/\1\n@@ -\2,1 +\2,1 @@#g' \
  | diff-so-fancy \
  | sed \
    -e ':a' \
    -e 'N' \
    -e '$!ba' \
    -e 's#─\+\x1B\[0m\n##g' \
    -e 's#modified: \S\+\n##g'
</pre>
</details>

### Before

![image](https://user-images.githubusercontent.com/152236/215028845-17c2dd3c-e5c7-402e-bc18-628f5f017af6.png)

### After

![image](https://user-images.githubusercontent.com/152236/215028965-513c4587-513f-4bd8-9cad-9420c15dcc4d.png)

**Comment by maks-rafalko** [comment]
Hello, let me ask a couple of questions to understand how it's going to work

1. Are you talking about text file, generated by `text` logger?
2. Are you talking about stdout output by `text` logger, like this `"logs": {"text": "php://stdout"}`
3. Is it supposed to be done by ANSI sequences?

If using ANSI sequenses, I guess the readability of the file will be reduced in the "raw" editor mode, because of ANSI chars (like `[1;32m Some string [0m`). So do we need a flag/option to enable this ANSI mode?

**Comment by Slamdunk** [comment]
I guess it would be better to just introduce a new `cli` logger that defaults to `STDOUT`, reuses the `text` format internally and adds colors by using the built-in color detection of Symfony Console.

**Comment by Slamdunk** [comment]
> or do you mean we need a characters `diff` (like on red background on your image) to be present in addition to red/green lines?

Exactly this: the current color hightlights would be enough with original formatting, but inlining everything makes them useless again.
I need either the original formatting with the current red/green lines, or mangled formatting with char diff.

**Comment by maks-rafalko** [comment]
I see, thank you.

So the best way is to find such diff'er written in PHP so we don't need to integrate with/require `diff-so-fancy`.

This should be investigated. From the quick look, we can find some packages to try out, for example:

- https://github.com/jfcherng/php-diff

If you @Slamdunk has any suggestion, please advice.

**Comment by Slamdunk** [comment]
I saw just now the `src/Differ/DiffColorizer.php`: it's easy to implement an inline-differ addition to add char highlight.

I'll propose a PR in the next week then :muscle:

**Comment by maks-rafalko** [comment]
that would be very cool. Thank you!

**Comment by maks-rafalko** [comment]
Hello @Slamdunk 

are you interested in adding this feature? If not, could you please show some examples where we can get that "inline-differ" and see how it works? Thanks

**Comment by Slamdunk** [comment]
Sorry Maks, yes I'm still interested but got overwhelmed at job, sorry 😅 

I forgot what I talking about, I had few snippet but lost them 😞

**Comment by maks-rafalko** [comment]
Released: https://github.com/infection/infection/releases/tag/0.29.2

Thank you @Slamdunk
