### ISSUE TITLE
GitHub annotations without Actions

### ISSUE THREAD

**Issue by danepowell** [infection/infection#1828]
**Is your feature request related to a problem? Please describe.**
It looks like the existing GitHub logger (which creates annotations on each mutant) only works with GitHub Actions. It uses some kind of magic string in the Actions output that gets parsed and turned into an annotation.

It would be awesome if this could use the Annotations / Checks API to create annotations from CI platforms other than Actions.

**Describe the solution you'd like**
The GitHub logger creates annotations from anywhere given a GitHub token.

**Describe alternatives you've considered**
Some kind of adapter to parse json logs and send mutations to the annotations API via the GH CLI.

**Comment by maks-rafalko** [comment]
Looks like it's possible using REST API: https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run

feel free to help with implementation

**Comment by danepowell** [comment]
> Looks like it's possible using REST API

When you put it like that, it sounds so simple! 😛 

I looked into this more, and while I think it's _possible_, it might not be pretty. The user would need to set a number of environment variables to configure the GitHub token, owner, repo, and possibly even check run ID in order for Infection to call the API. Even then, I'm not totally sure it's possible because the first paragraph in the API docs says that check runs cannot be updated from forked pull requests, and I work exclusively in forked PRs.

I might look into creating a standalone tool that instead mimics the GitHub Actions annotations magic on other CI platforms. Basically, a tool that looks for that annotations workflow string in log output and uses it to call the GitHub API.
