### ISSUE TITLE
No GPG Signature for Phive.

### ISSUE THREAD

**Issue by cyrilverloop** [infection/infection#1842]
| Question    | Answer
| ------------| ---------------
| Infection version | since 0.26.19
| PHP version | 8.2+
| Platform    | Linux

Installing or updating Infection through Phive shows the following message :
```
[WARNING] infection 0.26.20: No GPG Signature
[WARNING] infection 0.26.19: No GPG Signature
```
No version past 0.26.18 of Infection can be installed.

**Comment by maks-rafalko** [comment]
Please, try again. Thank you.

**Comment by cyrilverloop** [comment]
Works fine now. Thanks !
