### ISSUE TITLE
Attributes on parameters of method signature are not detected as part of method signature

### ISSUE THREAD

**Issue by niconoe-** [infection/infection#1846]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.20
| Test Framework version | PHPUnit 10.1.1
| PHP version | 8.2.5
| Platform    | Ubuntu

Hi all!

I discovered a really annoying bug with PHP Attributes applied on parameters being parsed by Infection when they're part of a method signature, in that Infection does not detect them as part of method signature.
In order to better explain, here is a snippet example:

```php
<?php
declare(strict_types=1);

class FooEntity
{
    public function __construct(
        #[\Doctrine\ORM\Mapping\Column(nullable: false)]
        public string $label,
    ) {
    }
}
```

**The important node here is `false` as it will be mutated to `true`.** When you do a unit test that covers everything here, including that the `nullable` arg is actually set to `false` and nothng else, PHP Infection will **wrongly infer** that the `FalseValue` mutant replacing `false` by `true` is uncovered.

Why that? That's the bug.

Here you can see on my snippet that the `false` in the attribute is declared line 7, but the codeCoverage (no matter if xDebug or PCOV, I've tried both) will declare that:
* line coverage is on range [10] (the `}` of the method declaration)
* method coverage is on range [6;10] (from `public function…` to the closing `}` of the method).

Like I said in this case, the `FalseValue ` mutant will wrongly be declared as **uncovered**, because the associated test coverage will be the _line coverage_, even if this Node is declared on an attribute that applies on a parameter of a method signature.

After long hours of debugging, I discovered that the issue comes from `ReflectionVisitor::isPartOfFunctionSignature`, which, when used with the Node `false`, is returning `false` while it's definitly `true`. It does so because only the 1st level parent is analyzed, but with the PHP Attribute feature, only looking at the 1st level parent of the Node is no longer sufficient. For example, my `ConstFetch` Node ("false") has the parent Node\Arg, which has the parent Node\Attribute, which has the parent Node\AttributeGroup, which finally has the parent Node\Param.

I tried a fix that loop over the parents until the parent is a Node\Param or there's no parent and I apply the same filter than previously, and finally it worked: the test coverage applied to the mutant is now the **method coverage**, so the mutant is in the appropriate range, and is finally considered as covered (and in my case, even killed because I wrote my test in a way to kill such mutant).

Here is the fix:
```php
    private function isPartOfFunctionSignature(Node $node): bool
    {
        if ($this->isFunctionLikeNode($node)) {
            return true;
        }

        $originalNode = $node;
        do {
            $node = ParentConnector::findParent($node);
        } while ($node !== null && ! $node instanceof Node\Param);
        
        if ($node === null) {
            return false;
        }

        return $node instanceof Node\Param || $originalNode instanceof Node\Param;
    }
```

@maks-rafalko if that's OK to you, I'm willing to open a PR for this, but I just want to be sure that looping over the parents again and again this way:
* does not take too much resources
* will not create any false positive
Also, I might lack of technical resources to build a valid unit-test or functional-test additionnaly with my PR to cover this.

Additionnal notes:

_EDIT: Those notes were taken when the playground was using infection 0.26.13. Now it is updated, the playground is having the exact same behavior that what I just described._

I tried this on the playground and I was actually surprised the playground kills the mutant rather than declaring it uncovered. But I realized that the snippet given on the playground is normalized before being analyzed (like forcing the namespaces to `Infected`), so I guess the snippet I gave in the example will be reformatted like:
```php
<?php
declare(strict_types=1);

class FooEntity
{
    public function __construct(#[\Doctrine\ORM\Mapping\Column(nullable: false)] public string $label,) {
    }
}
```
and because of that reformatting, the line coverage range will match the mutated Node location, so we are never going to check the **method coverage** on runtime with this example in the playground. That's why it worked online, but not on my local or CI servers.

**Comment by sanmai** [comment]
Can you make an example using Infection's playground?

https://infection-php.dev/

**Comment by sanmai** [comment]
I wonder if we could skip mutating PHP Attributes for now.

**Comment by niconoe-** [comment]
> Never mind, saw you last observation. Can you at least share it?

Yes of course. I wrote it few days ago to open an issue here but that's how I discovered the mutant is killed as expected in the playground, and I didn't understood why until I came into PHP Infection's source code and I understood how the coverage is bound to the mutation.

https://infection-php.dev/r/5wee

You'll see on the playground that the attribute is no longer on line 10 of the sources but normalized at line 8, which is why, IMO, it passes on playground. If you can ask for no line normalization on the playground, you should be able to reproduce my example.

**Comment by niconoe-** [comment]
> I wonder if we could skip mutating PHP Attributes for now.

Technically, the `ReflectionVisitor` could add a new custom attribute on the PhpParser\Node elements to detect if such node is into a `PhpParser\AttributeGroup` (= current node has any ancestor of type `PhpParser\AttributeGroup`) and then we could generate no mutation for nodes having such custom attribute.

Functionnally, I'm not a fan of such idea as I really do think that some static value given to arguments of attributes should be tested, and tests should be tests to ensure they are actually testing those values as expected. But regarding the impacts PHP Attributes can have on the good behavior of PHP Infection, maybe that's the wiser decision to take.

**Comment by niconoe-** [comment]
I managed to provide a PR with some unit tests: https://github.com/infection/infection/pull/1847

If you have tips or suggestions, I'll be pleased to apply them ASAP.

Thanks a lot!

**Comment by maks-rafalko** [comment]
It's now killed https://infection-php.dev/r/p3e2 :+1:
