### ISSUE TITLE
Disable PHP Attribute mutations globally via config.

### ISSUE THREAD

**Issue by nuryagdym** [infection/infection#1894]
Hi,

I am working with Doctrine Entities and Mongo DB documents.

Doctrine allows us to configure ORM mapping with PHP attributes. 
Example:
```
class UserDevice
{
    public function __construct(
        #[MongoDB\Id]
        private ?string $id,

        #[MongoDB\Field(type: Types::DATE_MUTABLE, nullable: true)]
        private ?UTCDateTime $updatedAt = null,
    ) {
    }
```
In this case infection test is changing `nullable: true` to `nullable: false`.

There is no direct way of handling this mutant, especially with unit tests.

Can we add a config, using which we can disable mutation of PHP attributes at all?

**Comment by maks-rafalko** [comment]
Hello,

while disabling mutating Attributes is not supported out of the box, you can achieve it by [`global-ignoreSourceCodeByRegex`](https://infection.github.io/guide/usage.html) setting in `infection.json5` config:

- https://infection-php.dev/r/zokd - attribute is mutated
- https://infection-php.dev/r/w135 - attribute is NOT mutated

Does it help?

**Comment by nuryagdym** [comment]
Thank you very much @maks-rafalko, it worked!
