### ISSUE TITLE
Incorrect --filter with PHPUnit 10

### ISSUE THREAD

**Issue by dkarlovi** [infection/infection#1899]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.27.8
| Test Framework version | PHPUnit 10.5.1
| PHP version | 8.3.0
| Platform    | Alpine Linux
| Github Repo | -

See discussion in https://github.com/infection/infection/discussions/1898#discussioncomment-7751004

**Comment by dkarlovi** [comment]
The annoying part is this is now versioned, PHPUnit 10+ expects the new behaviour. :|

**Comment by dkarlovi** [comment]
Ah, nevermind, you're already doing that. It seems the bugfix will not be terrible, just need to adjust the behaviour to match what PHPUnit is doing
1. numeric #X
2. else "X"

**Comment by maks-rafalko** [comment]
Thanks for the bug report and details!

Personally, I won't be able to look into this until the weekend. So feel free to help/fix it if you need it quicker.

**Comment by sidz** [comment]
Fixed in https://github.com/infection/infection/pull/1900

**Comment by sanmai** [comment]
@dkarlovi Can you confirm we fixed it?

**Comment by dkarlovi** [comment]
@sanmai I can confirm it was fixed! :champagne:
