### ISSUE TITLE
in_array strict parameter and the bool mutator

### ISSUE THREAD

**Issue by luispabon** [infection/infection#194]
| Question    | Answer
| ------------| ---------------
| Infection version | x.y.z (`infection.phar --version`)
master
| Test Framework version | PHPUnit/PhpSpec x.y.z
phpunit 7.0.1
| PHP version | x.y.z (`php -v`)
7.2.2
| Platform    | e.g. Ubuntu/Windows/MacOS
Ubuntu

```diff
7) /home/luis/somefile:64    [M] TrueValue
exec /usr/bin/php7.2 -c /tmp/infectionHpWXWA /home/luis/someproject/vendor/phpunit/phpunit/phpunit --configuration /tmp/infection/phpunitConfiguration.f540ee3497f35fb49cc1e498028c884e.infection.xml --stop-on-failure 
--- Original
+++ New
@@ @@
      */
     public function hasType(string $type) : bool
     {
-        return \in_array($type, $this->dataTypes, true);
+        return \in_array($type, $this->dataTypes, false);
     }
```

This is a bit of a difficult one. I'm very scrupulous with types in my code and these mutators will always produce a false positive. I can see this being useful in some situations though. Is there any way I can selectively disable mutators based on the method being called in code?

**Comment by theofidry** [comment]
We're thinking of implementing profiles cf. https://github.com/infection/infection/issues/89 which would be a fit for what you want to do

**Comment by luispabon** [comment]
Understood, I'm following that issue as well :+1:

**Comment by borNfreee** [comment]
Probably, as a temporary workaround (while we don't have profiles) we can modify True/False mutators to skip this function as I encountered this issue many times as well. Even @BackEndTea removed the third element (strict) from recently from infection source code when tried to increase MSI

WDYT?

**Comment by luispabon** [comment]
I am in no hurry tbh, I can definitely see the utility of the mutator being used in `in_array` on older codebases.

**Comment by borNfreee** [comment]
could you please explain what do you mean? How older codebases differ from the new one in context of using the third argument?

**Comment by BackEndTea** [comment]
>Even @BackEndTea removed the third parameter (strict) recently from infection source code when tried to increase MSI

I should note that for the cases where i removes it, there was no way a strict search improved anything

**Comment by luispabon** [comment]
I've taken over older codebases (eg early php5) where people hadn't been using strict `in_array` and that's caused problems with spurious checks where strings were being casted to numbers. Better seen with an example:

```
~ php -a
Interactive mode enabled

php > $foo = [10, "5 february bro"];
php > var_dump(in_array(5, $foo));
php shell code:1:
bool(true)
php > var_dump(in_array(5, $foo, true));
php shell code:1:
bool(false)
```

**Comment by borNfreee** [comment]
That's clear, I meant both codebases (new and old) can have the code with `strict` third where it's impossible to kill the mutant.

I can suggest to remove third parameter to avoid escaped mutant in your example  since it does not bring much value in this particular case (you always know that `$this->dataTypes` are strings, and parameters is always a string).

Later, you will be able to configure it :)

Can we close this issue?

**Comment by luispabon** [comment]
Yes, of course. I'll keep an eye on #89 

Thank you :+1:
