### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by jspeedz** [infection/infection#1955]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.28.1
| Test Framework version | PHPUnit 9.6.18
| PHP version | 8.2.16
| Platform    | MacOS 14.4.1
| Github Repo | -

I ran the GPG signature validation commands found in the documentation: https://infection.github.io/guide/installation.html.

The key has expired since 17 August 2023 at 21:46.

<img width="454" alt="image" src="https://github.com/infection/infection/assets/6095226/bde69286-4576-4a66-8ff7-8199f204b393">

<details>
 <summary>commands ran + output</summary>

 ```
 % wget https://github.com/infection/infection/releases/download/0.28.1/infection.phar

 % wget https://github.com/infection/infection/releases/download/0.28.1/infection.phar.asc

 % gpg --recv-keys C6D76C329EBADE2FB9C458CFC5095986493B4AA0
gpg: key C5095986493B4AA0: public key "Infection PHP <maks.rafalko@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1

% gpg --with-fingerprint --verify infection.phar.asc infection.phar
gpg: Signature made ma 25 mrt 10:55:42 2024 CET
gpg: Good signature from "Infection PHP <maks.rafalko@gmail.com>" [expired]
gpg: Note: This key has expired!
 ```
</details>

**Comment by sanmai** [comment]
```
$ gpg -k C6D76C329EBADE2FB9C458CFC5095986493B4AA0
pub   rsa2048 2018-08-05 [SC] [expired: 2023-08-17]
      C6D76C329EBADE2FB9C458CFC5095986493B4AA0
uid           [ expired] Infection PHP <maks.rafalko@gmail.com>
```

**Comment by maks-rafalko** [comment]
```
gpg -k C6D76C329EBADE2FB9C458CFC5095986493B4AA0                                             
pub   rsa2048 2018-08-05 [SC] [expires: 2029-04-15]
      C6D76C329EBADE2FB9C458CFC5095986493B4AA0
```

should be good now, thank you.

**Comment by jspeedz** [comment]
> ```
> gpg -k C6D76C329EBADE2FB9C458CFC5095986493B4AA0                                             
> pub   rsa2048 2018-08-05 [SC] [expires: 2029-04-15]
>       C6D76C329EBADE2FB9C458CFC5095986493B4AA0
> ```
> 
> should be good now, thank you.

Thanks a lot for the fast fix, cheers!
