### ISSUE TITLE
Windows can't open this file when composer.phar is found

### ISSUE THREAD

**Issue by tomzx** [infection/infection#196]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.7.1
| Test Framework version | PHPUnit
| PHP version | 7.2.1
| Platform    | Windows
| Github Repo | -

In `\Infection\Finder\TestFrameworkExecutableFinder::addVendorFolderToPath`, if `$this->findComposer()` returns the path to a `phar file`, Windows shows a window asking the user to select which program to use to open the file.

The expected behavior is that it should execute the `phar` file by calling the php binary since Windows ignores the shebang within the `phar` file.

It looks like logic from `\Infection\Finder\TestFrameworkExecutableFinder::makeExecutable` could be reused in order to prefix the `phar` file with the appropriate php binary.

![rundll32_2018-02-24_21-43-27](https://user-images.githubusercontent.com/188960/36637529-d026b36a-19ab-11e8-93c0-b686fa145534.png)

**Comment by sidz** [comment]
Good catch 👍 will be covered by https://github.com/infection/infection/pull/185

**Comment by sidz** [comment]
Fix has been merged.
@tomzx 🚢
