### ISSUE TITLE
Support for short circuit evaluation with assignment statements

### ISSUE THREAD

**Issue by kristos80** [infection/infection#1975]
**Is your feature request related to a problem? Please describe.**

Some people, including me, prefer writing code like this:
```php
$product !== $inlineProduct && !array_key_exists($hash, $pairs) && ($pairs[$hash] = $pair);
```
Instead of this:
```php
if ($product !== $inlineProduct && !array_key_exists($hash, $pairs)) {
    $pairs[$hash] = $pair;
}
```
`Infection`, in such cases, creates a mutant that tries to negate the whole condition:
```php
!($product !== $inlineProduct && !array_key_exists($hash, $pairs) && ($pairs[$hash] = $pair));
```

Which, of course, won't stop the execution of `&& ($pairs[$hash] = $pair)`, resulting in this specific mutation not being killed.

**Describe the solution you'd like**

I’m not entirely sure how something like this can be achieved due to the complexity arising from all the possible ways an assignment can occur within a short-circuit evaluation. This is more of a question about whether you think something like this can be achieved or is worth exploring further.

**Describe alternatives you've considered**

For now, I use the `if` syntax and avoid short-circuit evaluation assignments.

**Additional context**

Nothing.

Thank you nevertheless for this excellent library! :)

**Comment by maks-rafalko** [comment]
From what I understood, you want to say Infection to not mutate such lines of code. Currently, you can achieve it by configuring ignore regex, see:

- mutates https://infection-php.dev/r/wzlg
- doesn't mutate https://infection-php.dev/r/75z6

I don't think we should support it in the core as this is a very specific usage

**Comment by kristos80** [comment]
Hi @maks-rafalko thanks for your response.

Sorry for not providing a full example, my bad!

Check this out in order to see the difference in code syntax that achieves, though, exactly the same result:

* https://infection-php.dev/r/1lyp (Escaping `LogicalAndNegation`)
* https://infection-php.dev/r/yzg0 (Killing all)

In the first example, the assignment happens as the last part of the condition `&& ($extractedPairs[$hash] = $pair);`, while in the second, in the body of the `if` condition.

The mutation though in the first case should have be done as such in order to be able to get killed:

```PHP               
// Negate the part that is used as the actual condition 
!(($number !== $iNumber && !array_key_exists($hash, $extractedPairs)) 
// Leave the assignment part intact -- It applies that `infection` understands the semantics involved here
&& $extractedPairs[$hash] = $pair);
```

This is not some strange taste I have for non-readable code, but it comes in order to reduce cyclomatic complexity in cases where an extra `if` will dramatically increase it, due to deep nested loops or conditions.

Again, I am not saying that this is a must-have feature, but rather an attempt to start a discussion on the topic. 

PS

I prefer to refactor my code in order to be able to get tested against mutations, rather than ignore specific parts of it.

**Comment by maks-rafalko** [comment]
Ah ok, now it's clear what is needed. I think it's doable and looks like not a complex task (I hope!).

Look at this AST - https://infection-php.dev/ast/qxk - generated for 

```php
$number !== $iNumber && !array_key_exists($hash, $extractedPairs) && ($extractedPairs[$hash] = $pair);
```

the `right` expression is `Assing`, we can programmatically find it and if it's the latest on the right - then play with everything on the left, not touching this `right` side.

Feel free to trying implementing it and opening a PR :) 

Even if other maintainers decide to not include it in the core, you will be able to create your [custom mutator](https://infection.github.io/guide/custom-mutators.html) and disable built-in `LogicalAndNegation`

You can start here:

https://github.com/infection/infection/blob/b7e29dd415d95cc7e73dcefcdf9b11aafb386194/src/Mutator/Boolean/LogicalAndNegation.php#L82-L99

**Comment by kristos80** [comment]
In general, as a rule of thumb, the assignment parts of a condition should be ignored, but the remaining parts should be mutated.

For instance this:
```PHP
$a > $b && ($temp = $a) || $temp = $b;
```
Which is, more or less, the equivalent of this:
```PHP
if($a > $b){
   $temp = $b;
}else{
   $temp = $a;
}
```
Should be mutated as such:

Mutation 1.
```diff
- ($a > $b) 
+ ($a >= $b) 
&& ($temp = $a) || $temp = $b;
```
Mutation 2.
```diff
- ($a > $b) 
+ ($a <= $b) 
&& ($temp = $a) || $temp = $b;
```
And this:
```PHP
($temp = $a) && ($a < $b && $b >= 1) && ($temp = $b);
```
Which is equivalent to this:
```PHP
$temp = $a;
if($a < $b && $b >= 1) {
    $temp = $b;
}
```
Should be mutated in the same way ```$a < $b && $b >= 1``` would be mutated, while leaving assignments intact.

But then, there can be 'monsters' like this one:
```PHP
($temp = $a) && ($a < $b || (($temp = $b))) && ($temp < $c) && ($temp = $c);
```
Which, roughly, resembles this:
```PHP
$temp = $a;
if($a < $b){
    $temp = $b;
}

if($temp < $c){
    $temp= $c;
}

return $temp;
```
Can be way too complex to be handled in a global way. 

I guess custom mutators per case (or avoid this syntax at all costs) is the only way to go, so feel free to close it!

**Comment by maks-rafalko** [comment]
Ok, yeah I agree. If someone needs this very specific behavior, it can be implemented as a custom mutator.

Thank you.
