### ISSUE TITLE
Relative path to PHPUnit bootstrap file being incorrectly built.

### ISSUE THREAD

**Issue by Rockstar04** [infection/infection#199]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.8.0
| Test Framework version | PHPUnit 7.0.2
| PHP version | 7.2.1
| Platform    | e.g. Ubuntu on Windows

Relative path to PHPUnit bootstrap file being incorrectly built with version 0.8.0. Version 0.7.1 works exactly as expected. PR #165 seems like the likely cause, but with no clear solution.

<details>
 <summary>phpunit.xml</summary>
 
Located in `build` folder relative to project root

 ```xml
 <?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="../vendor/phpunit/phpunit/phpunit.xsd"
     beStrictAboutTestsThatDoNotTestAnything="true"
     checkForUnintentionallyCoveredCode="true"
     bootstrap="../vendor/autoload.php"
     colors="true">

  <testsuites>
    --SNIP--
  </testsuites>

  <filter>
    <whitelist>
      <directory suffix=".php">../src</directory>
      <exclude>
        <directory suffix="ConfigProvider.php">../src</directory>
      </exclude>
    </whitelist>
  </filter>

  <logging>
    <log type="coverage-html" target="coverage"/>
    <log type="coverage-xml" target="coverage/xml"/>
    <log type="coverage-clover" target="logs/clover.xml"/>
    <log type="coverage-crap4j" target="logs/crap4j.xml"/>
    <log type="junit" target="logs/junit.xml" logIncompleteSkipped="false"/>
  </logging>

</phpunit>

 ```
</details>

<details>
 <summary>Output with issue</summary>
 
![capture](https://user-images.githubusercontent.com/641721/36808567-13693ce2-1c8b-11e8-902f-1dea4ea5c268.PNG)

</details>

**Comment by borNfreee** [comment]
Thank for reporting this bug. Should be fixed in https://github.com/infection/infection/pull/200

**Comment by Rockstar04** [comment]
Thanks for the quick response and proposed resolution.

**Comment by borNfreee** [comment]
Tagged a [0.8.1](https://github.com/infection/infection/releases/tag/0.8.1) with a fix.
PHARs will be uploaded later.

Thank you!
