### ISSUE TITLE
Dependency "thecodingmachine/safe" outdated generate Deprecated logs

### ISSUE THREAD

**Issue by naspy971** [infection/infection#2015]
I'm using php 8.4 and I just installed Infection version ^0.29.8 and I have this type of logs (multiple lines) :

`Deprecated: Safe\mktime(): Implicitly marking parameter $day as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/app/vendor/thecodingmachine/safe/deprecated/datetime.php on line 78`

Seems like Infection needs to upgrade its `thecodingmachine/safe` dependency.

Thanks.

**Comment by darthf1** [comment]
There is no new stable version of `thecodingmachine/safe` to update to...

Also, yesterday, in https://github.com/infection/infection/pull/2012 the dependency was updated to `dev-master as 2.5.0`, but now my composer gives errors; is there a workaround for this whilst keeping my `minimum-stability`?

```
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "7.2.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires infection/infection 0.29.9 -> satisfiable by infection/infection[0.29.9].
    - infection/infection 0.29.9 requires thecodingmachine/safe dev-master as 2.5.0 -> found thecodingmachine/safe[dev-master] but it does not match your minimum-stability.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by maks-rafalko** [comment]
> I'm using php 8.4 and I just installed Infection version ^0.29.8

Please use yesterday's release 0.29.9

> but now my composer gives errors; is there a workaround for this whilst keeping my minimum-stability?

Use Infection PHAR distribution? Without deep investigating, I'm not aware of any other ways of how we can get the latest changes of `thecodingmachine/safe` without pointing to `dev-master`.

PHAR distribution should be a good workaround for you for now.

**Comment by maks-rafalko** [comment]
please use recommendation from https://github.com/infection/infection/issues/2015#issuecomment-2527373043

If you anyone has other ideas, feel free to suggest.

**Comment by maks-rafalko** [comment]
> I'm not sure I get you ? I actually tried to install the specific version you mentionned

to avoid "minimum-stability" issue with 0.29.9 you can use PHAR distribution instead of a composer package, see https://infection.github.io/guide/installation.html#Phar (but change the version to 0.29.9)

another idea to try on your side is to use

```
"minimum-stability": "dev",
"prefer-stable": true
```

in `composer.json` unless we have a proper solution.

**Comment by sanmai** [comment]
I suppose we can try to drop `thecodingmachine/safe` temporarily, and restore it (revert the PR that removed it) later as new version becomes available.

**Comment by sanmai** [comment]
@naspy971 Could you try if this works as a workaround?
```
composer require --dev shish/safe
```

**Comment by maks-rafalko** [comment]
@sanmai could you please explain how `shish/safe` should help? 

The issue @naspy971 has is because of **Infection** uses `dev-master` of `thecodingmachine/safe`

**Comment by sanmai** [comment]
`shish/safe` is a replacement package for the `thecodingmachine/safe`  which does not require changes to `minimum-stability` or other Composer flags.

**Comment by maks-rafalko** [comment]
out of curiosity, where is the information about `shish/safe`? I think I miss something and only see the [this comment](https://github.com/thecodingmachine/safe/issues/499#issuecomment-2527608763)

**Comment by darthf1** [comment]
> out of curiosity, where is the information about `shish/safe`? I think I miss something and only see [this comment](https://github.com/thecodingmachine/safe/issues/499#issuecomment-2527608763)

https://github.com/thecodingmachine/safe/issues/452 :)

**Comment by maks-rafalko** [comment]
Ok, now I see that it has "replaces" section here https://packagist.org/packages/shish/safe. Thanks for the explanation, it wasn't obvious for me

**Comment by maks-rafalko** [comment]
Please try https://github.com/infection/infection/releases/tag/0.29.10 and if possible report back if it fixes the issues. Feel free to reopen if not.

**Comment by Syndesi** [comment]
FYI safe got a new major release which fixes the deprecation logs: https://github.com/thecodingmachine/safe/issues/499
