### ISSUE TITLE
Ability to disable infection categories in config file

### ISSUE THREAD

**Issue by simplesales** [infection/infection#203]
First and foremost, thanks SO MUCH for the package - this is wonderful, and the hard work you guys have put in is amazing.

This might exist in the project already, and my apologies if I didn't see it in the docs, but is there a simple way to **exclude** certain mutators or mutator groups?  I saw the include option in the command line ,but in my case I'm interested in (for example) running everything except the Function Signature mutators, and I'm not seeing how to easily disable those inspections.

Again, thanks a TON for all the hard work!

**Comment by borNfreee** [comment]
Hello @simplesales, thank you for these kind words.

We are working on this feature in https://github.com/infection/infection/pull/177 - it will allow disable mutators by file, by namespace, by method, or even configure your Profile.

However, currently it's impossible to exclude signature mutators.

The only one workaround I know is to use [--mutators](https://infection.github.io/guide/command-line-options.html#mutators) option and list all mutators except ones you want to exclude: `infection --mutators=plus,decrement[,...,]`

**Comment by borNfreee** [comment]
Closing for now as we don't have a solution yet.

Feel free to reopen and keep an eye on #177 :)

**Comment by BackEndTea** [comment]
A combination of #177 and #89 will allow this pretty easily.

You could have the `@default` configuration, and then add `@visibility: false` option.
