### ISSUE TITLE
Fatal error when wrong test framework has been chosen during first run

### ISSUE THREAD

**Issue by lchrusciel** [infection/infection#204]
| Question    | Answer
| ------------| ---------------
| Infection version | dev-master
| Test Framework version | phpspec 4.3.0
| PHP version | 7.2
| Platform    | MacOS
| Github Repo | -

~According to your [documentation](https://infection.github.io/guide/command-line-options.html#test-framework), you are supporting two testing libraries PHPSpec and PHPUnit. As my project uses only PHPSpec, I have tried to run infection with `--test-framework=PHPSpec` option. Unfortunately, it resulted in a nasty fatal error:~
```bash../infection/bin/infection --test-framework=PHPSpec
You are running Infection with xdebug enabled.
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Infection\Config\InfectionConfig::__construct() must be an instance of stdClass, null given, called in infection/src/Console/Application.php on line 195 and defined in infection/src/Config/InfectionConfig.php:165
Stack trace:
#0 infection/src/Console/Application.php(195): Infection\Config\InfectionConfig->__construct(NULL, Object(Symfony\Component\Filesystem\Filesystem), '/Users/...')
#1 infection/vendor/pimple/pimple/src/Pimple/Container.php(118): Infection\Console\Application->Infection\Console\{closure}(Object(Pimple\Container))
#2 infection/app/container.php(61): Pimple\Container->offsetGet('infection.confi...')
#3 infection/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}(Object(Pimple\Container))
#4 infection in infection/src/Config/InfectionConfig.php on line 165

Fatal error: Uncaught TypeError: Argument 1 passed to Infection\Config\InfectionConfig::__construct() must be an instance of stdClass, null given, called in infection/src/Console/Application.php on line 195 and defined in infection/src/Config/InfectionConfig.php:165
Stack trace:
#0 infection/src/Console/Application.php(195): Infection\Config\InfectionConfig->__construct(NULL, Object(Symfony\Component\Filesystem\Filesystem), '/Users/...')
#1 infection/vendor/pimple/pimple/src/Pimple/Container.php(118): Infection\Console\Application->Infection\Console\{closure}(Object(Pimple\Container))
#2 infection/app/container.php(61): Pimple\Container->offsetGet('infection.confi...')
#3 infection/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}(Object(Pimple\Container))
#4 infection in infection/src/Config/InfectionConfig.php on line 165
```

~After deeper investigation, I have figurated out, that I should just use a lowercased name of `phpspec` (thanks to your [e2e tests](https://github.com/infection/infection/blob/a7a2ed8feae3535c12787b1332f939bbe252dedd/tests/Fixtures/e2e/Test_Frameworks/run_tests.bash#L20))~

~Once a cache is generated problem disappears and a nice fallback message is displayed which of course helps a lot:
![zrzut ekranu 2018-03-04 o 10 49 57](https://user-images.githubusercontent.com/6213903/36944316-d03f6894-1f99-11e8-941b-09b3337f51d0.png)~

~I am aware, that it is not a project for beginners and solution is not that hard, but I think it will be useful to mention about proper option key's for CLI tool and maybe do something with this fatal error :)~

Anyway, thanks for your work :)

**Comment by lchrusciel** [comment]
False alarm, a problem exists only if infection.json contains invalid JSON file.

**Comment by borNfreee** [comment]
> I am aware, that it is not a project for beginners and solution is not that hard, but I think it will be useful to mention about proper option key's for CLI tool and maybe do something with this fatal error :)

you are absolutely right. Thanks for your report. I've created an issue to resolve this. https://github.com/infection/infection/issues/205

Feel free to contribute BTW ;)

**Comment by lchrusciel** [comment]
I will try to help if only I will find some free time :)

**Comment by localheinz** [comment]
How about providing a JSON Schema and then using [`justinrainbow/json-schema`](https://github.com/justinrainbow/json-schema) to validate it, after ensuring we actually have valid JSON?

**Comment by borNfreee** [comment]
there are cool packages to validate json in packagist without doubts. 

The main concern (at least for me) here is to not add anew dependecy. may be just check json last error would be enough at this point?

**Comment by borNfreee** [comment]
for reference: https://github.com/infection/infection/issues/206 here we probably need json validation, so make sense to add a new dependency to not reinvent the wheel
