### ISSUE TITLE
Allow settings for Mutators

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#206]
With the proposal of #79, implemented like https://github.com/infection/infection/issues/89#issuecomment-365725972, we could extend the config file yet again to pass 'settings' to the Mutators.

Given the following config file:
```js
{
    "timeout": 25,
    "mutators": {
        "@library": true,
        "Minus": true, // included
        "Plus": false, // completely ignored
        "TrueValue": { // ignored for particular cases
            "ignore": [
                "Ignore\\For\\Particular\\Class",
                "Ignore\\For\\Another\\Class::method",
                "Ignore\\For\\**\\*\\Glob\\Pattern\\Or\\Namespace"
            ],
            "settings": {
                "in_array": false,
            }
        },
        "DecrementInteger": { // ignored for particular cases
            "settings": {
                "symfonty_event_subscriber": false,
            }
        }
    }
}
```

The `TrueValue` mutator could have a setting that it will not mutate for the in_array function. The `DecrementInteger` could have a setting that it does not mutate within the `getSubscribedEvents()` function, as a lot of time a +1 or -1 on those doens't change anything.

All settings should have a reasonable default value, and the config file is used to overwrite those.

At this point we should also look into some kind of json validation, so if invalid keys are passed, that are still valid json it should give some kind of notification to the user, and either quit entirely or continue if possible.

**Comment by borNfreee** [comment]
Good idea!

> At this point we should also look into some kind of json validation, so if invalid keys are passed, that are still valid json it should give some kind of notification to the user, and either quit entirely or continue if possible.

Yeah, with such a complex config file we will definitely need some kind of validation, as @localheinz already [mentioned](https://github.com/infection/infection/issues/204#issuecomment-370335823). 

Probably, if we are going to implement it, we can already add a new dependency (json validation) for https://github.com/infection/infection/issues/205 as both features will benefit from it.
