### ISSUE TITLE
Not easy to get package version

### ISSUE THREAD

**Issue by lchrusciel** [infection/infection#208]
| Question    | Answer
| ------------| ---------------
| Infection version | dev-master, local git distribution
| Test Framework version | doesn't matter
| PHP version | 7.2
| Platform    | MacOS
| Github Repo | -

Right now, checking a version of infection tells me, that I have `@package.version@` version of an app.
![zrzut ekranu 2018-03-05 o 20 40 54](https://user-images.githubusercontent.com/6213903/36995982-eb83ad78-20b5-11e8-8f2f-6ab7d45cb3a5.png)

**Comment by BackEndTea** [comment]
@sidz @theofidry I think you guys created the part that deals with package version. Do you know what is  going on?

This isn't just for dev-master, it doesn't work on 0.8.1 either.

**Comment by theofidry** [comment]
As far as I'm aware the version is simply not replaced when running infection from the package as opposed to the PHAR. The string `@package_version@` is replaced when building the PHAR.

**Comment by BackEndTea** [comment]
@borNfreee how about changing `const VERSION = '@package_version@';` with `const VERSION = '0.9.0-dev';` and then removing the `-dev` for the release.

This does mean it has to be manually changed for every release.

**Comment by theofidry** [comment]
I'm not really for managing it manually personally. That said we could replace the `@package_version` placeholder by something else when outside the PHAR. You can do something like in [Box](https://github.com/humbug/box/blob/master/src/Console/Application.php#L48-L60) or another way is just not using a placeholder at all like done in [PHP-Scoper](https://github.com/humbug/php-scoper/blob/master/src/functions.php#L49)

**Comment by sidz** [comment]
Do we really need to take care about it? Composer doesn't do it. 

![image](https://user-images.githubusercontent.com/1302230/37273409-d2c781bc-25ea-11e8-8d98-15bfefe4b23f.png)

**Comment by theofidry** [comment]
@sidz is 99% if not more installed as a PHAR, Infection is way more used as a library
