### ISSUE TITLE
Add a .editorconfig

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#212]
To reduce code style comments on PR's we should add an `.editorconfig`, which describes the indenting styles/ new line rules for certain file types.

To implement this we need to know exactly what 'rules' we want to have for the different file types like php and json

http://editorconfig.org/

**Comment by borNfreee** [comment]
I suggest the following:

```
root = true

[*]
charset=utf-8
end_of_line=lf
trim_trailing_whitespace=true
insert_final_newline=true
indent_style=space
indent_size=4
```
