### ISSUE TITLE
Code style makes lines uncovered

### ISSUE THREAD

**Issue by martijngastkemper** [infection/infection#214]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.8.1
| Test Framework version | PHPUnit 7.0.2
| PHP version | 7.1.14 xdebug 2.6.0
| Platform    | MacOS
| Github Repo | [https://github.com/martijngastkemper/xdebug-infection-coverage-bug](https://github.com/martijngastkemper/xdebug-infection-coverage-bug)

I created a repo with [a class](https://github.com/martijngastkemper/xdebug-infection-coverage-bug/blob/master/src/MyClass.php) with two identical functions, but different code style. The function with a multi line array gets changed by mutant, but Infection can't cover it.
<img width="461" alt="screen shot 2018-03-09 at 19 20 05" src="https://user-images.githubusercontent.com/250662/37222880-f28068a2-23ce-11e8-805a-b8168f04a446.png">

It looks like a problem with Xdebug because only the first line in the array is covered:
<img width="221" alt="screen shot 2018-03-09 at 18 54 59" src="https://user-images.githubusercontent.com/250662/37221853-7c9659ec-23cb-11e8-803a-1480101a061d.png">

I searched for bug reports, but couldn't find one. Is someone familiar with this problem?

**Comment by BackEndTea** [comment]
Thank you for raising this issue, as far as i know we were not yet aware of this.

Also much thanks for creating a repo that contains the issue.

You are correct that xdebug doesnt see this as covered.

**Comment by martijngastkemper** [comment]
Wouldn't that make this problem a Xdebug bug? Or do you think it's possible to solve this problem in Infection?

**Comment by borNfreee** [comment]
We had a similar issue before: https://github.com/infection/infection/issues/34

Unfortunately, this is how PHP works itself. We can't do anything here. This is an explanation from Derick, the author of Xdebug:

```
$array = array(
    'int' => 1,
    'bool' => true,
);

This is an improvement in PHP 7.1 - it has the array initialisation optimised from using 3 opcodes in PHP 5.6:

line #* E I O op fetch ext return operands
-------------------------------------------------------------------------------------
   5 5 INIT_ARRAY 0000002:0000001 1, 'int'
   6 6 ADD_ARRAY_ELEMENT 0000002:0000001 <bool>, 'bool'
   7 7 ASSIGN !0, 0000002:0000001

To just one in PHP 7.1:

line #* E I O op fetch ext return operands
-------------------------------------------------------------------------------------
   5 6 ASSIGN !0, <array>

Xdebug correctly shows there is no executable code at all on lines 6 and 7 with PHP 7.1 (use the XDEBUG_CC_UNUSED and XDEBUG_CC_DEAD_CODE options to xdebug_start_code_coverage), which means there is nothing to fix here.
```

Read more https://bugs.xdebug.org/view.php?id=1479


You can check it opening VLD opcodes tab https://3v4l.org/chYT6/vld#output

---------

@martijngastkemper I suggest refactor the code and to not use magic numbers, replacing them with constants :)
