### ISSUE TITLE
0.8.1 missing .phar

### ISSUE THREAD

**Issue by tomtomau** [infection/infection#216]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.7.1 (`infection.phar --version`)
| Test Framework version | n/a
| PHP version | 7.2.2 (`php -v`)
| Platform    | e.g. Ubuntu

As a user, when I run infection.phar self-update I get a 404 because 0.8.1 is missing the .phar in the releases section. My expectation is that I can always self-update to _some_ stable version, or I am told I am up to date.

Thanks for this great package!

**Comment by borNfreee** [comment]
Oops, totally forgot to upload files.

Thank you for creating this issue. Fixed.

> Thanks for this great package!

Thanks for using it!
