### ISSUE TITLE
Improve CI usage: hangs indefinitely

### ISSUE THREAD

**Issue by sanmai** [infection/infection#223]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.8.1 from Packagist
| Test Framework version | PHPUnit 6.5.6
| PHP version | 7.0.27-1
| Platform    | Travis CI
| Github Repo | -

Great work, folks!

Right now when run unattended and without a config file the program just hangs indefinitely. This could easily happen in CI situations. [For example, see this build.](https://travis-ci.org/sanmai/pipeline/jobs/353749452#L820)

Possible solutions:

1. The program could fail with an error if it detects a non-interactive terminal.
2. The program could continue with guessed defaults.

I would prefer to see the second option, but there could be other considerations.

**Comment by BackEndTea** [comment]
Would a `--no-interaction` flag solve this issue?

**Comment by sanmai** [comment]
From what I understand this could just as it is, without any flags. 

E.g. most cases of CI can be detected by `CI=true`.

Other than that, there's [posix_isatty](http://php.net/manual/en/function.posix-isatty.php) which should suffice in all other cases.
```php
if (!posix_isatty(STDOUT)) {
    fwrite(STDOUT, "Invalid TTY\n");
    exit(1);
}
```

**Comment by theofidry** [comment]
Not all CI exposes this environment. A common convention with the Symfony Console is to use the `--no-interaction` flag. I don't know why `posix_isatty` is not used: it may just be an oversight or there is a genuine behind it

**Comment by BackEndTea** [comment]
`--no-interaction` gives more control the the end user. Which means it can also be used in other environments.

**Comment by sanmai** [comment]
If there is a convention, so be it.

I'd think it would be best if there is `CI=true`, then it is like `--no-interaction` was set on the command line.

**Comment by sanmai** [comment]
```
$ php vendor/bin/infection --no-interaction
You are running Infection with xdebug enabled.
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____ 
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/
 

                                             
  Welcome to the Infection config generator  
                                             
````

I just found that Infection config generator still launches even if  `--no-interaction` specified. This means there's more work to be done.

**Comment by sanmai** [comment]
And actually `posix_isatty` gets used.
