### ISSUE TITLE
infection --version does not return its version

### ISSUE THREAD

**Issue by walterdolce** [infection/infection#245]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.8.1 (as defined within the `composer.json` file)
| Test Framework version | N/A
| PHP version | 7.1.4
| Platform    | macOS High Sierra 10.13.3
| Github Repo | ?

Running `bin/infection --version` does not actually return its version, but returns the following:
```
$ bin/infection --version
You are running Infection with xdebug enabled.
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Infection - PHP Mutation Testing Framework @package_version@
```

**Comment by walterdolce** [comment]
I should add that infection in the project where this is happening is defined as a development dependency within the `composer.json` file:
```
# composer.json

{
   ...
   "require-dev": {
      ...
      "infection/infection": "0.8.1"
   },
   ...
}
```

**Comment by sanmai** [comment]
Seems related to #208

**Comment by theofidry** [comment]
Yep, let's close as a duplicate :)
