### ISSUE TITLE
Mutant processes are not memory-bound

### ISSUE THREAD

**Issue by sanmai** [infection/infection#247]
| Question    | Answer
| ------------| ---------------
| Infection version | master
| Test Framework version | PHPUnit

Currently mutant processes are only limited by the time they could take before timing out. They should also be limited by the amount of memory they consume.

While dogfooding Infection with experimental mutators it isn't uncommon to see some processes eating a sizeable part of the RAM: 
```
  PID USER       PR  NI    VIRT    RES    SHR S  %CPU %MEM   SWAP     TIME+ COMMAND                                                                                                      
29508 sanmai     20   0 7539,7m 7,049g  22,1m R 100,0 22,5   0,0m   0:09.14 php7.0                                                                                                       
29712 sanmai     20   0  350,2m  33,3m  21,9m R  33,3  0,1   0,0m   0:00.06 php7.0                                                                                                       
29713 sanmai     20   0  348,0m  33,4m  22,0m R  27,8  0,1   0,0m   0:00.05 php7.0                                 
```
This could lead to all kind of nasty issues, including having OOM Killer come for unconcerned processes, especially those having unsaved data. I would really appreciate if it wouldn't kill my Chrome once in a while.

## Steps to reproduce

Be forewarned that this experiment can be very unpleasant.

1. Checkout the current master revision, which is a5e034f.

        checkout a5e034f

2. Adjust timeout to a larger value. This is needed because the bugs Infection triggers upon itself isn't very quick in terms of memory consumed.
    ```diff
    --- a/infection.json.dist
    +++ b/infection.json.dist
    @@ -1,5 +1,5 @@
     {
    -    "timeout": 25,
   +    "timeout": 2500,
    ```
3. Get some tea or coffee, launch Infection with as many threads as you like. A single thread would work too, though it'll take more time.

        bin/infection -j4

4. Try to get some other work done. Depending on the amount of RAM you have, at least on Linux, after just one minute you would notice your IDE suddenly closing, music stops playing, and so.

## Workarounds

One easy way to enforce memory limits under Linux is to use `ulimit`:

    ulimit -Sv 500000

Or, if one has daemontools installed, one can use [softlimit](http://cr.yp.to/daemontools/softlimit.html) for a one-off job:

    softlimit -m 500000000 bin/infection ...

But a user may not care enough, and I'm not sure if there's ulimit under Windows.

Therefore, this issue should be taken care of by the Infection itself by any means PHP give us.

**Comment by theofidry** [comment]
Shouldn't the limit be set by your php config?

**Comment by sanmai** [comment]
For PHP CLI it is usually unlimited:
```bash
$ grep -R memory_limit /etc/php/*/cli/php.ini
memory_limit = -1
```

**Comment by theofidry** [comment]
AFAIK most installs don't put `memory_limit = -1` though and I think it's better if you put a limit like 2GB or 5GB rather than unlimited. If you really want unlimited for a peculiar case you can always set it with `php -d memory_limit=-1`.

So IMO here it would be safer if you were to adjust your settings rather than Infection trying to do some sketchy guess work as to which limit to put

**Comment by sanmai** [comment]
Debian and Ubuntu do put `memory_limit = -1`. Doesn't that qualify for the most these days?
```
$ grep memory_limit /usr/lib/php/7.0/*
/usr/lib/php/7.0/php.ini-development:memory_limit = 128M
/usr/lib/php/7.0/php.ini-production:memory_limit = 128M
/usr/lib/php/7.0/php.ini-production.cli:memory_limit = -1
```

**Comment by theofidry** [comment]
And I thought they fixed it already looks like it’s not the case :(

**Comment by sanmai** [comment]
And they never will. It's a CLI after all. You don't expect any limits for command line programs, right?

I tried to see what are limits there on Travis, but for some reason Travis decided to ignore #249. Or is it me?

**Comment by theofidry** [comment]
>It's a CLI after all

I don't see why CLI is an exception. I don't expect a PHP CLI process to take over 2GB of memory except in some cases. Most of the times it's an indicator something is fishy.

Another example of why this is a bad idea: imagine you have a queuing system on the same server as where you webserver is. Without that limit (provided you are not limiting it in your queue supervisor), you could bring the server down by having a job taking over all the memory.

Another scenario: when you are using a library like AMPHP: you need to provide a certain number of jobs for the given resources. If unlimited, how can you guess what is a reasonable amount? IMO you should take the maximum available: if you don't want that to happen you should limit the resources upstream and this is what the `memory_limit` setting is for.

That said, if there is an easy and robust way to guess that at the application level and people feel strongly about it why not... I feel like this is more foot gun shooting than anything else but that's my personal opinion after all.

**Comment by sanmai** [comment]
See rationale for #252. 

We have to either limit our sub-processes to the amount of memory they may consume, or add a big fat warning everywhere.

It isn't fun when you work with a file and your IDE crashes before you could save your work because you lazily started Infection in another console. Not fun at all.
