### ISSUE TITLE
Module Disabled

### ISSUE THREAD

**Issue by Fenikkusu** [infection/infection#254]
| Question    | Answer
| ------------| ---------------
| Infection version | https://github.com/tobiasstadler/infection:master
| Test Framework version | Codeception
| PHP version | 7.1.12
| Platform    | Docker Image - twistersfury/phalcon:xdebug
| Github Repo | http://gitlab.com/twistersfury/phalcon-json

Really odd issue. If I run the testing using my locally installed copy of PHP, everything runs fine. If I run it through the docker image, it doesn't because a php extension isn't getting loaded.

`docker run --rm -v $(pwd):/workspace -w /workspace twistersfury/phalcon:xdebug ./vendor/bin/infection --test-framework=codeception`

I can force it to work by specifying the INFECTION_DISABLE_XDEBUG env.
`docker run --rm -v $(pwd):/workspace -w /workspace -e INFECTION_DISABLE_XDEBUG=true twistersfury/phalcon:xdebug ./vendor/bin/infection --test-framework=codeception`

The really odd thing is that if I edit PhpIniHelper.php to echo out the loaded paths, the module is there. Not only that, if I add `var_dump(extension_loaded('phalcon'))` in src/phalcon_bootstrap.php, I can see true dumped twice and false for the third time...

Obviously, I can just use the env var to get it to run (Which I'm doing in the Pipeline), but that seems a bit unnecessary to me.

**Comment by BackEndTea** [comment]
Could you check if using #329 fixes this for you?

**Comment by BackEndTea** [comment]
I'm assuming this has been fixed with the 0.9 release. Feel free to re-open the issue if this is not the case.
