### ISSUE TITLE
Run as project dependency

### ISSUE THREAD

**Issue by snapshotpl** [infection/infection#27]
I want to have to require infection as dev dependency in my project. After installation I try to run and...:
```
Warning: require(/var/www/html/auth/vendor/infection/infection/app/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/auth/vendor/infection/infection/app/bootstrap.php on line 7

Call Stack:
    0.0001     364912   1. {main}() /var/www/html/auth/vendor/infection/infection/bin/infection:0
    0.0003     365832   2. require('/var/www/html/auth/vendor/infection/infection/app/bootstrap.php') /var/www/html/auth/vendor/infection/infection/bin/infection:8


Fatal error: require(): Failed opening required '/var/www/html/auth/vendor/infection/infection/app/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/auth/vendor/infection/infection/app/bootstrap.php on line 7

Call Stack:
    0.0001     364912   1. {main}() /var/www/html/auth/vendor/infection/infection/bin/infection:0
    0.0003     365832   2. require('/var/www/html/auth/vendor/infection/infection/app/bootstrap.php') /var/www/html/auth/vendor/infection/infection/bin/infection:8
```

**Comment by borNfreee** [comment]
Hi, thanks for posting this issue.

It has been fixed in https://github.com/infection/infection/pull/22 but not yet released.

I will release it under 0.5.2 soon.

Btw, the recommended way of using infection is a [Phar archive](https://infection.github.io/guide/installation.html#Phar). Besides the issue above, it allows to avoid problems with dependencies conflicts like in #21

**Comment by snapshotpl** [comment]
Thanks for feedback!
Dependency conflict is not problem for me now. Is there any blocker to release 0.5.2 where I can help?

**Comment by borNfreee** [comment]
> Is there any blocker to release 0.5.2 where I can help?

No thank you, this is just a manual process (build phar, check with many projects and compare with previous one, update documentation, changelog, upload phar/pubkey, etc.).

I will do it today or tomorrow, so stay tuned!

PS: time to think about automation of this process...

**Comment by borNfreee** [comment]
@snapshotpl please check the new release https://github.com/infection/infection/releases/tag/0.5.2. It should be possible now to use infection as a composer dependency
