### ISSUE TITLE
Infection can't report on effectiveness of mutators

### ISSUE THREAD

**Issue by sanmai** [infection/infection#271]
| Question    | Answer
| ------------| ---------------
| Infection version | <0.9

Infection can't report on effectiveness of mutators it use. Effectiveness in a sense of number of mutations created, killed, escaped, and errorred. Such report must be mandatory for every PR with a new mutator, and can have other uses.

For example, from #243:

| Mutator          | Mutations     | Killed        | Escaped       | Errors       | 
| ---------------- | ------------- | ------------- | ------------- |------------- |
| Assign           | 437           | 281           | 27            | 1            |
| MethodCallFalse  | 1275          | 583           | 116           | 3            |
| MethodCallNull   | 1275          | 582           | 117           | 3            |
| MethodCallTrue   | 1275          | 563           | 135           | 4            |

**Comment by BackEndTea** [comment]
What about a markdown log type, which prints info like that?

**Comment by sanmai** [comment]
I'm good with markdown, and if there would be JSON too, that'd be best.
