### ISSUE TITLE
Observations - Composer - php-cs-fixer

### ISSUE THREAD

**Issue by Fenikkusu** [infection/infection#279]
Just a slight observation. I'm not sure if it's intentional or not. composer cs:check downloads php-cs-fixer, but composer cs:fix does not. I would assume that A) Both should download and B) neither should download it again if it already exists.

As an additional observation, the composer cs:check creates the directory build/cache. Why not have the wget download the phar into the build folder? That or into build/libraries or similar. Otherwise, the php-cs-fixer file needs to be added to the .gitignore I would think.

**Comment by sanmai** [comment]
First point is going to be fixed by #255.

**Comment by Fenikkusu** [comment]
@sanmai, I agree. #255 should be able to take care of both these points.

**Comment by Fenikkusu** [comment]
Closing
