### ISSUE TITLE
Suggestions Regarding Commit Hooks

### ISSUE THREAD

**Issue by Fenikkusu** [infection/infection#284]
Two suggestions. First, you've the git hook that the ./setup_environment.sh file sets up. I suggest converting this over to using GrumPHP (or a similar package). Its a composer package that automatically handles the git hooks for everyone that installs the composer dev requirements. The only difference is that it runs it on commits as opposed to pushes. In this way, people don't have to run the setup script, as its handled automatically. Secondly, running the push checks the current state of the repo, not the state of the committed repo. As a result, if errors do occur, a person can fix them and then try the push again. They can keep doing this until all the fixes are staged. The push will then go through. Problem is that the commit is still wrong unless the person remembers to commit the code. If not going with GrumPHP, I suggest using git stash (pop) in the pre-push hook to ensure testing against the committed code, not staged code.

**Comment by sanmai** [comment]
GrumPHP will replace existing `pre-commit` hook [with no questions asked](https://github.com/phpro/grumphp/issues/416). This is unacceptable. 

Git hooks are usually not under version control, which means if they're gone, they're gone. Okay, there are backups, but that's a major hassle all the same.

**Comment by Fenikkusu** [comment]
@sanmai, Certainly a valid point. However, the whole point of GrumPHP is to help enforce the business logic and standards of a given project. Additionally, it only effects the one project, not all projects. The only reason I could see this being an issue is because you have setup your own git-hooks outside of the project's specific hook. Now, with that being said, I'm curious to what scenario you've setup which you consider appropriate enough to be, for lack of a better phrase, more important than that the project's standards.

I personally have never had any use for any git hooks, outside of enforcing the project guidelines, so I'm interested in learning what possible uses you have for the hooks.

**Comment by borNfreee** [comment]
Ok, from my point of view GrumPHP is an overkill for us. It's a great tool for the regular project, but we don't need 99% of what it does.

> I suggest [...] using GrumPHP [...], automatically handles the git hooks for everyone that installs the composer

If we want to automatically install our git hook, we can add `post-install` script to `composer.json` and run `./setup_environment` 

```json
"post-install-cmd": [
        "./setup_environment.sh"
 ],
```

> I suggest using git stash (pop) in the pre-push hook to ensure testing against the committed code, not staged code.

Both ways has pros and cons. If you are pushing and have unstaged changes at the same time - probably you forgot to commit something. So I'm not sure what is the best way to proceed here.

**Comment by sanmai** [comment]
> If we want to automatically install our git hook, we can add post-install script to composer.json and run ./setup_environment

If someone installs Infection as a dev dependency, most certainly they don't want, or need, to unittest Infection before every push. Neither they want to run it. This isn't going to work, unfortunately.

> I suggest using git stash (pop) in the pre-push hook to ensure testing against the committed code, not staged code.

I can't pin exactly why, but this feels evil and unwarranted to me. And there's CI for that. 

My belief is that you're all folks who develop Infection are all very sharp and clever. It doesn't seem like you people need any extra help to take care of own Git hooks. More, it could be just me, but I prefer if my hooks are left alone, thank you very much.

**Comment by theofidry** [comment]
I also think that a few guidelines in the contribution guide and eventually calling this script in the Makefile for better discoverability is enough.

I've grown to hate post commit/push hooks as I always seem to find some cases were it's a major pain for no value. IMO having a CI check to make sure we are not violating those rules as well as an easy way to apply them is good enough :)

**Comment by Fenikkusu** [comment]
I'm going to go ahead and close this then. The general consensus on both points is no, and everyone has reasonably valid reasons as to why not.

**Comment by borNfreee** [comment]
> If someone installs Infection as a dev dependency, most certainly they don't want, or need, to unittest Infection before every push. Neither they want to run it. This isn't going to work, unfortunately.

By the way, `setup_environment.sh` won't setup git hook to the project if it is installed as a dependency:

```
ln -sf $(pwd)/devTools/pre-push $(pwd)/.git/hooks/pre-push
```
