### ISSUE TITLE
Provide meaningful feedback on failure

### ISSUE THREAD

**Issue by rjscully** [infection/infection#29]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.5.1
| Test Framework version | PHPUnit 6.2.4
| PHP version | 7.0.23
| Platform    | Windows
| Github Repo | N/A

First, thanks for creating infection! It's great to see an AST-based mutation testing framework. I use "the other" framework and its lack of support for PHPUnit 6 has been a concern.

In the course of setting up to try infection I'm experiencing the same output as #24 but the root cause is not the same. Though we're all well-accustomed to PHP errors, it would be best for the developer to receive an intelligible error message when a problem occurs. It's not possible to say if there was a problem finding a dependency to start infection, generating the coverage, or writing the coverage file. It simply says the file isn't there when it was later requested.

An example fix might be output like "PHPUnit version too low" or "couldn't find PHPUnit" or whatever the problem is (I still haven't diagnosed mine). Providing this output as early as possible will also make it easier for users to fix problems themselves or at least to identify them accurately when requesting support.

**This is not a request for help with my particular problem.** This is a request for meaningful feedback upon failure, especially the problems most likely encountered during the first run for a user or environment.

**Comment by borNfreee** [comment]
Thanks for pointing out to this issue @rjscully. 

Indeed, it needs to be improved. Let's list concrete cases you had together with other potential issues:

1. Not supported PHPUnit version (causes problems with Code Coverage) - **not handled**
2. No whitelist for coverage in `phpunit.xml` (causes problems with Code Coverage) - **handled**
3. PHPUnit executable is not found - **handled**

Anything else? Btw, what was your problem? I will add it to the list above and fix all of them together.

**Comment by rjscully** [comment]
I assumed (based upon #24) that I have some environment problem, but I wasn't able to diagnose it yesterday. Windows environment setup has always given me trouble for some reason so I assumed it's on my end.

If your list were complete, my problem would be an unsupported version of PHPUnit but I don't think that's the case. There must be a 4th option, even if it's an environment config issue it would be ideal to identify the problem.

**Comment by rjscully** [comment]
@borNfreee The fourth case is detailed in #30. Infection is **amazing**!

**Comment by rjscully** [comment]
Additional error case:
Running infection with an invalid infection.json.dist results in a fatal error while instantiating InfectionConfig. (For example, using a traditional Windows path with unescaped backslashes.)
