### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by Fenikkusu** [infection/infection#291]
I'm not as familiar with the Symfony framework, so this may be easy to address (and I've not the time to dig into it right now). I'm trying to work on PR #143  and have been having some issues with the .env file. The changes I've applied work fine on my local environment, but do not work in my CI. As a result, I'd like to add some debugging into the class in question (YamlConfigHelper or something). However, if I recall correctly, I need the output from the symfony command to do this. My question at this point is A) is the output readily accessible so we can add debug code throughout the frameworks, and B) if it's not, what should we do to ensure that it is available.

Once I can access it, I should be able to just use something to the effect of `$this->getOuput()->writeln('Message', <Debug Flag>)`

**Comment by borNfreee** [comment]
Well, if you want to debug your infection fork, just inject `OutputInterface` to the `YamlConfigHelper` as it is done for example [here](https://github.com/infection/infection/blob/master/src/Logger/BadgeLogger.php), in a badge logger, and use it to debug on CI. Then it can be reverted.

> A) is the output readily accessible so we can add debug code throughout the frameworks

No. Each time you need to output something via symfony console output, you need to inject this class manually to constructor.

> if it's not, what should we do to ensure that it is available.

I'm not sure we need it globally. Let's take [BadgeLogger](https://github.com/infection/infection/blob/master/src/Logger/BadgeLogger.php) as an example - it's polluted with the "debug" code. As @BackEndTea already mentioned before - such code looks bad with much noise ([one](https://github.com/infection/infection/blob/master/src/Logger/BadgeLogger.php#L53), [two](https://github.com/infection/infection/blob/master/src/Logger/BadgeLogger.php#L61), [three](https://github.com/infection/infection/blob/master/src/Logger/BadgeLogger.php#L77-L85), [four](https://github.com/infection/infection/blob/master/src/Logger/BadgeLogger.php#L88-L91))

So, personally, I would not add this to [many] classes.

**Comment by sanmai** [comment]
As for the usual debugging, I never had any problems with an `echo` or `var_dump()`. I don't think there's a reason why you can't do this during CI. Obviously you don't want to commit these hacks to master, but if you get the job done it's all that matters.

**Comment by theofidry** [comment]
Differences in the CI with Symfony are likely to be:

- A different `.env` or `parameters.yml` file than you expect is loaded (you can easily dump them to check)
- A different environment is being used, calling a command like `bin/console` will display those informations, e.g. `Symfony 3.4.2 (kernel: app, env: dev_cli, debug: true)`

**Comment by Fenikkusu** [comment]
I tried the passing through the outout (was already working on it prior to the suggestion, lol), and I found it to be a pain in the rear. Back to the tried and true `var_dump`. However, I would like to consider shifting the subject slightly. That being, is it possible to access the container without having to pass it through everywhere? It seems to me, that a somewhat more simple solution, if such a solution is really necessary, would be to just add the output to the container when the execute command runs. Then anyone can just grab it and use it if they'd like. Additionally, it gives them access to anything in the container, should they so need it.

**Comment by borNfreee** [comment]
> is it possible to access the container without having to pass it through everywhere

It's possible to do with the global variable (forgive me, God 🤣 ), with the Registry pattern and so on.

But nothing of these will be implemented in infection as these are antipatterns (global state).

**Comment by BackEndTea** [comment]
>It's possible to do with the global variable (forgive me, God 🤣 ), with the Registry pattern and so on.
But nothing of these will be implemented in infection as these are antipatterns (global state).

Although these paterns are normaly bad design, they may have their place for acces to some kind of logger from anywhere, for debug purposes.

As mentioned in #275 im against the idea of littering code with debug statements, but on the other hand it could come in handy to find out exactly where failures are happening. For people working on infection var_dump is great when trying to make somthing work, but when a user tries to run infection and gets an output that doesn't help anyone it would be great to ask someone to run infection with `--debug` and get detailed information of every step of the process.

**Comment by theofidry** [comment]
>but when a user tries to run infection and gets an output that doesn't help anyone it would be great to ask someone to run infection with --debug and get detailed information of every step of the process.

That's where installing it as a dep and being able to do dump or use break points becomes handy :)

**Comment by borNfreee** [comment]
> but when a user tries to run infection and gets an output that doesn't help anyone it would be great to ask someone to run infection with --debug and get detailed information of every step of the process.

Even in this case, personally I'm against global logger/output/container or something like that:

```
public function methodToDebug()
{
    $logger = Registry::get('logger');
    // ...
}
```

All dependencies should be injected from my point of view

**Comment by BackEndTea** [comment]
> Even in this case, personally I'm against global logger/output/container or something like that:

Understandable, i'm not trying to make a case for having the whole container globally available

**Comment by theofidry** [comment]
@BackEndTea IIRC it already is, or was because it was created in the global namespace and assigned to a variable so you could access to it... @sanmai is making a PR to change that though :)

https://3v4l.org/ZLm2H

**Comment by BackEndTea** [comment]
> @BackEndTea IIRC it already is, or was because it was created in the global namespace and assigned to a variable so you could access to it... @sanmai is making a PR to change that though :)

I never knew PHP worked like this.

**Comment by theofidry** [comment]
we could easily circumvent that by declaring the bin in a namespace as well. It won't affect the code but it will prevent to push things like that in the global namespace :P

**Comment by borNfreee** [comment]
> https://3v4l.org/ZLm2H

bloody nightmare of the old php projects :|

@Fenikkusu can we close this one or is there anything you want to discuss yet?

**Comment by Fenikkusu** [comment]
> bloody nightmare of the old php projects :|

I see it on a daily basis in a project otherwise considered modern...

I'm good at this point. Closing.
