### ISSUE TITLE
Infection does not fail gracefully if PATH isn't set

### ISSUE THREAD

**Issue by sanmai** [infection/infection#295]
| Question    | Answer
| ------------| ---------------
| Infection version | master

With no PATH set Infection fails [in AbstractExecutableFinder](https://github.com/infection/infection/blob/master/src/Finder/AbstractExecutableFinder.php#L22) with a vague TypeError:

```
$ PATH= /usr/bin/php ./bin/infection
 
PHP Fatal error:  Uncaught TypeError: explode() expects parameter 2 to be string, boolean given in src/Finder/AbstractExecutableFinder.php:25
Stack trace:
#0 src/Finder/AbstractExecutableFinder.php(25): explode(':', false)
#1 src/Finder/ComposerExecutableFinder.php(38): Infection\Finder\AbstractExecutableFinder->searchNonExecutables(Array, Array)
#2 src/Finder/TestFrameworkFinder.php(90): Infection\Finder\ComposerExecutableFinder->find()
#3 src/Finder/TestFrameworkFinder.php(73): Infection\Finder\TestFrameworkFinder->findComposer()
#4 src/Finder/TestFrameworkFinder.php(46): Infection\Finder\TestFrameworkFinder->addVendorFolderToPath()
#5 src/TestFramework/AbstractTestFrameworkAdapter.php(101): Infection\Finder\TestFrameworkFinder->find()
#6 src/Process/Builder/ProcessBuilder. in src/Finder/AbstractExecutableFinder.php on line 25
```
`PATH` (or `Path`) environment variable is crucial to Infection, but its absence isn't handled. Alternatively Infection can be made to continue as usual, if possible without PATH.

(Should we use `$_ENV['PATH']` instead of `getenv('PATH')`?)

**Comment by sidz** [comment]
> (Should we use $_ENV['PATH'] instead of getenv('PATH')?)

Don't think that this is a good idea because of this explanation - https://stackoverflow.com/a/8798318

and also we can disable every super global by this option http://php.net/manual/ru/reserved.variables.environment.php#98113  . I'd prefer to leave `getenv`

**Comment by theofidry** [comment]
`$_ENV['PATH']` is safer to use though: unlike `getenv()` it's thread safe
