### ISSUE TITLE
Make Crash Course

### ISSUE THREAD

**Issue by Fenikkusu** [infection/infection#318]
Someone mind giving me a make crash-course? I've read up on make syntax and can otherwise read the instructions, but am still having troubles. 

My basic understanding at this point is that any `<target>:<files>` line can be called using `make <target>` and any `.PHONY` line is there to say 'always run this regardless of if `<files>` exist or not.

For example, I want to build the phar on my local comp. Looking at the make file, I thought I would just run `make build/bin/infection.phar` and be good to go. However, running that gives me the error `make: *** No rule to make target `build/bin/infection.phar'.  Stop.`

**Comment by BackEndTea** [comment]
`make build/bin/infection.phar` works fine for me. Are you sure you are up to date with master?

`.PHONY` means that its not a real file, and should not be checked, so its command should always be executed. 

> My basic understanding at this point is that any `<target>:<files>` line can be called using `make <target>` and any `.PHONY` line is there to say 'always run this regardless of if `<files>` exist or not.

That is correct, `<target>:<files>` is `<target>:<dependencies>` 
So to run the `target` it first checks all `dependencies`. If it is a PHONY target it will always run its command, if its a file it only runs its command if needed.

**Comment by Fenikkusu** [comment]
> make build/bin/infection.phar works fine for me. Are you sure you are up to date with master?

Looks like I was on the wrong project actually xX my bad. Question though, how do I generate the pem file, and should this be added to the make file.

**Comment by Fenikkusu** [comment]
Got It, Closing

**Comment by theofidry** [comment]
>Question though, how do I generate the pem file, and should this be added to the make file.

You should not :/

I don't like this because it's making it harder for contributors. I worked around that in PHP-Scoper by creating a dev `box.json` via the `Makefile` to remove the signing algorithm, but I think it should be integrated directory in Box rather
