### ISSUE TITLE
Implement Regex Mutator

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#324]
@kalessil suggested a set of interesting mutators for Regular Expressions.

```diff
- preg_match("/test/i", $string));
+ preg_match("/test/", $string));

- preg_match("/test/g", $string));
+ preg_match("/test/", $string));

- preg_match("/^test$/", $string));
+ preg_match("/^test/", $string));
+ preg_match("/test$/", $string));
```

and so on.
Original message:

> E.g. add/remove i-flag, `\d,\w\s` <-> `\D,\W\S`, `{<number>[, {number}]}` - same as hardcoded numbers mutations, `.*` <-> `.+`

thoughts?

-----

UPD: now it's clear that we should implement it https://twitter.com/infection_php/status/990136566726189057

**Comment by ntzm** [comment]
How about removing `preg_quote` calls?

**Comment by kalessil** [comment]
For `preg_quote` will be enough to add/modify 2nd parameter with as `''` (when diffs will be more informative about intention).

**Comment by BackEndTea** [comment]
> For preg_quote will be enough to add/modify 2nd argument as '' (then diffs will be more informative about intention).

From what i can tell this won't work
```php
var_dump(preg_quote('\ab?'));
var_dump(preg_quote('\ab?', ''));
```
yields:
```
string(6) "\\ab\?"
string(6) "\\ab\?"
```

**Comment by adeptofvoltron** [comment]
not to duplicate someone's work
yesterday I just to work on murators:

![image](https://user-images.githubusercontent.com/6844275/41502059-73f7f564-71b1-11e8-8442-caa9f4bd3186.png)
![image](https://user-images.githubusercontent.com/6844275/41502061-788859ac-71b1-11e8-9bfb-9e5de52f67aa.png)

they both work similar whey...If carret is present in regex  it delete one...otherway it put one in to the regex.
Same with ending dollar

I would try to make PR today or tommorow. Regards

**Comment by maks-rafalko** [comment]
other ideas to implement: https://github.com/stryker-mutator/stryker-net/blob/master/docs/RegexMutators.md
