### ISSUE TITLE
license is weird

### ISSUE THREAD

**Issue by keradus** [infection/infection#35]
Hi. Isn't license file copy-pasted from `humbug` project ?

This part especially:
```
 Neither the name of Pádraic Brady, Humbug
```
as it points to creator of Humbug and Humbug itself

**Comment by borNfreee** [comment]
> Isn't license file copy-pasted from humbug project ?

yes, it was, but the real license file is [almost the same](https://opensource.org/licenses/BSD-3-Clause)

Nice catch! Fixed.
