### ISSUE TITLE
Infection infects /tmp

### ISSUE THREAD

**Issue by Majkl578** [infection/infection#356]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.8.2
| Test Framework version | PHPUnit 7
| PHP version | 7.2
| Platform    | Linux

Infection pollutes /tmp with thousands of files.
```
$ du -hs /tmp/infection
270M	/tmp/infection
$ ll /tmp/infection | wc -l
18706
```

This should be cleaned up after run. Otherwise it eats space and RAM (`/tmp` is typically `tmpfs` which is RAM-based).

**Comment by borNfreee** [comment]
Probably, it should be configurable since we reuse created mutants to avoid extra IO operations

https://github.com/infection/infection/blob/2276560c4886c79fd6b7175a6039f5c6650d8a93/src/Mutant/MutantCreator.php#L71-L76

On the other side, I'm not sure many people will run infection many times in a row

**Comment by sidz** [comment]
> Once thing that could be done however is create the temporary files in a infection directory of the temporary directory and clean it up at the start of the run (to be careful that it won't affect/collide with the one used for XdebugHandler)

We can't guarantee that user didn't change `tmpDir` between infection execution. IMO we need to clean `tmpDir` after a run.

**Comment by theofidry** [comment]
I don't think the user should change it neither rely that it won't change.

That said it might be an issue with concurrent runs

**Comment by borNfreee** [comment]
fixed https://github.com/infection/infection/pull/357
