### ISSUE TITLE
request: support phpdbg

### ISSUE THREAD

**Issue by keradus** [infection/infection#36]
Hi.
Are there any chances to support `phpdbg`, not only `xDebug` ?

**Comment by borNfreee** [comment]
It is on my list of features to be done before 1.0.0, but currently I'm working on more priority ones.

Would you want to contribute? It shouldn't be difficult.

**Comment by keradus** [comment]
I found this project 5 minutes ago (browsing projects using mine PHP CS Fixer ;P), I'm not that much familiar in this project to start contributing, sorry.
I was requesting phpdbg support for humbug for few months, I hope to not wait that long here ;)

**Comment by theofidry** [comment]
@borNfreee would it be much different than the way it is done in Humbug?

**Comment by keradus** [comment]
ref #37

**Comment by borNfreee** [comment]
@theofidry 
 
> btw do you have a roadmap anywhere?

Not published. Will think about creating a wiki page a using a Project boards with cards wich is more useful.
Basically, this is what I have:

Nearly-term

1. DX - correctly handle exceptions / fatal errors (#29)
2. New mutators (I am about to start creating mutations that removes lines of code - for example void function calls).
3. Performance optimizations. From what I see now, much time is wasted to process code coverage data (XML files generated by `--coverage-xml` option). This issue needs to be investigates and optimized.

Medium-term

1. Internals: creating a behat features for functional tests like PHPSpec does (test creates infection.log, runs infection, analyzes output).
2. Jenkins charts (to use infection on jenkins and analyze charts -> MSI)
3. diff mutations (not sure how it will work yet)

Long-term 

1. Mutations badges. This require 3rd-party service with authentication. Googled about it - there are several options of open source projects that can be reused here
2. PHP AST extension

If you have anything to add - please let me know :)

**Comment by theofidry** [comment]
@borNfreee I do have _a lot_ to add :) I need to get the PHPUnit6 compatibility out of the door for Humbug to release the 1.0.0 (it's just a release to allow a smooth upgrade) and PHP-Scoper (blocked at https://github.com/humbug/php-scoper/issues/98) and then I'll be fully focused on mutation testing, be it Humbug 2.0, Infection or another.

Btw you should join us on Slack :P I'll ping you some ideas/issues as soon as I'm done with the two points above

**Comment by keradus** [comment]
guys, maybe it's not worth to develop 2 great projects for mutation, maybe you could combine forces to bring one great project a boost ?

**Comment by theofidry** [comment]
>and then I'll be fully focused on mutation testing, be it Humbug 2.0, Infection or another.

Making a separate project given the little free time me or padraic had was a good move on @borNfreee part. How it goes next, be it two separate projects, disrupting Humbug for Injection or making Injection Humbug 2.0 to benefit from the traction it has, it's open for discussion and depends on @borNfreee views as well.

It might be selfish of me but at the end of the day I don't really care: I just want mutation testing to kick off and have a good tool for it :)

**Comment by keradus** [comment]
I wish best for both of you, I played a little with both of them, both are nice (not perfect, as everything ;P)
As end-user, for me, it would be great if you could find a way to cooperate, and bring one perfect solution for mutating. If not, I will end up using both of them to catch as much mutations as possible.
