### ISSUE TITLE
False positive: count(-1) (decrement integer mutator)

### ISSUE THREAD

**Issue by luispabon** [infection/infection#364]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.8.2
| Test Framework version | phpunit 7.1
| PHP version | php 7.2
| Platform    | Ubuntu

I have the following code being mutated by DecrementInteger

```php
 if (\count($diff) === 0) {
    // stuff
}
```

into
```php
 if (\count($diff) === -1) {
    // stuff
}
```

This is clearly a false positive as `count` can't possibly return 0.

**Comment by borNfreee** [comment]
this should now be fixed in https://github.com/infection/infection/pull/365

**Comment by luispabon** [comment]
:D
