### ISSUE TITLE
Mutator blacklist 

### ISSUE THREAD

**Issue by Grummfy** [infection/infection#380]
**Is your feature request related to a problem? Please describe.**
I would like a mutator blacklist like we have the white list available with --mutator to help remove some mutator from the list 

**Describe the solution you'd like**
--mutator-blacklist=.... 

**Describe alternatives you've considered**
For now adding every mutator in the argument about it and remove the one I don't want to

**Additional context**
I think it's obvious ;)

**Comment by sanmai** [comment]
What is your use case for a mutator blacklist? What is that this feature is supposed to archive?

**Comment by borNfreee** [comment]
@Grummfy we have a new feature of "profiles" already implemented in master https://github.com/infection/site/blob/master/src/guide/profiles.md

So if you need to exclude some mutators, you can do it in the `infection.json`

```json
{
    "mutators": {
        "@default": true,
        "@function_signature": false,
}
```

Does it cover your use case?

**Comment by Grummfy** [comment]
Yes it cover what I need. Would be happy to have it in the command line but that's enough. Thanks

**Comment by borNfreee** [comment]
Glad it helped. Thank you for using Infection!

Closing for now.
