### ISSUE TITLE
Tolerant failures (Recoverable fatal error in PregQuote mutator)

### ISSUE THREAD

**Issue by theofidry** [infection/infection#382]
| Question    | Answer
| ------------| ---------------
| Infection version | master (`2499d3d`)

When an unexpected error occurs, for an incorrect assumption in Infection leading to a fatal error like this:

```
PHP Recoverable fatal error:  Object of class PhpParser\Node\Expr\PropertyFetch could not be converted to string in /home/travis/build/humbug/box/vendor/infection/infection/src/Mutator/Regex/PregQuote.php on line 36
```

I think a more contextual error would be helpful, for example giving the problematic file name

**Comment by BackEndTea** [comment]
Do you know exactly what is causing the error?

**Comment by theofidry** [comment]
Well looking at the code I have a rough explanation but the interesting bit that I'm missing is what actual code ended up generating that issue. You can try yourself it happens on humbug/box master, I couldn't point it yet because it is so slow to run

**Comment by BackEndTea** [comment]
Does #385 fix your error @theofidry ?

**Comment by borNfreee** [comment]
ping @theofidry

**Comment by theofidry** [comment]
Will try to check again on Box and open the issue again if the issue is still there
