### ISSUE TITLE
Locally enabled xdebug using `php -d` ignored

### ISSUE THREAD

**Issue by Majkl578** [infection/infection#392]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.9.0-beta.2
| Test Framework version | PHPUnit 7.1.4
| PHP version | 7.2.7
| Platform    | Linux

With XDebug disabled globally, only turned on per-process, Infection fails to respect this and crashes.
Note that main process does correctly detect XDebug being enabled, but does not propagate it to sub-processes.

```
$ php -dzend_extension=xdebug vendor/bin/infection 
You are running Infection with xdebug enabled.
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____ 
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/
 
Running initial test suite...

PHPUnit version: 7.1.4

 5186 [============================] 2 secs

Generate mutants...

Processing source code files:   1/249
In CoverageDoesNotExistException.php line 21:
                                                                                                                                                                                         
  Code Coverage does not exist. File /tmp/infection/coverage-xml/index.xml is not found. Check phpunit version Infection was run with and generated config files inside /tmp/infection. 
```

XDebug must be enabled globally in order to make it work.

**Comment by theofidry** [comment]
>that main process does correctly detect XDebug being enabled, but does not propagate it to sub-processes.

AFAIK this is the expected behaviour, you should set the environment variable `INFECTION_ALLOW_XDEBUG=1` to allow it to be propagated to sub processes

**Comment by sanmai** [comment]
It appears to me that xdebug-handler won't pass-through options given on the command line, which leaves us with two options:

1. Run Infection with xdebug always enabled, like @theofidry suggested with `INFECTION_ALLOW_XDEBUG=1`

2. Another option is to generate coverage manually, then pass it to Infection:
```
php -dzend_extension=xdebug vendor/bin/phpunit  --coverage-clover=clover.xml --coverage-xml=coverage/coverage-xml --log-junit=coverage/phpunit.junit.xml
php vendor/bin/infection --coverage=coverage -j4
```

**Comment by BackEndTea** [comment]
If i remember correctly you can use the  `--initial-tests-php-options` for this.
So you would run it like

```bash
$ vendor/bin/infection --initial-tests-php-option='-d zend_extension=xdebug.so'
```

**Comment by borNfreee** [comment]
Added doc PR: https://github.com/infection/site/pull/46/files#diff-c505802353b0e250e559497bda4139b2R111

**Comment by borNfreee** [comment]
Added detailed error message and note to documentation about how to enable Xdebug for just 1 process.

@Majkl578 please use `infection.phar --initial-tests-php-options="-d zend_extension=xdebug.so"`

**Comment by Bilge** [comment]
>  The "--initial-tests-php-option" option does not exist.
