### ISSUE TITLE
Location of test framework

### ISSUE THREAD

**Issue by dmecke** [infection/infection#4]
As a developer, I want to be able to configure the location of the test framework.

I don't have PHPUnit installed globally on my local system as I need to use different versions for different projects. So I have a shared directory with the different versions of PHPUnit in it. It seems that Infections looks for a `phpunit.phar` either installed globally or in the current directory. It would be nice if I could define the location explicitely.

**Comment by borNfreee** [comment]
Released under [0.3.0](https://github.com/infection/infection/releases/tag/0.3.0)
