### ISSUE TITLE
Do not mutate code that is ignored from code coverage

### ISSUE THREAD

**Issue by sebastianbergmann** [infection/infection#407]
Code that is ignored from code coverage (`@codeCoverageIgnore` annotation on a class or method; `@codeCoverageIgnoreStart` and `@codeCoverageIgnoreEnd` blocks; `@codeCoverageIgnore` on a single line) should not be mutated.

**Comment by sebastianbergmann** [comment]
Thanks for pointing out the workaround!

**Comment by borNfreee** [comment]
partially implemented (for class and method level). Thank you @sebastianbergmann
