### ISSUE TITLE
Build failures on Travis/phpdbg: FD_SETSIZE limitations

### ISSUE THREAD

**Issue by sanmai** [infection/infection#412]
We started getting [interesting failures with phpdbg](https://travis-ci.org/infection/infection/builds/405048670):

```
Infection\Tests\StreamWrapper\IncludeInterceptorTest::test_passthrough_file_methods_pass
stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.                                               
It is set to 1024, but you have descriptors numbered at least as high as 1027.
--enable-fd-setsize=2048 is recommended, but you may want to set it 
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date.
```

**Comment by BackEndTea** [comment]
Can confirm this also happens when running `make test-infection-phpdbg-72`, so its not a travis issue.

I'm not sure if this is an issue in:
* Infection
* The test suite
* phpdbg itself

**Comment by sanmai** [comment]
That's great! Were you able to bisect it?

**Comment by BackEndTea** [comment]
PHP cs fixer seems to have a similar issue, linking here for future reference
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3929
