### ISSUE TITLE
Space in directory path breaks Infection

### ISSUE THREAD

**Issue by GaryJones** [infection/infection#413]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.9.0 (`infection.phar --version`)
| Test Framework version | PHPUnit 7.2.7
| PHP version | 7.1.7 (`php -v`)
| Platform    | MacOS
| Github Repo | -

The path to my directory where I want to run `infection` has got a space in it, and so the `exec /Users/gary/Local Sites/long/path/to/my/phpunit --version` fails.

```
Error Output:
  ================
  sh: /Users/gary/Local: No such file or directory
  sh: line 0: exec: /Users/gary/Local: cannot execute: No such file or directory
```

**Comment by BackEndTea** [comment]
Thank you for reporting this issue to us. 

I think an [`escapeshellarg `](http://php.net/manual/en/function.escapeshellarg.php) with the testframework finder will do the trick

**Comment by sidz** [comment]
there is the same issue with the custom `tmpDir` as well.

**Comment by borNfreee** [comment]
Released https://github.com/infection/infection/releases/tag/0.9.2

**Comment by BackEndTea** [comment]
:clap:
