### ISSUE TITLE
Drop PHP 7.0 support

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#414]
PHP 7.0 will end security support in [4 months](http://php.net/supported-versions.php). So i think its about time that we drop support for php 7.0 as well. We could target `0.10`, or only add deprecation warnings for users running php 7.0 in that version, and then upgrade to `0.11`.
Dropping 7.0 means that users who have projects that support 7.0 can't have infection as a dev dependency anymore. 

I'd like to hear what people think.

**Comment by localheinz** [comment]
@BackEndTea 

Sounds good to me!

Users on PHP 7.0 can still use older versions of `infection/infection`.

**Comment by ryan7273** [comment]
All of my old code is still on PHP 5. Everything that's been migrated is running on 7.3. This change won't make any difference to me and I would tend to agree with localheinz. Philosophically I agree with supporting older stuff, but dev time is limited and I don't think it makes sense to continue support past official language support; especially when upgrading is fairly trivial.

**Comment by sanmai** [comment]
That's going to make things difficult CI-wise. Now you just throw Infection and it works anywhere. Else you would be using this version of Infection here and that version there, giving all kinds of interesting situations. That's a clear drawback. Which leads me to the question...

Why would we do that? What are the benefits? Other pros and cons?

**Comment by borNfreee** [comment]
Implemented
