### ISSUE TITLE
Brew installation isn't supported anymore or docs aren't updated

### ISSUE THREAD

**Issue by ricardofiorani** [infection/infection#416]
When trying to follow the installation tutorial from https://infection.github.io/guide/installation.html using :

`brew install infection`

I get a message `Error: No available formula with the name "infection"`.

If I search on brew:
```
▶ brew search infection
No formula or cask found for "infection".
```

Is Brew installation not supported anymore and the docs aren't updated OR is the docs just not updated with some missing step ?

EDIT:

```
▶ brew -v
Homebrew 1.7.0
Homebrew/homebrew-core (git revision 11dc; last commit 2018-07-23)
```

**Comment by borNfreee** [comment]
Thank you for letting us know, @ricardofiorani !

According to [this post](https://brew.sh/2018/01/19/homebrew-1.5.0/), this is not in the Homebrew core anymore and won't be

> [...] Unfortunately we have been unable to maintain an acceptable, consistent user or contributor experience and CI workload through non-core formula taps in the Homebrew organisation so we are continuing to migrate widely used formulae into Homebrew/core and encourage more niche formulae and options to be supported outside the Homebrew organisation.

[Homebrew-php](https://github.com/Homebrew/homebrew-php) has been deprecated and archived, Infection formula has not been migrated to the [Homebrew-core](https://github.com/Homebrew/homebrew-core).

For reference: 

* Commit to integrate Infection to Homebrew: [diff](https://github.com/Homebrew/homebrew-php/commit/07e255ee1069dd8d6ec2df59d47753a5b9749373#diff-1786a6615bed4174b29ad066197470aa)
* PR: https://github.com/Homebrew/homebrew-php/pull/4519

IMO, we should not support Homebrew by ourselves and should remove it from documentation. The main and recommended ways to install Infection are PHAR and `composer require`.

If someone can/want maintain (probably @pierredup) it - you are welcome. 

Personally, I would concentrate my time on Infection itself.

**Comment by BackEndTea** [comment]
I'd like to know a few things;
* What was the original reason to support installing through homebrew?
* Are there other php packages that are installed through homebrew?
* How much work is it to maintain the homebrew installation?

**Comment by borNfreee** [comment]
1. @pierredup made a [PR](https://github.com/infection/site/pull/11) and integrated Infection to Homebrew one day
2. There were [many packages](https://github.com/Homebrew/homebrew-php/tree/phan-0.9.3/Formula) in the Homebrew
3. At least: a) read about how to support Formula on 3rd party repository b) create repository (infection/homebrew for example) c) update it any time something does not work (you should have MacOS or VM). Last point is going to take not much time, but still

**Comment by BackEndTea** [comment]
Personally i'd say, remove it form the docs for now.

The preferred installation is as a phar, but if we get a lot of requests for homebrew support we should reconsider.

**Comment by pierredup** [comment]
I've removed the homebrew installation instructions from the doc at infection/site#51. I have also created a repository for the homebrew formula at pierredup/homebrew-infection. If you prefer to not mention homebrew at all in the docs, then I can remove everything, otherwise I made a note of the repository in the docs

**Comment by borNfreee** [comment]
thank you @pierredup, I've checked it and it works! I'm for leaving it on your account and for merging your PR in the doc

👍

**Comment by theofidry** [comment]
What about migrating it under the infection organization and provide
@pierredup wrote access on it?

**Comment by BackEndTea** [comment]
> What about migrating it under the infection organization

I would prefer this as well, it keeps everything organized, and prevents a dependency on one person.

**Comment by sanmai** [comment]
It's a single file. It can be right in the main repository, and then you would install it with:
```
brew tap infection/infection
brew install infection
```

**Comment by pierredup** [comment]
> It's a single file. It can be right in the main repository, and then you would install it with:
> 
> brew tap infection/infection

Homebrew by default looks for a `homebrew-` prefix.
So if you run the command `brew tap infection/infection`, it will try and clone a repository from `https://github.com/infection/homebrew-infection`, so the formula will have to be in a separate repository

**Comment by borNfreee** [comment]
Moved to https://github.com/infection/homebrew-infection

Invited @pierredup as an external collaborator with Write access.

Thank you.

Now infection can be installed like:

```
brew tap infection/homebrew-infection
brew install infection
```

**Comment by pierredup** [comment]
Thanks @borNfreee
