### ISSUE TITLE
Should infection keep using a json config?

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#419]
Currently infection uses a json file as its configuration file. I don't know what the original reason was for a json file, but i'd like to find out if there are better options for us.

We are at a stage where we could still make a transition between config styles, if there is a benefit to doing so. So i'd like to resolve this somewhere before `1.0.0`

Some viable options could be:

* XML, like phpunit
* YAML, like phpspec
* PHP: like php-cs-fixer

I think we should look at what the benefits and limitations of each configuration style are. And then decide if one style provides enough benefit to make the change.

If we do decide to change we should still support the json configuration style for **at least** one minor version, and give a big deprecation warning.

**Comment by ryan7273** [comment]
Personally, I really like JSON for config files. It is easy to read, easy to validate, and not especially bloated. XML works as well, but requires more typing and I see no benefit from the extra characters. I've always viewed JSON as a superior XML.

I really loathe YAML along with every other language where whitespace is significant. I find it more difficult to read and work with.

No strong opinions about PHP. I guess the advantage would be that it wouldn't require knowledge of outside languages. For the pure PHP programmer it may be simpler to get up and running.

**Comment by borNfreee** [comment]
1. IMO, yaml is not so good. Too many errors just because of incorrect indentation. 
2. XML is too verbose, I'm not sure we will get any benefits until we use some XSD schema for validation and autocompletion (like `./vendor/phpunit/phpunit/phpunit.xsd`)
3. JSON is quite ok. The main issue with JSON is that we can't use comments.
4. [neon](https://ne-on.org/). What the hell is neon? 
5. PHP. Probably, but I didn't manage to find any reason at the moment.
6. Custom format (hello Dockerfile) - no

**Comment by sidz** [comment]
don't see any sense of using yml. Because it will need to add new dependency at least. Anyway it doesn't more readable then json. IMO no benefits.

XML - agree with @borNfreee 

Json - @borNfreee do we need to use comments? what for? :)

**Comment by borNfreee** [comment]
> Json - @borNfreee do we need to use comments? what for? :)

No need to use it, I just pointed out a drawback of JSON format in general.

@BackEndTea what is the original cause of this ticket? Did you have a situation where JSON didn't suit you?

**Comment by BackEndTea** [comment]
So far I haven't had any issues with JSON. I'd just like to make sure that it is the right config style for us.

**Comment by sanmai** [comment]
As @borNfreee said, the main issue with JSON is that we can't use comments, therefore you can't have a self-documented config file. Which is a bummer, user interface-wise. Secondly, JSON is very picky about commas, and so on. I wonder if there is a parser for kind-of-JSON that would permit comments, and so on.

Else I'm all pro YAML. Yeah, it is a bit picky about indentation, and there are other issues with big fat complex files, but they all can be avoided. Let's say, how many times you have any of these issues when editing `.travis.yml`? I hardly remember if I had them.

As for dependencies @sidz mentioned, we already have `symfony/yaml` in our dependencies, so there's nothing new on this front.

**Comment by deleugpn** [comment]
After transitioning my AWS CloudFormation from json to yaml all I can say is that yaml readability is infinite times superior over json.
However, infection config are not that extense and feels familiar by php devs because of composer.json.
Offering yaml in addition to json could be cool.

**Comment by localheinz** [comment]
I think it’s important that configuration can easily be validated. Both `json` and `XML` can be easily validated via schema files. With `xml`, when referencing schema files, a developer also has auto-completion and validation within the IDE. I think that is at least a good argument for `xml`. 

In the end it probably doesn’t matter much, but the question is whether it is worth providing (or using) different configuration file format readers, or whether it’s enough to stick to a single format. 

What do you think?

**Comment by theofidry** [comment]
I think there is two more things to consider:

- The migration path: we either pick a new config format and force users to migrate to it or a support for a new format
- If we support multiple format, we will need a configuration validation so the only benefit XML would have is auto-completion, the validation being redundant

**Comment by borNfreee** [comment]
https://twitter.com/infection_php/status/1028234812014903296?s=19

Let's ask community is it needed at all to changr something

**Comment by Ocramius** [comment]
XML all the way: if your snippets include an XSD reference pointing at `vendor/infection/infection/infection.xsd`, you get auto-complete out if the box, and there's basically no typing involved 👍

**Comment by Ocramius** [comment]
Example: https://github.com/Roave/BackwardCompatibilityCheck/blob/1.0.3/phpunit.xml.dist#L4

**Comment by sanmai** [comment]
That's non-standard JSON, all other parsers/validators will choke on it.

**Comment by borNfreee** [comment]
Results of [twitter poll](https://twitter.com/infection_php) (353 votes):

```
62%  json (current)
13%  xml
11%  Several formats
14%  Other (comment pls)
```

How I interpret them (your interprentaion may be different):

1. We are using the right default config file format: `json`. This format got majority of the votes (62%)
2. 38% of the users (which is quite a big value) want another format or several formats to have a choice
3. 13% of 38% want `xml`
4. There are valid statements in comments that both `json` and `xml` are good choices because of schema validation and autocompleted out of the box for `xml`

My opinion: we should support both: `json` (default) and `xml` (otherwise we should stick to `json` and do nothing).

If we decide to add `xml`, we should also update documentation and show configuration for both format, how Symfony does it (with tabs).

**Comment by davidjeddy** [comment]
@sanmai Your statement is true. Just throwing out ideas to see what might stick.

**Comment by deleugpn** [comment]
I think the poll was a little unclear. Yaml was not an option. Several formats implies more than 2. Others might imply dropping json, so I was left with json as the only valid answer since I don't enjoy xml.

**Comment by Ocramius** [comment]
Supporting multiple formats just leads to confusion: dropping some made things much more manageable and homogeneous in the community of @doctrine/doctrine-core, so I suggest to avoid going down that route unless you want to start having sub-packages just to configure the minimal flags that infection supports.

On the other hand, building a Dhall plugin would be really fun :D

**Comment by Ocramius** [comment]
> If we decide to add `xml`, we should also update documentation and show configuration for both format, how Symfony does it (with tabs).

You can probably just provide an empty XML with an XSD location in it: no real need to document it if the XSD contains all relevant descriptions.

**Comment by sidz** [comment]
@borNfreee my 5 cents:
> My opinion: we should support both: json (default) and xml (otherwise we should stick to json and do nothing).

I'm pretty sure that there is no needs to support more than one config format. Will be better to keep Infection as simple as possible. And concentrate on other things.

**Comment by localheinz** [comment]
Agree with @sidz, a single configuration format should be fine.

**Comment by borNfreee** [comment]
I'm super happy to have only one `json`.

The main question of this issue has been answered. @BackEndTea can we close it?

**Comment by BackEndTea** [comment]
Yeah this can be closed
