### ISSUE TITLE
padraic/phar-updater should not be a dependency outside the phar

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#425]
Currently, infection has `padraic/phar-updater` as a dependency.

We do need it when running the par, but it should not be part of our dependencies when it is installed as a composer dependency.

**Comment by theofidry** [comment]
It's unfortunately very tricky to do, unless you would manage the app (which is the PHAR) with a different `composer.json` file.

That said, I believe updating a PHAR should be left to tools like [phive](https://phar.io/) which are more secure and we could simply remove the whole self-update feature altogether.

**Comment by borNfreee** [comment]
The other option is Composer Merge Plugin https://github.com/wikimedia/composer-merge-plugin
