### ISSUE TITLE
Infection 0.9 isnt compatible with symfony/console <3.4

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#435]
Spotted here: https://github.com/Roave/DoctrineSimpleCache/pull/27#issuecomment-410521494

Not sure what is causing the issue, but best course of action would be to simply require 3.4. Which i already targeted for `0.10` in #430.

Should we also release a new 0.9 with that minimum requirement?

**Comment by sidz** [comment]
I'd say that we shouldn't drop the support of 3.2 for Infection 0.9. 

build with fail: https://travis-ci.org/Roave/DoctrineSimpleCache/jobs/412320302

will double check on the next week

**Comment by borNfreee** [comment]
Fixed and released as 0.9.3
