### ISSUE TITLE
Infection may apply a memory limit to the normal php ini

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#442]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.9.3 (`infection.phar --version`)
| Test Framework version | PHPUnit 6.5
| PHP version | 7.2.7
| Platform    Ubuntu
| Github Repo | this one

When running infection with `INFECTION_ALLOW_XDEBUG=1`, we use the 'default' php ini, as we don't use xdebug handler. When you run cli from an account that has write access to the php ini, a memory limit will be set

**Comment by sanmai** [comment]
> When you run cli from an account that has write access to the php ini

One shouldn't do that in the first place.

**Comment by BackEndTea** [comment]
> One shouldn't do that in the first place.

I must admit that I ran this as root in order to trigger this behavior. It is, however, something that could happen if a user is not careful.

I was also able to reproduce this on my mac, without needing to sudo
