### ISSUE TITLE
Should 'default' keep containing all mutators?

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#444]
Taking this repo as an example:

The phpunit test suite(excluding e2e tests) takes roughly 5 seconds.
The infection, mutation test suite (once again excluding e2e tests), running with 4 threads and only on covered mutations, takes one minute and 42 seconds. Thats already 20 times as long.

If you have any tests that depend on the state of a file system or database or something alike, you can't run it in multiple threads which increases the time the tests take by a lot.

My point here is that mutation testing is 'slow', which is simply a consequence of what mutation testing is. However it may scare of new users, who have a test suite that already takes a few minutes, and uses the file system or database. For them infection is gonna take 30 minutes or something.

Therefor i'd propose to remove mutators from `@default` and leave that as a baseline, while creating a new `@all` profile that does keep all the mutators, for those who want to always run all of them.

This 'should' also help with better BC, as it won't cause MSI and Covered MSI to fluctuate much between releases.

**Comment by borNfreee** [comment]
Agree, I like the idea of having a limited `@default` profile. The main question here is what Mutators will be in this profile. 

I believe a deep analyzing of at least several quite big repositories is needed to decide what are the most useful mutators.

We need to understand for each Mutator how often this mutation appears in the log (in %), is it a big value to kill this mutation, what is the average MSI for this mutator across repositories, etc.

I mean, if some Mutator produces hundreds of mutations but almost all of them are killed from project to project, then it shouldn't be in the `@default` profile.

Finally, we can create a poll and ask our users about what mutations they like or deal with more often.

**Comment by sanmai** [comment]
For this we better somehow estimate efficiency of all and every mutators. Like by running a survey on as many open-source project we may lay our hands on. Precisely this idea I had when filing #271. Then we would know exactly which mutations are most efficient, and should stay in the default profile.

**Comment by theofidry** [comment]
Since we not longer include all mutators in `@default` in order to keep a high efficiency ratio I guess this issue is good to be closed?

IMO we can always revisit the question on a case by case basis anyway.

**Comment by sanmai** [comment]
Yes, I think this could be closed for time being, since we have no evidence to the contrary.
