### ISSUE TITLE
Integrate Codeception testing framework

### ISSUE THREAD

**Issue by vworldat** [infection/infection#45]
I'm using [codeception](http://codeception.com/) as my main testing framework and may be interested in providing the integration. Has anybody else already started working on codeception integration or have there been any blockers I don't know about yet?

**Comment by borNfreee** [comment]
Hello, thank you for posting this question.

I'm not aware of any activity about integrating Infection with Codeception. Wouldn't you want to be the first one? :)

As soon as it supports code coverage (just checked - it supports), I think there is no problem to do it.

> or have there been any blockers I don't know about yet

Several points to consider before implementation:

1. We need to be able to pass such parameters as (they may have different names in Codeception) 
1.1 `--stop-on-failure` - to stop executing tests when the first is failed
1.2 `--configuration` - to override location of configuration file

2. Ideally we need to be able to generate `junit.xml`. This is needed to fetch execution time of each test and sort them during mutation testing for performance reason

3. And the most important thing: we need to be able to run only particular tests (e.g. test `C`, `D`) from the whole {`A`, `B`, `C` , `D`, `E`} testsuite. This is also for performance reason. But if it's impossible in Codeception, it does not block integration.

-----

There are already two examples of integrated testing frameworks (PHPUnit, PhpSpec) so it's clear where to start.

**Comment by sidz** [comment]
@vworldat have you started to do anything?

**Comment by vworldat** [comment]
@sidz not yet, unfortunately there was no time

**Comment by tobiasstadler** [comment]
Hi,
I integrated Codeception into Infection, see https://github.com/tobiasstadler/infection

I will create a PR once https://github.com/Codeception/Codeception/pull/4562 (which is required by my implementation) is merged.

**Comment by vworldat** [comment]
Wow, thanks a lot @tobiasstadler !

**Comment by DavertMik** [comment]
Merged at Codeception. The next release (2.3.8) will include those changes.

**Comment by metalcamp** [comment]
@DavertMik when is next release planned?

**Comment by DavertMik** [comment]
Everything looks like is ready. I plan to make a release this month.

**Comment by metalcamp** [comment]
@DavertMik: you mean dev-master or some other release?
I get following error when adding 2.3.x-dev to composer.json
```
Problem 1
    - The requested package infection/infection 2.3.x-dev exists as infection/infection[0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.6.1, 0.6.2, 0.7.0, dev-master, dev-mockery10, dev-php-parser-400, dev-reflection, dev-reflection2, dev-theofidry-patch-1] but these are rejected by your constraint.
```

**Comment by borNfreee** [comment]
@metalcamp current Infection version is 0.7.0. @DavertMik was writing about 2.3.8 version of Codeception.

Codeception is not supported by Infection at the moment.

@tobiasstadler any new on your branch?

**Comment by sanmai** [comment]
Codeception is at version 2.4.0 now FWIW.

**Comment by voku** [comment]
any news on this?

**Comment by borNfreee** [comment]
no news. AFAIK nobody works on it at the moment. 

New PR is in #457 

See https://github.com/infection/infection/pull/457#issuecomment-424499650

**Comment by voku** [comment]
Thanks for the feedback, anyway.

**Comment by sanmai** [comment]
See also #499 for general discussion.

**Comment by maks-rafalko** [comment]
New PR and discussion will be here https://github.com/infection/infection/pull/800

**Comment by maks-rafalko** [comment]
Implemented in https://github.com/infection/infection/pull/800
