### ISSUE TITLE
Premature Process Termination.

### ISSUE THREAD

**Issue by Fenikkusu** [infection/infection#459]
| Question    | Answer
| ------------| ---------------
| Infection version | #457 
| Test Framework version | Codeception 2.4.2
| PHP version | 7.1.17
| Platform    | MacOS
| Github Repo | https://github.com/twistersfury/infection

InitialTestsRunner::57-58 needs to be revised. When codeception runs, it echos to the error output in pieces. This creates a race condition where all the output of STDERR does not have a chance to echo/process before the parent infection run calls the stop command. This ends up resulting in error code 143 because the pipe gets killed prematurely. I'm still looking for the best way to fix this, but thought someone might have an answer. At the very least, the stop command should allow the echo to finish. My suggestion is to only call the stop after the timeout command. That should give the main command to successfully finish in full. Will test when I get the chance.

**Comment by Fenikkusu** [comment]
I have applied a preliminary/suggested fix to the MR.

**Comment by maks-rafalko** [comment]
Closing as no one complains about this, and Codeception was redeveloped from scratch
