### ISSUE TITLE
Do not mutate the code inside plain functions

### ISSUE THREAD

**Issue by borNfreee** [infection/infection#466]
Related https://github.com/infection/infection/pull/456

Example: when there is a closure inside a plain function, current Infection mutates it. It does not make any sense.

```php
function property($path): callable
{
    return function ($value, $index = 0, $collection = []) use ($path, $propertyAccess) {
          // should NOT be mutated
    };
}
```

On the other side, we can mutate closures that are on the global scope:

```php
// global scope

$filtered = array_filter([1, 2, 3], function ($value) {
    return $value % 2; // we CAN mutate here
});
```

**Comment by theofidry** [comment]
In other words we can when it's a *non static* anonymous function. 👍

**Comment by sanmai** [comment]
On the other hand, we should definitely mutate functions that *do not exist* in the global scope at the time of a mutation. E.g. if `function_exists($functionName)` returns false, then our mutations will affect tests, and will be useful. Although I'm not entirely sure that is going to happen any often.
