### ISSUE TITLE
[New Mutator] Swap arguments in the Spaceship operator

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#47]
New mutator to implement:

```diff
- $a <=> $b
+ $b <=> $a
```

#### Why?

To determine whether the sorting function is correctly covered by tests and parameters are not mixed up.

#### What needs to be done?

1. First, a new mutation operator (mutator) should be created [here](https://github.com/infection/infection/tree/master/src/Mutator)
2. It should be registered in the [configuration file](https://github.com/infection/infection/blob/c9531cb42b15543f7faff5e14761e2767bd0f478/src/Config/InfectionConfig.php#L67).
3. Unit test should be added to proof it works as expected.

-----

> I would like to involve more contributors for the upcoming [Hacktoberfest](https://hacktoberfest.digitalocean.com/). Feel free to submit your first PR and get a T-Shirt!

**Comment by marcosh** [comment]
I'd like to work on this issue!

**Comment by borNfreee** [comment]
@marcosh you are welcome. Feel free to ask me any questions.
We also have [Slack channel `#infection`](https://symfony-devs.slack.com/messages/C4ZEGUW5R) and a [Gitter room](https://gitter.im/infection/Lobby)
