### ISSUE TITLE
--initial-tests-php-options ignored on Windows

### ISSUE THREAD

**Issue by johnstevenson** [infection/infection#471]
| Question    | Answer
| ------------| ---------------
| Infection version | dev-master
| Test Framework version | irrelevant
| PHP version | 7.1.18
| Platform    | Windows
| Github Repo | -

Unless a custom path is being used for the test framework, the library will find the `.bat` proxy file in `vendor\bin`. This stops the use of `--initial-tests-php-options` as these options will be ignored (because they cannot be used).

**Comment by sanmai** [comment]
So the `phpunit.bat` won't pass-through options?

**Comment by johnstevenson** [comment]
@sanmai Yes, it will pass-through options, but not command-line options for php itself when a proxy is being used.

For example: `--initial-tests-php-options=-d zend_extension=xdebug.dll` is used to create the following  command-line:

```
php -d zend_extension=xdebug.dll phpunit ...
```
But this cannot be done in a .bat proxy because it invokes php without any command-line arguments:

```
php "%BIN_TARGET%" %*
```
