### ISSUE TITLE
Exclude --testsuite from PhpUnit mutant options, but allow for initial process

### ISSUE THREAD

**Issue by tomtomau** [infection/infection#480]
**Is your feature request related to a problem? Please describe.**

Given a circumstance where I have a large codebase, I may want to specify the `--testsuite` [option](https://phpunit.de/manual/6.5/en/textui.html) for my initial test run.

While setting this option is satisfactory for the initial test run, it conflicts with the mutant process as each mutant has a custom `phpunit.xml` generated for the mutation that defines it's own testsuites, such as:

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://phpunit.de/manual/current/en/appendixes.configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/6.1/phpunit.xsd" backupGlobals="false" colors="false" bootstrap="/tmp/infection/interceptor.autoload.fc0b5b0381dd1a59ad01f1ed0d0f8bcf.infection.php" stopOnFailure="true">
  <testsuites>
    <testsuite name="Infection testsuite with filtered tests">
      <file>/path/to/the/specific/test/infection/wants/to/Run.php</file>
    </testsuite>
  </testsuites>
</phpunit>
```

As a result, the user's `--testsuite=Foobar` option is applied to this mutant PhpUnit process and the behaviour of PhpUnit is to simply exit 0 with a warning that no tests were executed.

```
$ bin/phpunit -c /tmp/infection/mutated-phpunit.xml --testsuite=foobar
#!/usr/bin/env php
PHPUnit 6.5.13 by Sebastian Bergmann and contributors.

Time: 90 ms, Memory: 4.00MB

No tests executed!
```

As far as I can tell, this led to some pretty huge false-negatives for us, suggesting that the mutant was killed when it definitely was not.

**Describe the solution you'd like**

Similar to how --filter is not applied to the mutant process, I think `--testsuite` should not be applied either.

**Describe alternatives you've considered**

As a workaround, we were able to replace our `--testsuite` option with `--filter="My\Namespace"` as our testsuite in phpunit.xml was only a single path. For users with multiple paths or strange configurations (some directories plus specific files) it will probably be much more difficult.

**Additional context**

**Comment by borNfreee** [comment]
Fixed, https://github.com/infection/infection/commit/6ab4c5dc932f9d73a49a45cde8b9e90bd571247e thanks @tomtomau, very nice bug report
