### ISSUE TITLE
Usage of quoted options in --test-framework-options fails to replace effectively

### ISSUE THREAD

**Issue by tomtomau** [infection/infection#482]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.10.4 (`infection.phar --version`)

Given a case where I use framework options such as:

```
./infection.phar --test-framework-options="--testsuite='Unit Tests'"
```

These test framework options are not effectively replaced with regex, resulting in an invalid call to PHPUnit:

```
#!/usr/bin/env php
Cannot open file "Tests'.php".
```

The behaviour of this regex pattern can be seen here: https://regex101.com/r/oyZgsk/1/

And improved pattern can been here: https://regex101.com/r/HeMqI0/2/

**Comment by borNfreee** [comment]
Fixed https://github.com/infection/infection/pull/483
