### ISSUE TITLE
`--testsuite=unit` no longer working as expected?

### ISSUE THREAD

**Issue by Ocramius** [infection/infection#486]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.10.5
| Test Framework version | 7.3.5
| PHP version | irrelevant
| Platform    | irrelevant
| Github Repo | https://github.com/Ocramius/ProxyManager/

I'm running cronjobs on `ocramius/proxy-manager`, so I detected this issue as a diff between two builds with no source changes on my end:

 * 2018-09-15 15:38:00 https://travis-ci.org/Ocramius/ProxyManager/builds/428981637 - :green_heart: 
 * 2018-09-22 15:39:40 https://travis-ci.org/Ocramius/ProxyManager/builds/431865855 - :broken_heart: 

The green build was running `infection/infection` `0.10.3`, while the failing one was running `0.10.5`.

The dependency is locked to `>=0.10.1,<0.11` as per https://github.com/Ocramius/ProxyManager/blob/a4f3ee3bce026bfc3ebda42bf5ff33eadaec1da3/composer.json#L36

This is the diff between `0.10.3` and `0.10.5`: https://github.com/infection/infection/compare/0.10.3..0.10.5

I don't see a massive difference between the amount of files being covered/mutated: could it be that the options are not correctly passed down to phpunit or infection?

This is what is used to run the tool:

```sh
./vendor/bin/infection -vvv --test-framework-options='--testsuite=unit' --min-msi=99 --min-covered-msi=100
```

**Comment by sanmai** [comment]
I guess #480 is somehow related.

**Comment by Ocramius** [comment]
So the previous version wouldn't consider it escaped because of the no tests warning?

**Comment by sidz** [comment]
@Ocramius yes.

How it works:
https://github.com/infection/infection/blob/c77dbe8da2bdea64ae761c94fe7962abeca04362/src/Process/MutantProcess.php#L86-L105

https://github.com/infection/infection/blob/32a399d214e384feaed79775ce460b9ada6da952/src/TestFramework/PhpUnit/Adapter/PhpUnitAdapter.php#L22-L42

**Comment by Ocramius** [comment]
Got it, so on my end I'll have to bump to `^0.10.5` and fix the actual mutants :-)

Thanks for the quick feedback!
