### ISSUE TITLE
Add a configuration step to enable identical/equal mutators if needed

### ISSUE THREAD

**Issue by sanmai** [infection/infection#489]
Since it appears that the majority of open source projects that use Infection are also fancy strict comparisons, like we do since #398, identical mutators from #298 are not very useful for the majority, and likely to offend or turn away users from Infection. Which isn't a good thing, to be honest.

On the other hand, those identical mutators, and mutators from #391 are quite useful for projects which do not explicitly follow the strict-comparisons-only rule. In my mind we should not throw them away outright.

Therefore, a two-step plan is proposed:

- [x] Review and merge #391 that removes those annoying identical mutator from the default profile, which I took liberty to reopen. Sure, an E2E test case for identical mutators [should be amended to re-enable the mutators in subject](https://github.com/infection/infection/blob/master/tests/Fixtures/e2e/Identical_Mutator_Example/infection.json).
- [ ] Add an initial configuration step in which we would ask, or otherwise guess, if project authors follow the strict-comparisons-only rule or not, automatically enabling additional mutators if not.

This way the majority of our vocal users won't be annoyed anymore more than needed, and minority in need would still be able to continue to test their projects to the fullest.

**Comment by theofidry** [comment]
Since we can now easily enable/disable mutators I guess we can close this one? There might be some ways to improve the discovery of other mutators, but I feel this is a whole different topic

**Comment by sanmai** [comment]
It was possible to disable/enable mutators at the time of this PR, it is more about configuration. But since `===` -> `==` is deprecated, and it being responsible for the half of this proposal, this PR can be shelved for time being.
