### ISSUE TITLE
Function call unwrapping mutators

### ISSUE THREAD

**Issue by sanmai** [infection/infection#490]
[A fine example from our Slack channel](https://symfony-devs.slack.com/archives/C78M7A4BY/p1537651009000100) by @borNfreee:

```diff
- $lowercasedStrings = array_map(['L', 'O', 'L'], function ($v) {
-    return strtolower($v);
- });
+ $lowercasedStrings = ['L', 'O', 'L'];
```
And just as such for `array_filter`. There could be more similar mutators which all will be looking like:

```diff
- $output = standardFunction($input, $foo, $bar);
+ $output = $input;
```

**Comment by borNfreee** [comment]
I would create separate issues for `array_map` and `array_filter` example, because

* In this case, we can mark them with `Hacktoberfest` label
* it will be easier to develop and review for newcomers (I hope from Hacktoberfest)
* it's not immediately clear what is in common between `array_map`+`array_filter` on the one side, and other functions that can be unwrapped on the other side.

what do you think?

**Comment by sanmai** [comment]
I think it may not worth separating these mutations into two as they're quite similar to what you've done with RoundingFamily. Keep first argument, drop others. Only function name differs.

**Comment by deleugpn** [comment]
If nobody else do it, I'm going to give this a try this week.

**Comment by meetthosar** [comment]
Do we have to use array_map  and array_filter functions only?

**Comment by borNfreee** [comment]
> Do we have to use array_map and array_filter functions only?

In this issue - let's stick to those functions only to make it simple.
But I believe there are many other functions that can be "unwrapped" in this way.

For example:

* [`array_flip()`](http://php.net/manual/ru/function.array-flip.php)
* [`array_reverse()`](http://php.net/manual/ru/function.array-reverse.php)
* [`array_replace()`](http://php.net/manual/ru/function.array-replace.php)
* all `*sort()` functions (not sure about it)

and so on.

The only one thing I would like to have is the base class for all these mutators. Thus, we need to wait untill the first one is implemented.

Pseudocode (just an idea, no need to treet it as a rule):

```php
abstract class UnwrapMutator extends Mutator
{
    abstract protected function getParameterIndexToUnwrap(): int;

    // logic of mutator
}

UnwrapArrayFilter extends UnwrapMutator
{
    protected function getParameterIndexToUnwrap()
    {
        // 1 because `array_filter ( array $array [, callable $callback [, int $flag = 0 ]] )`
        return 1;
    }
}

UnwrapArrayMap extends UnwrapMutator
{
    protected fuctoin getParameterIndexToUnwrap()
    {
        // 2 because `array_map ( callable $callback , array $array1 [, array $... ] )`
        return 2;
    }
}
```
