### ISSUE TITLE
Travis failures on PHPDBG and PHP 7.2

### ISSUE THREAD

**Issue by borNfreee** [infection/infection#503]
This is a weird issue that I don't think I can understand myself.
From the Travis log, it appears it started failing after https://github.com/infection/infection/commit/4f364b814a5187966a71c168fb685a035ef8cf21, but I tried to restart successful builds before this commit and all of them now failing as well.

#### Example of failing build

https://travis-ci.org/infection/infection/jobs/440835337#L1044-L1062

#### What causes the failure

e2e test `Phpunit_Bat_Wrapper`

#### Why?

Ok, that's interesting. I started debugging by running `make test-e2e-phpdbg-72` - but this works without any errors. Then I ssh'd to the Travis build (using [Travis debug mode](https://docs.travis-ci.com/user/running-build-in-debug-mode/)) and found the following:

Initial Run command line:

`/home/travis/.phpenv/versions/7.2.11/bin/phpdbg -qrr /home/travis/.phpenv/versions/7.2.11/bin/phpunit --configuration /home/travis/build/infection/infection/tests/Fixtures/e2e/Phpunit_Bat_Wrapper/./infection/phpunitConfiguration.initial.infection.xml --stop-on-failure`

Note which PHPUnit Infection tries to run, it is: `/home/travis/.phpenv/versions/7.2.11/bin/phpunit `. What the heck?

When I ran this command, I got:

```
notice
[PHP Notice:  Undefined index: _SERVER in /home/travis/.phpenv/versions/7.2.11/bin/phpunit on line 18]
```

Version:

```
/home/travis/.phpenv/versions/7.2.11/bin/phpunit --version
PHPUnit 7.4.0 by Sebastian Bergmann and contributors.
```

What I understand is that Infection runs incorrect PHPUnit. Instead of running `phpunit.bat` wrapper (this is actually why this e2e test exists), it is running Travis' global PHPUnit.

Questions that I don't know answers for:

* how did it work before?
* how can Infection find `./phpunit.bat` at all?

**Comment by sanmai** [comment]
The thing is TestFrameworkFinder is looking for a `phpunit` executable, and it is customary *not* to have it installed globally, that test passed fine before. 

https://github.com/infection/infection/blob/ef45b8e6f6eec00821b385ba670a4ca95c2a9d20/src/Finder/TestFrameworkFinder.php#L110-L125

Now it appears that Travis CI decided to add a globally installed `phpunit` binary (not `.phar`) and the test started to find that globally installed phpunit binary first.

**Comment by sanmai** [comment]
About second point, that's not the problem with the change, just `TestFrameworkFinder` can't run on a Mac.

**Comment by borNfreee** [comment]
1 and 3 look like workarounds, so probably 2 is the right way to go
