### ISSUE TITLE
New @unwrap mutators ideas

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#514]
After merging https://github.com/infection/infection/pull/513, it's very easy to create new mutators that unwrap parameter from function. Let's keep the list of desired mutators and discuss them here.

- [x] `array_chunk()` https://github.com/infection/infection/pull/558
- [x] `array_column()` https://github.com/infection/infection/pull/590
- [x] `array_combine` https://github.com/infection/infection/pull/550
- [x] `array_flip()` https://github.com/infection/infection/pull/529
- [x] `array_diff($a, $b);` -> `$a;` https://github.com/infection/infection/pull/544
- [x] `array_diff_assoc` https://github.com/infection/infection/pull/562
- [x] `array_diff_uassoc` https://github.com/infection/infection/pull/568
- [x] `array_diff_key` https://github.com/infection/infection/pull/563
- [x] `array_diff_ukey` https://github.com/infection/infection/pull/583
- [x] `array_pad` https://github.com/infection/infection/pull/680
- [x] `array_reverse()` https://github.com/infection/infection/pull/527
- [x]  `array_replace()` https://github.com/infection/infection/pull/536
- [x]  `array_reduce($array, $func, $initial)` -> `$initial` https://github.com/infection/infection/pull/533
- [x] `array_merge($a, $b, $c);` -> `$a;`, `$b;`, `$c` https://github.com/infection/infection/pull/542
- [x] `array_merge_recursive($a, $b, $c);` -> `$a;`, `$b;`, `$c` https://github.com/infection/infection/pull/594
- [x] `array_replace_recursive()` https://github.com/infection/infection/pull/545
- [x] `array_slice()` https://github.com/infection/infection/pull/598
- [x] `array_splice()` https://github.com/infection/infection/pull/605
- [x] `array_intersect($a, $b, $c);` -> `$a;`, `$b;`, `$c` https://github.com/infection/infection/pull/543
- [x] `array_intersect_assoc()` https://github.com/infection/infection/pull/679 
- [x] `array_intersect_key($a, $b, $c);` -> `$a;`, `$b;`, `$c` 
https://github.com/infection/infection/pull/584
- [x] `array_intersect_ukey($a, $b, $c);` -> `$a;`, `$b;`, `$c` 
https://github.com/infection/infection/pull/593
- [x] `array_intersect_uassoc()` https://github.com/infection/infection/pull/591
- [x] `array_keys` https://github.com/infection/infection/pull/555
- [x] `array_udiff` https://github.com/infection/infection/pull/624
- [x] `array_udiff_assoc` https://github.com/infection/infection/pull/614
- [x] `array_udiff_uassoc` https://github.com/infection/infection/pull/623
- [x] `array_uintersect` https://github.com/infection/infection/pull/637
- [x] `array_uintersect_assoc` https://github.com/infection/infection/pull/628
- [x] `array_uintersect_uassoc` https://github.com/infection/infection/pull/633
- [x] `array_unique` https://github.com/infection/infection/pull/556
- [x] `array_values()` https://github.com/infection/infection/pull/554
- [x] `lcfirst()` https://github.com/infection/infection/pull/643
- [x] `ltrim()` https://github.com/infection/infection/pull/1395
- [x] `rtrim` https://github.com/infection/infection/pull/1396
- [x] `str_ireplace()` https://github.com/infection/infection/pull/1397
- [x]  `str_replace()` https://github.com/infection/infection/pull/831
- [x] `str_shuffle()` https://github.com/infection/infection/pull/1398
- [x] `strrev()` https://github.com/infection/infection/pull/1399
- [x]  `strtolower()` https://github.com/infection/infection/pull/534
- [x]  `strtoupper()` https://github.com/infection/infection/pull/559
- [x] `substr()` https://github.com/infection/infection/pull/1400
- [x] `trim()` https://github.com/infection/infection/pull/638
- [x]  `ucfirst()` https://github.com/infection/infection/pull/635
- [x]  `ucwords()` https://github.com/infection/infection/pull/645
- [ ]  ...

**Comment by ntzm** [comment]
Some ideas for string unwrap mutators:

- `ltrim`
- `rtrim` + `chop`
- `nl2br`
- `str_ireplace`
- `str_shuffle`
- `strrev`
- `substr`
- `substr_replace`
- `addslashes`
- `stripslashes`
- `addcslashes`
- `stripcslashes`
- `strip_tags`
- `quotemeta`
- `htmlentities`
- `html_entity_decode`
- `htmlspecialchars`
- `htmlspecialchars_decode`
- `wordwrap`

**Comment by maks-rafalko** [comment]
let's close, all new mutators/ideas can be opened as new issue/RFC to discuss
