### ISSUE TITLE
can't find how to skip a mutator

### ISSUE THREAD

**Issue by marcelloh** [infection/infection#518]
So, after some puzzling, I've got this:
```
"mutators": {
        "Throw_": {
            "ignore": [
                "**::*"
            ]
        }
    }
```
but this will skip all mutators, so it must be wrong. Ilooked everywhere in the docs, but I didn't see it. (Perhaps I've look wrong)

Can you post some examples in how this ignoring should work?

**Comment by sanmai** [comment]
Like here: 

https://github.com/sanmai/cdek-sdk/blob/master/infection.json.dist

**Comment by marcelloh** [comment]
Unclear for me, because it doesn't say what @default does, or @cast
(this seems not documented)

So I try
```
"mutators": {
        "@default": true,
        "Throw_": false
    }
```
Which seems to do the trick.

**Comment by marcelloh** [comment]
Ok, super. Must have mistunderstood what they did :-)
Thanks for your patience.

**Comment by ls-chloe-schoreisz** [comment]
Would it be possible to update the documentation, and specify that mutators can be muted everywhere by just doing `'{mutationName}': false` ?

**Comment by borNfreee** [comment]
Sure, will do. Thank you

**Comment by borNfreee** [comment]
> Would it be possible to update the documentation, and specify that mutators can be muted everywhere by just doing `'{mutationName}': false` ?

Please, read the new article in our documentation: https://infection.github.io/guide/how-to.html#How-to-disable-Mutators-and-profiles
