### ISSUE TITLE
boolean mutators and array_search, in_array, is_subclass_of, is_a

### ISSUE THREAD

**Issue by kalessil** [infection/infection#578]
| Question    | Answer
| ------------| ---------------
| Infection version | latest
| Test Framework version | PHPUnit latest
| PHP version | 7.2
| Platform    | Ubuntu
| Github Repo | -

The booleans mutator (true => false, false => true) should skip some of PHP core function:
- array_search
- in_array
- is_subclass_of
- is_a

The optional parameters there are intended for hardening workflows, and writing tests for those cases are normally is overkill.

**Comment by borNfreee** [comment]
Thanks @kalessil. I agree with this proposal. Let's implement it for the next release ;)

Also, this is related to https://github.com/infection/infection/issues/206

**Comment by kalessil** [comment]
Super, thank you @borNfreee !

**Comment by kalessil** [comment]
Super, thank you @borNfreee !

**Comment by borNfreee** [comment]
No problem ;) Will be released soon, I hope this week. 

Thanks for pushing it forward
