### ISSUE TITLE
Running command with --only-covered should add in log only covered code.

### ISSUE THREAD

**Issue by gmponos** [infection/infection#581]
When I run the command like this:

```
php vendor/bin/infection --threads=8 --min-covered-msi=90 --only-covered --log-verbosity=default
```

I would expect that `infection.log` will contain only the Mutators for the covered code.. but it does contain code from the non covered code.

**Comment by borNfreee** [comment]
If you mean we should skip the whole

```
Not Covered mutants:
====================
```

section than I totally agree. PR is welcome!
