### ISSUE TITLE
symfony/phpunit-bridge isn't supported

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#588]
**Is your feature request related to a problem? Please describe.**
A lot of symfony projects use the `symfony/phpunit-bridge` package instead of phpunit directly. This exposes `simple-phpunit` instead of `phpunit` as an executable in `vendor/bin`. When adding infection to a project it doesn't detect the correct executable during the config generation step.

**Describe the solution you'd like**
This is a common enough use case that we should either detect this during runtime, or help the user with a guesser during the initial set up.

**Comment by borNfreee** [comment]
Also see https://github.com/infection/infection/issues/493
