### ISSUE TITLE
infection own tests are failing on windows

### ISSUE THREAD

**Issue by siad007** [infection/infection#596]
| Question    | Answer
| ------------| ---------------
| Infection version | dev-master (`infection.phar --version`)
| Test Framework version | PHPUnit 6.5.13
| PHP version | 7.1.8 (`php -v`)
| Platform    | Windows / cygwin or cmd.exe
| Github Repo | -

Executed with cygwin
```
There was 1 failure:

1)
         Infection\Tests\Console\E2ETest::test_it_runs_an_e2e_test_with_success
         with data set "Code_Coverage_Ignore"
         (Symfony\Component\Finder\SplFileInfo Object
         (...))
C:\Users\xxx\GITRepos\infection\tests\Fixtures\e2e\Code_Covera
         ge_Ignore/expected-output.txt is not same as infection.log (if that is
         OK, run GOLDEN=1 vendor/bin/phpunit)
Failed asserting that two strings
         are equal.
--- Expected
+++ Actual
@@ @@
-'Total: 1\r\n
-Killed:
         0\r\n
-Errored: 0\r\n
-Escaped: 0\r\n
-Timed Out: 0\r\n
+'Total:
         1\n
+Killed: 0\n
+Errored: 0\n
+Escaped: 0\n
+Timed Out:
         0\n

```
When executed with `cmd.exe`
```
There was 1 failure:

1) Infection\Tests\Config\ValueProvider\TestFrameworkConfigPathProviderTest::test_it_asks_question_if_no_config_is_found_in_current_dir
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'C:\Users\said\GITRepos\infection\tests\Fixtures\Files\phpunit'
+''

C:\Users\said\GITRepos\infection\tests\Config\ValueProvider\TestFrameworkConfigPathProviderTest.php:119

--
```

**Comment by sanmai** [comment]
Are you sure you haven't edited that file?

I see only normal line endings:
```
$ cat -ev tests/Fixtures/e2e/Code_Coverage_Ignore/expected-output.txt 
Total: 1$
Killed: 0$
Errored: 0$
Escaped: 0$
Timed Out: 0$
```
Compare with this example where `\r` is visible:

```
$ echo -e 'abc\ndef\r\n' | cat -ev
abc$
def^M$
$
```

**Comment by sanmai** [comment]
Oh right. The test wants to see `\r\n` where actually there are only `\n`s. Workaround is easy, but I'm not sure that's going to be the right solution.

Thanks for the report.

**Comment by siad007** [comment]
> 
> 
> Oh right. The test wants to see `\r\n` where actually there are only `\n`s. Workaround is easy, but I'm not sure that's going to be the right solution.
> 
> Thanks for the report.

But it is also wired, that there are two different results using either cygwin or cmd.exe

**Comment by borNfreee** [comment]
Is it still the issue @siad007 ?

**Comment by borNfreee** [comment]
Closing since tests pass on AppVeyor
