### ISSUE TITLE
Schema does not include initialTestsPhpOptions

### ISSUE THREAD

**Issue by nesl247** [infection/infection#606]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.11.4
| Test Framework version | PHPUnit 7.5.1
| PHP version | 7.2.13
| Platform    | Docker
| Github Repo | -

The schema in https://github.com/infection/infection/blob/64c474fcd2017663383a08edf05e123bf31988dc/resources/schema.json does not include `initialTestsPhpOptions` even though https://infection.github.io/guide/usage.html shows it in an example config.

<details>
 <summary>Output with issue</summary>
 
 ```
 In JsonValidationException.php line 51:

                                                                               

  "/application/infection.json.dist" does not match the expected JSON schema:  

   - The property initialTestsPhpOptions is not defined and the definition do  

  es not allow additional properties              
 ```
</details>

**Comment by sidz** [comment]
as well as `testFrameworkOptions`

**Comment by sidz** [comment]
Fixed. and release in 0.11.5
