### ISSUE TITLE
Provide compact output for CI environments

### ISSUE THREAD

**Issue by lcobucci** [infection/infection#613]
**Is your feature request related to a problem? Please describe.**
The amount of text generated by the initial processes (running tests, generating mutations) is quite big, specially when running it on medium to large projects. This is basically due to the progress bars that are being used and that, for CI environments without proper ANSI support, is quite irrelevant.

**Example:**
![image](https://user-images.githubusercontent.com/201963/51386791-00573a80-1b24-11e9-829e-e10392a4118e.png)

**Describe the solution you'd like**
It would be nice if could have a flag to omit the progress bars of these listeners:

* `InitialTestsConsoleLoggerSubscriber`
* `MutantCreatingConsoleLoggerSubscriber`
* `MutationGeneratingConsoleLoggerSubscriber`

**Describe alternatives you've considered**
Another option is to use something like the `DotFormatter` instead of the progress bars.

**Comment by borNfreee** [comment]
Implemented and released as 0.12.2.

Enjoy ;)
