### ISSUE TITLE
Error when parsing method that creates anonymous class

### ISSUE THREAD

**Issue by remorhaz** [infection/infection#616]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.11.5 (`infection.phar --version`)
| Test Framework version | PHPUnit 7.5.2
| PHP version | 7.1.27 (`php -v`)
| Platform    | Linux
| Github Repo | -

Infection reports an error if the following code occurs in source folder:
```php
namespace My\Namespace;

class Bug
{

    public function createAnonymousClass()
    {
        new class
        {
            public function foo()
            {
            }
        };
    }
}
```
The error is:
```
In CodeCoverageMethodIgnoreVisitor.php line 56:

  Method foo does not exist
```
Seems that code seeks method in host class instead of anonymous one, because if I add `private function foo() {}` to `Bug` class, the error dissapears.
I don't know either bug is in PHP-Parser or in Infection, but it affects your software anyway.

**Comment by BackEndTea** [comment]
I think we have some tests on dealing with anonymous classes, but maybe not for the `CodeCoverageMethodIgnoreVisitor`.
