### ISSUE TITLE
BADSIG for infection 0.12.0 phar release

### ISSUE THREAD

**Issue by theseer** [infection/infection#619]
Looks like the gpg signature is b0rked for 0.12.0. Installing 0.11.5 works like charm.

```
theseer@nyda /tmp/xy $ phive install infection@0.12.0
Phive 0.12.1-7-g6b5b887-dirty - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/infection/infection/releases
Downloading https://github.com/infection/infection/releases/download/0.12.0/infection.phar
Downloading https://github.com/infection/infection/releases/download/0.12.0/infection.phar.asc
[ERROR]   Signature could not be verified
```

Debug detail output:
```
"[GNUPG:] BADSIG C5095986493B4AA0 Infection PHP <maks.rafalko@gmail.com>"
```

**Comment by borNfreee** [comment]
I have redeployed both files, rerunning the Travis deploy script.

```bash
gpg --with-fingerprint --verify infection.phar.asc infection.phar
gpg: Signature made Tue Jan 29 07:24:19 2019 +03
gpg:                using RSA key C5095986493B4AA0
gpg: Good signature from "Infection PHP <maks.rafalko@gmail.com>" [ultimate]
Primary key fingerprint: C6D7 6C32 9EBA DE2F B9C4  58CF C509 5986 493B 4AA0
```

Is it ok now?

**Comment by tommy-muehle** [comment]
@borNfreee 
Works now for me.

**Comment by borNfreee** [comment]
Thanks

**Comment by theseer** [comment]
Can confirm.
Thanks for the quick reaction!

Out of curiosity: Any idea what might have caused this?

**Comment by borNfreee** [comment]
This is a very good question.

I have created a release (0.12.0) and travis had to deploy `.phar` and `.asc` automatically, thanks to our deploy stage

https://github.com/infection/infection/blob/8a4d0fbf8de0dca0e590ad590a0052154fd7ca56/.travis.yml#L137-L147

However, it failed with such error "Please upload the file again" and the file was in red in Github UI (I'm not sure what does it mean, probably corrupted file).

So I have removed `.phar` file and redeployed again (only `.phar` but not the `.asc`). 
Before the first deployment and the second - there were no commits, so I'm not sure what has happened.
