### ISSUE TITLE
Do not mutate function signature of inherited methods

### ISSUE THREAD

**Issue by borNfreee** [infection/infection#63]
There is no need to mutate `public` to `protected` for methods from the implemented interface.

```php
interface Doable
{
    public function do(): void;
}

class Foo implements Doable
{
    public function do(): void {}
}
```

Incorrect mutation:

```diff
class Foo implements Doable
{
-    public function do(): void {}
+    protected function do(): void {}
}
```

Expected result: *no mutation*, because it always leads to `Fatal error: Access level to Foo::do() must be public (as in class Doable)...`

------

At this point, we don't have information about parent classes/interfaces. It requires implementing a new smart feature with native reflection or BetterReflection.

**Comment by theofidry** [comment]
I common issue with mutation testing is redundant/useless mutants. We can apply a load of dumb mutants, but the less relevant they are the more of a waste of time (as more mutants means longer run time).

That said if I were you I wouldn't focus on performance first: I can help with that and I have some plans for it, I would focus first on usability, having something easy to work with and to debug

**Comment by borNfreee** [comment]
> I would focus first on usability

Do you mean that such issue like this one (removing useless mutants) should be the first priority? If so, I agree, because currently with ~940 mutations on infection itself this particular mutator creates 134 (which is 15%) useless mutants that are immediately killed because of a Fatal Error.

Feel free to open another usability issues you are aware about.

> I can help with that and I have some plans for it

Sorry, you can help with what, performance or usability? Didn't get it. Anyway, any help from you would be very useful 👍  😸

**Comment by theofidry** [comment]
>Sorry, you can help with what, performance or usability?

Actually I'm a bit confusing as performance does count in usability: if a tool is too slow it's less usable right?

So I mean what should be the main focus first is getting things right: the mutants, the mutant strategy, framework integration, debuggability (worst situation: tests pass with the test framework, they don't with the mutation testing framework and impossible to know what's going on without digging horribly deep in the internals).

Getting fast enough is later when the above has been pinned down right.

>Anyway, any help from you would be very useful 👍 😸

Worry not I've meant to sent you an email with some plans for quite a while now, I just really need to get the alice packages out (as get the stable release) first to have enough free time for that :)
