### ISSUE TITLE
Multi line arrays are not properly handled by code coverage

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#652]
**Is your feature request related to a problem? Please describe.**
With #649, we will see a lot more mutations of arrays. And multi-line arrays aren't properly handled
by code coverage, as seen in #214. 

**Describe the solution you'd like**
This is gonna be a bit difficult, as PHPDBG and Xdebug both take a different approach on array coverage. But the best solution (i think) would be to check if either the first item, or the opening bracket is considered covered, and then use that for the rest of the array as well.

**Describe alternatives you've considered**
As it stands, #649 will cause a lot of un-killable mutations, which is something we'd like to avoid.

**Comment by sanmai** [comment]
I've seen [a similar issue reported on our Slack channel](https://symfony-devs.slack.com/messages/C78M7A4BY/convo/C78M7A4BY-1551266524.011200/?thread_ts=1551266524.011200).
