### ISSUE TITLE
PHP Fatal error:  Cannot declare class XXX  because the name is already in use in YYY  

### ISSUE THREAD

**Issue by Tony4Sosa** [infection/infection#681]
You are running Infection with Xdebug enabled.
Running initial test suite...
`
PHPUnit version: 6.5.14

    0 [>---------------------------] < 1 sec
    1 [->--------------------------]  1 sec
    2 [-->-------------------------]  1 sec
    3 [--->------------------------] 9 secs
 [ERROR] Project tests must be in a passing state before running Infection.     
                                                                                
         Check the executed command to identify the problem: '/root/phpunit'    
         '--configuration'                                                      
         '/tmp/infection/phpunitConfiguration.initial.infection.xml'            
                                                                                
         PHPUnit reported an exit code of 143.                                  
                                                                                
         Refer to the PHPUnit's output below:                                   
                                                                                
         STDOUT:                                                                
                                                                                
         PHPUnit 6.5.14 by Sebastian Bergmann and contributors.                 
                                                                                
         Runtime:       PHP 7.2.14-1+0~20190205200722.15+jessie~1.gbpd83c69 with
         Xdebug 2.6.1                                                           
         Configuration:                                                         
         /tmp/infection/phpunitConfiguration.initial.infection.xml              
                                                                                                                                                   
         STDERR:                                                                
                                                                                
         PHP Fatal error:  Cannot declare class                                 
         Openbee\Tasks\EventListener\TasksEventSubscriber, because the name is  
         already in use in                                                      
         /var/lib/jenkins/workspace/OBPTasksQA/sf3/src/Openbee/Tasks/EventListen
         er/TasksEventSubscriber.php on line 5                                  
         PHP Stack trace: `

*infection version* : 0.12.1
*php version* : 7.2.14
*symfony version* : 3.0

**Comment by sanmai** [comment]
Do you think you can share an example project reproducing the issue?

**Comment by maks-rafalko** [comment]
ping @Tony4Sosa

**Comment by Tony4Sosa** [comment]
@sanmai thanks but i fixed, the problem related to class autoload test class i just change `require` by `require_once`. like this  [https://github.com/sebastianbergmann/phpunit/issues/2789](url)
