### ISSUE TITLE
Error about missing phar pubkey file on self-update

### ISSUE THREAD

**Issue by PeeHaa** [infection/infection#684]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.12.2 (https://github.com/infection/infection/releases/download/0.12.2/infection.phar)
| Test Framework version | N/A
| PHP version | 7.3
| Platform    | Ubuntu 14.04.5 LTS
| Github Repo | https://github.com/HarmonyIO/Cache

When following the steps to run infection on travis and doing an update of the phar afterwards I get an error about the missing pubkey file. Looking through past issues it *might* be related to the discussion [here](https://github.com/infection/infection/issues/134)?

Looking at past releases the pubkey file was dropped as of 0.10.0 (2018-08-11).

I am running the following commands on travis:

```shell
wget https://github.com/infection/infection/releases/download/0.12.2/infection.phar
wget https://github.com/infection/infection/releases/download/0.12.2/infection.phar.asc
gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 493B4AA0
gpg --with-fingerprint --verify infection.phar.asc infection.phar
chmod +x infection.phar
./infection.phar self-update
```

And I get the following result (based on the execution of the `./infection.phar self-update` command):

```shell
     ____      ____          __  _
    /  _/___  / __/__  _____/ /_(_)___  ____
    / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
  _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
 /___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/
In Updater.php line 335:
                                                                               
  The phar pubkey file does not exist: /home/travis/build/HarmonyIO/Cache/inf  
  ection.phar.pubkey.                                                          
                                                                               
self-update [-p|--pre] [-s|--stable] [-r|--rollback] [-c|--check]
The command "./infection.phar self-update" failed and exited with 1 during .
```

Link to travis build: https://travis-ci.org/HarmonyIO/Cache/jobs/525863163

**Comment by BackEndTea** [comment]
This is an issue with the self-update command, it looks like that still expects a pubkey.

I'm gonna ping @theofidry, since i think he knows most about this command/ the humbug implementation.

But from what i can see by quickly looking at the implementation, it doesn't look like it actually supports using `.asc` files etc.

**Comment by theofidry** [comment]
I think the self-command & package are a bit flawed and shouldn't be used until revamped & reviewed with a security audit. So meanwhile I'm all for #688

**Comment by sanmai** [comment]
If you do like this:

```
gpg --export -a 493B4AA0 > infection.phar.pubkey
./infection.phar self-update
```

Will that work?
