### ISSUE TITLE
Allow percent numbers with decimals in --min-msi and --min-covered-msi

### ISSUE THREAD

**Issue by arudolph-cxt** [infection/infection#694]
**Is your feature request related to a problem? Please describe.**
We calculate the MSI and mutation coverage manually from the summary log and store the values with 2 decimals. When we add those values to the ci command-line script like so: `... --min-msi=15.77` it fails:
`[ERROR] The minimum required MSI percentage should be 15.77%, but actual is 15%. Improve your tests!`
Although the actual percentage should be compared with 15.77424023154848% to be exact and therefore pass.

**Describe the solution you'd like**
The comparison should use float values instead of rounded-down integers to decide if the ci fails.

**Describe alternatives you've considered**
Rounding down the value to an int, with the drawback of having much less accuracy on bigger projects.

**Comment by arudolph-cxt** [comment]
According to the code, the flooring seems to be deliberate:
https://github.com/infection/infection/blob/7894cf5f6030c3c499004d57f7a29db52aeb2af8/src/Mutant/MetricsCalculator.php#L161
Is there a reason for this? Since the values seem to be available as floats, this looks as simple as removing the floor call and ensuring the values are calculated as float and not auto-casted into integer values.
Unless i'm missing something and there was a good reason for this?

This commit seems to be the last change https://github.com/infection/infection/commit/b2a7a2d50d2be36c963abd88298ddef67ee0adb9 and i understand why the change from `round` to `floor` was done, but why there was actual rounding in the first place seems confusing to me.

**Comment by borNfreee** [comment]
Personally, I don't remember any reasons for rounding.

**Comment by arudolph-cxt** [comment]
I'm currently working on one and as expected, two tests fail as they compare against rounded values.

My current approach would be to just use float values instead, a more nuanced approach would be to allow control over the accuracy/decimal amount maybe with a parameter.
I think I can provide a PR shortly.
