### ISSUE TITLE
Ignore files with codeCoverageIgnore annotation

### ISSUE THREAD

**Issue by gmponos** [infection/infection#696]
My suggestion is to ignore files with codeCoverageIgnore annotation when the --min-covered-msi is set.

Otherwise I have to always maintain two places. One with the exclude list in the JSON and with the annotations.

**Comment by borNfreee** [comment]
Hello @gmponos. Could you please explain with more details what do you mean by "ignore files with codeCoverageIgnore annotation"? Do you mean to exclude them from MSI report? Would be nice to have concrete examples. 

Thank you.

https://infection.github.io/guide/usage.html#codeCoverageIgnore-support

**Comment by maks-rafalko** [comment]
ping @gmponos

**Comment by gmponos** [comment]
closing.. Sorry I am not sure how I got confused.. I think I have noticed in some logs that the files were not excluded but re-checking now to provide more info I could not track it back.

**Comment by maks-rafalko** [comment]
Thank you @gmponos, no problem :)
