### ISSUE TITLE
Allow adding mutation exclusions for specific calls

### ISSUE THREAD

**Issue by NGTOne** [infection/infection#697]
**Is your feature request related to a problem? Please describe.**
It's often the case that production codebases include support/monitoring/logging code that, if mutated, has little-to-no impact (or, alternatively, isn't worth testing the result of - e.g. calls to a logging function). If your codebase has lots of logging, this can generate large numbers of needless false positives and greatly slow down the mutation test run.

**Describe the solution you'd like**
Perhaps an addition to the `mutators` element in `infection.json`, along the lines of:
```json
{
    "mutators": {
        "ArrayItem": {
            "excludeCallsTo": [
                "Namespace\\Class::writeToLog",
                "OtherNamespace\\SomeOtherClass"
            ]
        }
    }
}
```

Obviously this wouldn't necessarily be 100% given PHP's extremely loose ways of calling functions (for instance, it might not catch something like `$level = "info"; Log::$level(...)`), but it would still save a lot of false positives over code like this.

**Describe alternatives you've considered**
Excluding every single log line, line-by-line, using the existing exclusion syntax. Doesn't scale well at all, and extremely brittle.

**Comment by BackEndTea** [comment]
I'm assuming this would mostly be for the `FunctionCallRemoval` and `MethodCallRemoval` mutators?

I'd be okay with adding a filter, which works along the lines of how `ignore` currently works for excluding mutation of certain classes/namespaces/methods. e.g. use the [`fnmatch`](https://www.php.net/manual/en/function.fnmatch.php) syntax. (As that is used under the hood). We regex could also be an option, but i feel `fnmatch` is simpler, and good enough for what it is going to do.

**Comment by NGTOne** [comment]
@BackEndTea I'm thinking a _bit_ more general - for instance, my use case also includes `ArrayElement` and `RemoveArrayElement` (our log lines are given a "context" array, to keep them easily `grep`able), both of which fall into the "it doesn't really affect anything if this breaks" category. And, even though I don't do it myself, I can imagine something like array-to-object casts falling into that bucket as well.

**Comment by sanmai** [comment]
Infection itself would have used this for `Assert::` calls, I think.

And, yes, right now this can be done only on per-mutator basis, and not to say this is bad. Just a limitation.

**Comment by theofidry** [comment]
@sanmai from what I understood, this appears to only work to ignore namespaces, classes or methods: not peculiar lines

**Comment by sanmai** [comment]
As I see it OP mentions calls to logging functions they don't want Infection to alter/remove, not whole namespaces or classes. [We can do that already IIRC. ](https://infection.github.io/guide/how-to.html#Disable-in-particular-class-or-method-or-line)

**Comment by theofidry** [comment]
Nevermind: you can ignore a specific line indeed, but not an expression on a method body (which is what we need to really ignore say logger or assert calls)

**Comment by LoopKarma** [comment]
in my projects I'm facing same problems: I have a trait with `Logger` inside and in results I have a lot of `ArrayItemRemoval` applied to log context. It's not actually adding any value and it's not easy to avoid such mutations because namespace will be different for every class with same trait usage.
So the only way to exclude trait calls by defining line number, but this approach creates too much hassle with constant config update. 
Anything you can recommend to improve ignore experience? 

I can think of following:
`ReflectionVisitor` will know about Trait parent node for method node and IgnoreMutator will double check excluded namespace if parent node with type Trait is exist in provided Node.

**Comment by theofidry** [comment]
>Anything you can recommend to improve ignore experience?

Enriching the current ignore feature :) 

I unfortunately cannot thing of much workaround atm except using incremental runs which at least avoids you to have to deal with that noise at every run.

**Comment by maks-rafalko** [comment]
IMO, to resolve such issues like this, we need to know the type of variables (this is what PHPStan / Psalm do in their analyzes).

Knowing the type of a variable, we can exclude/ignore any call easily. For example:

```php
private LoggerInterace $logger;

public function anyMethodWithLogger(): void
{
    // ...

    // here Infection will know that $this->logger is instance of LoggerInterface, so no need to mutate ['user' => $user]
    $this->logger->error($message, ['user' => $user]);
}
```

**Comment by LoopKarma** [comment]
@maks-rafalko I will check functionality of PHPStan and Psalm regarding getting actual namespace of a variable. And infection already has a dependency on PHPStan so maybe it's better to go with phpstan only.

**Comment by sanmai** [comment]
Using annotations to exclude certain parts of the code like proposed in #1231 is much more convenient to the user, while also quite easy to implement. You don't need no functionality of PHPStan and Psalm to do what #1231 proposes.

**Comment by theofidry** [comment]
also regexes would work to a certain extend: definitely not as accurate and smart as leveraging PHPStan or Psalm but for example `/^Assert::\p{L}+\(.+\)$/` eventually constraining to a class/method would be effective

**Comment by LoopKarma** [comment]
@sanmai I agree that it's much easier to implement but not sure it's convenient to user because it's mixing business code with testing tool.

**Comment by ondrejmirtes** [comment]
Hi, it'd be easy to use PHPStan internally here in Infection to figure this stuff out. The basics are:

* Create [ContainerFactory](https://github.com/phpstan/phpstan-src/blob/master/src/DependencyInjection/ContainerFactory.php) instance.
* Create the DIC by calling ContainerFactory::create().
* Get NodeScopeResolver by calling Container::getByType(NodeScopeResolver::class).
* Call NodeScopeResolver::processNodes() with your AST. You'll get callback called for every node.
* Ask `$scope` for any information you'd like. So for example you can ask which type a MethodCall is called on by asking `$scope->getType($node->var)`.

**Comment by Slamdunk** [comment]
> also regexes would work to a certain extend: definitely not as accurate and smart as leveraging PHPStan or Psalm but for example `/^Assert::\p{L}+\(.+\)$/` eventually constraining to a class/method would be effective – I think there is an ideal case we can try to work to but there is several other steps on the ladder than we can climb up first

:+1: for regex

1. easy to implement
1. no new heavy dependency needed
1. effective for most of the cases
1. handling tricky code is up to the user instead of Infection

**Comment by Ocramius** [comment]
I think mutations for `Assert::` and `assert()` are valid, since not all of these `assert()` are harmless (non-functional assertions), but sometimes are used for actual data input validation that needs testing.

The problem with `assert()` specifically is solved by using something like https://github.com/Roave/infection-static-analysis-plugin, while we maybe work on a more precise plugin system :-) 

Logging is also to be tested, IMO, and shouldn't be silently skipped.

**Comment by theofidry** [comment]
IMO it's not that they are not valid, it's that 80% if not more don't want either to focus on it or is not valid for their usage. In other words more than arbitrary deciding to ignore something, this is more about to provide the _ability_ to ignore something

**Comment by Ocramius** [comment]
Certainly OK with allowing to suppress arbitrary patterns in mutators - just think that `assert()` and logging aren't valid use-case scenarios for this, while maybe `stop_debugger_here_if_active();` makes sense :-)

**Comment by Ocramius** [comment]
A potential solution to this (and other similar filtering problems) with potential design is proposed in #1323

**Comment by maks-rafalko** [comment]
here is the draft implementation based on Regexes: https://github.com/infection/infection/pull/1326

@Slamdunk @NGTOne @LoopKarma feel free to test and see if it suits your needs
