### ISSUE TITLE
Ensure the tools used in the Makefile are up to date and leverage caching

### ISSUE THREAD

**Issue by theofidry** [infection/infection#717]
As per https://github.com/infection/infection/pull/706/files#r294505032.

There is two problematics here:

- How to ensure those tools stays up to date
- How to accomplish the above whilst being able to leverage caching in the CI

cf. the linked discussion for more details

**Comment by sanmai** [comment]
[An executable for a tool can depend on the Makefile](https://github.com/infection/infection/pull/706#discussion_r294637509), then if Makefile changes, which includes changes to versions of tools used, all executables will be re-downloaded:
```make
$(PHP_CS_FIXER): Makefile
    # Commands to download
```

**Comment by theofidry** [comment]
Is that good enough? I thought when cloning the Makefile timestamp was
being tempered with which would make the above strategy ineffective

**Comment by BackEndTea** [comment]
We could go with the strategy of dumping a hash of the makefile, and updating that if needed, like we did with the Dockerfiles? (At least that is my understanding of how that works)

**Comment by sanmai** [comment]
We can restore the timestamp before running make.
```bash
$ git log Makefile | head -n 3
commit ...
Author: ...
Date:   2019-06-24 15:20:51 +0200

$ git log -1 --format=%cd Makefile
2019-06-24 16:20:51 +0300
```

Then it is as simple as this:

```
touch -d "$(git log -1 --format=%cd Makefile)" Makefile
```

**Comment by theofidry** [comment]
👌
