### ISSUE TITLE
Feature Request: Add line numbers to diffs on Escaped mutants

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#72]
I'm really liking this project so far, and it should be a big help moving forward with tests for me. However one of the issues i find is that the following diff:
```diff
12) Infection\Mutator\Boolean\FalseValue
/Users/Me/Projects/project/classes/Domain/Model/User.php
exec /usr/local/Cellar/php71/7.1.11_22/bin/php /Users/Me/Projects/project/vendor/phpunit/phpunit/phpunit --configuration /var/folders/5y/g0yc55n12hjcc4zb0k3z2x_m0000gn/T/infection/phpunitConfiguration.dc85538a77301d5b6fb62b5c77d33083.infection.xml --stop-on-failure 
--- Original
+++ New
@@ @@
-                return false;
+                return true;

PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.11 with Xdebug 2.5.5
Configuration: /private/var/folders/5y/g0yc55n12hjcc4zb0k3z2x_m0000gn/T/infection/phpunitConfiguration.dc85538a77301d5b6fb62b5c77d33083.infection.xml

...................                                               19 / 19 (100%)

Time: 4.54 seconds, Memory: 110.00MB

OK (19 tests, 39 assertions)

```
Doesn't give me too much information about what change didn't get caught by tests. Of course it tells me in what file the change happened, but these can have a lot of return ```return false;``` statements.

On mutants that aren't escaped these get displayed normally

**Comment by sidz** [comment]
@BackEndTea We did couple improvements as part of: https://github.com/infection/infection/pull/56
and these changes will be in the next release

**Comment by sidz** [comment]
release as part of the 0.6.2

**Comment by BackEndTea** [comment]
Thanks @sidz
