### ISSUE TITLE
The profile keys are missing in the schema.json

### ISSUE THREAD

**Issue by theofidry** [infection/infection#732]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.13.3
| Test Framework version | -
| PHP version | -
| Platform    | -
| Github Repo | -

We are defining the allowed schema for the `infection.json.dist` in the `resources/schema.json` file. I however fail to see _any_ profile keys listed [in the doc](https://infection.github.io/guide/profiles.html) in that schema file.

Is that expected?

**Comment by maks-rafalko** [comment]
https://github.com/infection/infection/pull/524

> Also I didn't add validation for the mutators profiles and particular classes. For case like:

But I think we can (and should) add it, at least I see no reason why not.

**Comment by theofidry** [comment]
I see thanks, will take a look at it. My main focus for the next weeks
should be the configuration :)

**Comment by maks-rafalko** [comment]
Implemented
