### ISSUE TITLE
Infection should fail faster when wrong mutator/profile is used

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#734]
Currently, if you have a typo in the mutator or profile name, Infection try to run initial test suite and only then validate `--mutators` option.

Example:

![1  ssh 2019-07-01 22-55-04](https://user-images.githubusercontent.com/3725595/60462971-5db6f200-9c53-11e9-83a9-1c10e30ad19c.png)

Note 3 minutes delay before user gets an exception.

We need to validate `--mutators` option as soon as possible, before Initial Test Suite step.

**Comment by theofidry** [comment]
Working on that with the rework of the config in general

**Comment by BackEndTea** [comment]
This was fixed in #875
