### ISSUE TITLE
Remove all inherit doc blocks

### ISSUE THREAD

**Issue by theofidry** [infection/infection#749]
Since we are not using any tool to generate doc, having the:

```php
/**
 * {@inheritdoc}
 */
```

phpdoc blocks is just adding noise for no value.

**Comment by sanmai** [comment]
Please reconsider. Some static analysers use this tag to infer the proper typing. IIRC this was PHPStan or Psalm. Without `{@inheritdoc}` you will get a very annoying head-scratching issues from them, or even make them useless (e.g. IIRC Psalm in the `totallyTyped` mode will fail the analysis unless it can see a type for everything).

**Comment by localheinz** [comment]
Related to https://github.com/phpstan/phpstan/issues/671.

**Comment by theofidry** [comment]
I guess if it is we should keep it

**Comment by localheinz** [comment]
Personally, I would vote for removing - I agree that they only add noise, as they should be automatically inherited. If there actually is an issue with static analysis, perhaps that’s a flaw in the analyzer?

**Comment by sanmai** [comment]
True, that's the flaw. But on the other hand if working around that flaw enables us to find an overlooked bug or other problem, isn't that is why we're using a static analyzer in the first place? And what's the point in using a static analyzer if we intentionally tie their shoelaces so they can't see a thing?

**Comment by sanmai** [comment]
So phpstan/phpstan#671 says this issue is solved in PHPStan. And I can't reproduce it with Psalm. So I guess I have to take my word back. There's no more a reason keeping us from removing these.
