### ISSUE TITLE
Fix build for PHP 7.4 before November, 28

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#774]
Fix Travis build for PHP 7.4 before the stable release

/remind @infection/core on November, 1

**Comment by maks-rafalko** [comment]
Well, currently [Infection fails](https://travis-ci.org/infection/infection/jobs/604424085#L348) on `7.4snapshot` with:

```
PHPUnit\Framework\Exception: Notice: stream_get_contents(): read of 8192 bytes failed with errno=9 Bad file descriptor in Standard input code on line 66
```

@sanmai I remember this is something you have investigated in https://github.com/sebastianbergmann/phpunit/issues/3772 and related tickets. Do you think it is related to mentioned issue?

To be honest, I didn't try anything yet (like running PHP on Docker with 7.4 RC etc.), perhaps your input would be a good start ;)

**Comment by sanmai** [comment]
That issue was about PHPDBG misbehaving with `strict_types` enabled. And there's [a still-unaddressed but report](https://bugs.php.net/bug.php?id=78424).

I also remember reading that PHP 7.4 became more strict about file descriptors. Otherwise put, if this is a plain old bug, it might be that we had this bug before but it did not manifest itself in any way.

**Comment by sanmai** [comment]
I can't even start testing on 7.4:
```
$ make test-unit-74
./devTools/flock devTools/*php74*.json docker run --tty --rm --volume "$PWD":/opt/infection --workdir /opt/infection infection_php74 vendor/bin/phpunit --group default
PHPUnit 8.4.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.0RC5 with Xdebug 2.8.0
Configuration: /opt/infection/phpunit.xml.dist
Random seed:   1572915764

Testing Infection Test Suite

Fatal error: Uncaught ReflectionException: Property PHPUnit\Util\Test::$annotationCache does not exist in /opt/infection/vendor/symfony/phpunit-bridge/Legacy/CoverageListenerTrait.php on line 73
```

**Comment by sanmai** [comment]
And... This is a know issue: https://github.com/symfony/symfony/issues/34231

**Comment by sanmai** [comment]
After #818 I can say that Infection passes 100% of the tests under PHP 7.4 locally, so the issue we're having with Travis builds might be related to either their build of PHP, or just that it is outdated.

**Comment by sanmai** [comment]
[The changelog says](https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.stream-wrappers) that `stream_set_option() ` must always return false, [where our implementation does not](https://github.com/infection/infection/blob/8b5fe199e222eff7a0fd5960815c91f825b0489f/src/StreamWrapper/IncludeInterceptor.php#L286).

**Comment by bkdotcom** [comment]
@sanmai 
php's documentation says
>(always returning FALSE is a sufficient implementation).

It does NOT say it must return false

That being said, the documentation for [stream_set_option](https://www.php.net/manual/en/streamwrapper.stream-set-option.php) is inadequate and makes no mention of `STREAM_OPTION_READ_BUFFER` / what does `STREAM_BUFFER_NONE` and ` STREAM_BUFFER_FULL` mean??   

probably safest to simply return `false` for `STREAM_OPTION_READ_BUFFER` & `STREAM_OPTION_WRITE_BUFFER`

**Comment by sanmai** [comment]
@bkdotcom if you take a look at our implementation (linked above), you'll notice it does about what you propose it should be doing

**Comment by sanmai** [comment]
@bkdotcom thank you for the valuable input, and please forgive me for misunderstanding.
