### ISSUE TITLE
Uncovered Mutations not logged?

### ISSUE THREAD

**Issue by GaryJones** [infection/infection#78]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.6.0 (via Composer)
| Test Framework version | PHPUnit 6.4.4
| PHP version | 7.1.7
| Platform    | MacOS
| Github Repo | https://github.com/GaryJones/plugin-boilerplate

Completely new to Infection, so likely a user error, but when running `infection -s` against by repo, I'm not able to see what the "mutants not covered by tests" were. My `logs/infection-text.txt` is empty.

![screenshot 2017-11-18 16 12 49](https://user-images.githubusercontent.com/88371/32982411-57511718-cc7c-11e7-87d2-0f45c4816e6a.png)

<details>
 <summary>phpunit.xml</summary>
 
 ```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/6.4/phpunit.xsd"
         bootstrap="tests/bootstrap.php"
         backupGlobals="false"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTestsThatDoNotTestAnything="true"
         beStrictAboutTodoAnnotatedTests="true"
         colors="true"
		 defaultTestSuite="unit"
         verbose="true">
	<testsuites>
		<testsuite name="unit">
			<directory suffix="Test.php">tests/Unit</directory>
		</testsuite>
		<testsuite name="integration">
			<directory suffix="Test.php">tests/Integration</directory>
		</testsuite>
	</testsuites>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>

    <logging>
        <log type="coverage-text" target="php://stdout" showUncoveredFiles="false"/>
        <!--<log type="coverage-html" target="coverage"/>-->
    </logging>
</phpunit>

 ```
</details>

<details>
 <summary>infection.json.dist</summary>
 
 ```json
{
    "timeout": 10,
    "source": {
        "directories": [
            "src"
        ]
    },
    "logs": {
        "text": "infection-log.txt"
    }
}

 ```

</details>

**Comment by sidz** [comment]
So I've tried (on the latest 0.6.1 version) to replicate your issue in your repo but **Not covered mutants** section is appearing in the _infection-text.txt_

Also if you want to see **Not covered mutants** in the console as well as others you just need to add `-v` option.
it caused by https://github.com/infection/infection/blob/master/src/Process/Listener/MutationTestingConsoleLoggerSubscriber.php#L102

**Comment by GaryJones** [comment]
Even on 0.6.1, my `infection-text.txt` is still empty (I've set it to `chmod 777`).

Maybe the file only gets written if there are escaped mutants?

The `-v` flag does make a couple of uncovered tests appear in the command line output, so I can play more with that.

**Comment by borNfreee** [comment]
You say the `logs/infection-text.txt` is empty, but `infection.json.dist` contains `infection-log.txt` file.

Are you looking at the wrong log file?

**Comment by GaryJones** [comment]
Sorry - typo in my last comment - the file I have is `infection-log.txt`.
