### ISSUE TITLE
We can't add PHPStan plugins, because we use the phar, and the plugins require to use a composer dependency

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#788]
We can't add PHPStan plugins, because we use the phar, and the plugins require to use a composer dependency. (Due to scoping of the phar etc)

_Originally posted by @BackEndTea in https://github.com/infection/infection/pull/745#issuecomment-511195465_

What about using composer package instead? This will allow us use so many useful plugins, including 

* https://github.com/thecodingmachine/phpstan-safe-rule (see [why](https://github.com/infection/infection/pull/745#pullrequestreview-261577586))
* https://github.com/thecodingmachine/phpstan-strict-rules
* https://github.com/phpstan/phpstan-phpunit
* and any other

**Comment by BackEndTea** [comment]
👍 For adding it as a dev dependency. The downside is that we can't test against 3.4 versions of some symfony components, due to the dependencies of phpstan.
We could solve this through vendor-bin, or however that is called, but i think @theofidry knows more about that.

**Comment by maks-rafalko** [comment]
Thanks to new baseline feature https://medium.com/@ondrejmirtes/phpstans-baseline-feature-lets-you-hold-new-code-to-a-higher-standard-e77d815a5dff we can use level `max` and all the strict rules without spending hours fixing existing issues

current `src` level: max
current `tests` level: 4
