### ISSUE TITLE
Fatal error by UnwrapArrayMerge and unpack

### ISSUE THREAD

**Issue by 1ed** [infection/infection#801]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.14.0
| Test Framework version | PHPUnit  7.4.5
| PHP version | 7.3.9
| Platform    | Ubunut
| Github Repo | -

Php fatal error caused by UnwrapArrayMerge and this diff:  

[M] UnwrapArrayMerge
```diff
--- Original
+++ New
@@ @@
-        return \count($classes) ? array_merge(...$classes) : $classes;
+        return \count($classes) ? ...$classes : $classes;
     }
```

**Comment by maks-rafalko** [comment]
Seems like we have [Parse error here](https://3v4l.org/Hppgc)

```
Parse error: syntax error, unexpected '...' (T_ELLIPSIS) in...
```

I think not only `array_merge` is affected, but all that can accept different arrays made by spread operator.

Feel free to submit a PR 👍

**Comment by maks-rafalko** [comment]
Released in https://github.com/infection/infection/releases/tag/0.14.2

Thank you!
