### ISSUE TITLE
Are there any services that let you upload mutation test results and display a badge on your repo?

### ISSUE THREAD

**Issue by Bilge** [infection/infection#805]
Like there is for code coverage.

**Comment by sanmai** [comment]
[How to set up a badge.](https://infection.github.io/guide/mutation-badge.html)

Feel free to close the issue.

**Comment by maks-rafalko** [comment]
You can try Stryker's dashboard, see https://github.com/infection/infection/issues/340#issuecomment-477148001

We didn't do any integration yet

**Comment by BackEndTea** [comment]
A HTML logger is something i'd like to work on, but from my quick experiments i did find a few incompatabilities with Strykers expected data and what we 'know'. I'm a bit too busy atm to create large PRs, but its something i'd like to work on a few months down the line.

**Comment by maks-rafalko** [comment]
I guess the question has been answered.
