### ISSUE TITLE
CTRL+C does not terminate process in progress

### ISSUE THREAD

**Issue by Bilge** [infection/infection#806]
CTRL+C interrupt is ignored by the program from start to finish and cannot be used to abort execution. Would be nice to have this ability.

**Comment by sanmai** [comment]
So far I cannot reproduce the issue with ignored CTRL+C. Infection stop just as I type that combination. Is there a repository where this behaviour can be seen?

**Comment by Bilge** [comment]
Under mintty on Windows 10.

**Comment by sanmai** [comment]
It is highly doubtful that Infection has anything to do with this behaviour. For one, because `pcntl_signal`, which is typically used to ignore signals, is never used.

**Comment by BackEndTea** [comment]
Its been a while since i did anything windows command line, but isn't ctrl+c just a copy there?

**Comment by BackEndTea** [comment]
Guess that just shows my ignorance of windows command line then. In that case i must admit i have no clue why ctrl c wouldn't abort like it is supposed to do.

**Comment by theofidry** [comment]
@Bilge the question is more what could prevent Windows to stop the command... We are not doing anything fancy there. Intercepting signals requires `pcntl` which we never use (and it won't work on Windows anyway).

Is this the case at any point of execution of Infection or is it in a specific phase?

**Comment by theofidry** [comment]
Can you try with `-vvv` and post the log? I'm curious to know if that could be because the infection process would restart itself to disable xdebug

**Comment by maks-rafalko** [comment]
ping @Bilge

**Comment by Bilge** [comment]
I'm not sure what you mean. `-vvv` does not change the output in any way.

**Comment by maks-rafalko** [comment]
closing as no one complains about it and we couldn't reproduce it
