### ISSUE TITLE
Infection should emit its version when run

### ISSUE THREAD

**Issue by Bilge** [infection/infection#808]
As per PHPUnit, it is very useful to see the version number in the output. Instead, we get a giant ASCII banner containing no useful information whatsoever. Nevertheless, this ticket is not a crusade against ASCII art, but if we are going to consume five lines where one would do, at least put something useful on one of them.

**Comment by sanmai** [comment]
We have it [right there under the banner](https://travis-ci.org/ScriptFUSION/Async-Throttle/jobs/599366095#L278).

**Comment by BackEndTea** [comment]
Thank you for this feature request. I think it is a good idea to emit this information to our users.

You can open a PR to add this functionality. The best place to add it would probably be somewhere around here: https://github.com/infection/infection/blob/2c915a4aa2c2b96a9ca2282254aebe8f7af29489/src/Console/Application.php#L122
