### ISSUE TITLE
Notify user if msi is over specified min-msi

### ISSUE THREAD

**Issue by LeoVie** [infection/infection#810]
**Is your feature request related to a problem? Please describe.**
I'm using infection as a composer script inside a ci pipeline.
I'm kind of hard coding the minimum msi via the `--min-msi` option.
Everytime I run infection, I have to check if the actual msi has raised over the min-msi. If so, I can raise the min-msi, too.

**Describe the solution you'd like**
It would be nice, if infection would check the min-msi and compare it with the actual msi.
If the msi is like 2% over the min-msi, it should print out a notice like "Your msi has raised. You should run infection with a higher min-msi next time." or something.

**Comment by maks-rafalko** [comment]
Nice suggestion, thank you! Seems like easy to implement, feel free to contribute ;)

**Comment by LeoVie** [comment]
Cool, I'll take care of it. :)

**Comment by LeoVie** [comment]
Maybe we could even add an opt-in configuration option which lets infection fail, if the actual msi is much greater than the min-msi. This would force users to keep their min-msi updated.
What do you think about that?

**Comment by maks-rafalko** [comment]
Do you mean a new option (`--something`) that is disabled by default? And what is "much greater"?

Looks like your build will always fail, either by actual MSI below the `--min-msi` or above ;)

**Comment by BackEndTea** [comment]
> Maybe we could even add an opt-in configuration option which lets infection fail, if the actual msi is much greater than the min-msi. This would force users to keep their min-msi updated.
What do you think about that?

The notification about being able to bump your min-msi is fine. I think this is a bit overkill.

**Comment by sanmai** [comment]
This and any other similar types of behavior can be emulated with a simple bash script provided Infection writes the actual MSI metrics to a file, which then can be cached at the CI side, and then parsed to use the latest metrics when running Infection.

No other extra command line option is needed here, but an additional logging format, which is much more straightforward to implement.

**Comment by LeoVie** [comment]
I'd not compare by equality, but the user would define a tolerance range of 2 percent points for example.
The build would fail then, if `msi > (min-msi + 2 percent points)`.
The configuration option could be something like `"fail-if-msi-x-percent-points-over-min-msi": 2` (or a smoother name :))

This would cause infection to fail, if it gets run with a min-msi of 70%, but the actual msi is over 72%.

Through this, no manual comparing of the min-msi and the actual msi is needed, anymore. The user could be sure, that the min-msi is always more or less up to date.

Do you get my point? Or is this use case to specific?

**Comment by sanmai** [comment]
Well, that 2% advancement can be quite hard to achieve for bigger projects. You can stick for the face value for the metric, but updating it only if it goes up. E.g. you will cache no the original `something.json` with metrics that Infection generates, but a copy of it after comparing the metrics here and there. So if you have say, 70% metric saved in a file, and new run gives 70.5% MSI, you would note that change, and next time require 70.5% MSI. I am any clear?

**Comment by LeoVie** [comment]
Hm, this would not make use of the `min-msi` option. Am I right?

**Comment by sanmai** [comment]
It'll be more like https://github.com/phan/phan/issues/2000, but less automatic. And I think we can do that baseline trick just like Phan does.
