### ISSUE TITLE
Multiple runs give different MSI scores

### ISSUE THREAD

**Issue by Bilge** [infection/infection#828]
| Question    | Answer
| ------------| ---------------
| Infection version | unknown
| Test Framework version | PHPUnit 7.5.17
| PHP version | 7.2.15
| Platform    | Ubuntu
| Github Repo | https://github.com/Porter-connectors/HttpConnector

Unfortunately I have no evidence of this because I rebuilt the same job several times, each time discarding the log of the previous build. Nevertheless I can accurately assert exactly the same code with exactly the same dependencies can yield different scores for the same code. The first build failed because it was below the specified 69% threshold, but running it again yielded a pass at 70%. Here's the [passing build](https://travis-ci.org/Porter-connectors/HttpConnector/jobs/611484507), but again, I don't have the failing ones any more because they were literally the same job.

**Comment by Enapiuz** [comment]
Hey @theofidry!

We've encountered the same issue.
Actually, we found that it happens because of flaky tests. I bet your MSI spikes always go up and never down.
I think everything cuz of this https://github.com/infection/infection/blob/master/src/Metrics/Calculator.php#L97 and `$this->errorCount`

**Comment by sanmai** [comment]
Care to show your `phpunit.xml`? You can remove private parts like names etc.

**Comment by theofidry** [comment]
I think the main issue here is to identify from where it comes from:

- The tests themselves that are flaky; To identify this you might want to check if the execution order is random or not
- Infection corrupts the state: this may happen if there is any integration test. At some point we will need to add support for a noop operator to detect those scenarios
- There is a legit bug in how we collect and calculate the metrics

**Comment by maks-rafalko** [comment]
Seems like the reason is failed tests (because of order, for example).

We have implemented `--noop` option to debug such cases, so please use it to debug the issue on your side and feel free to discuss here/reopen if you think Infection still has a bug.
