### ISSUE TITLE
TypeError not detected as failing test

### ISSUE THREAD

**Issue by Bilge** [infection/infection#836]
| Question    | Answer
| ------------| ---------------
| Infection version | x.y.z (`infection.phar --version`)
| Test Framework version | PHPUnit x.y.z
| PHP version | 7.2.x
| Platform    | Ubuntu/MacOS
| Github Repo | -

We have observed a false positive when a mutation causes a `TypeError`. The most obvious case is when removing a cast in a file that declares `strict_types=1`. More subtly, it can also occur when a call to a parent constructor is removed as part of the method removal mutation, because a subsequent call to a getter method will now return `null` instead of the type that should have been passed in to the parent's constructor. In all cases where `TypeError` is thrown, no matter how it comes about (does not depend on a particular mutation), Infection claims the mutant was not caught. However, making exactly the same change manually (according to the diff) and rerunning tests causes our test suite to fail, so this seems to be clearly a false positive.

Unfortunately I cannot provide clear steps to reproduce this issue. We tried creating a contrived test case but failed. In practice, the test is a Symfony functional test that makes a subrequest by booting the kernel and emulating an HTTP request (but it doesn't actually despatch a real request via a web server). Ultimately this shouldn't matter, but again, I cannot reproduce it with a simple contrived case and I cannot share the code because it's owned by a company. So this is just a note in case anyone has experienced something similar and might be able to intuit where the problem lies.

**Comment by sanmai** [comment]
If a code style assumes always adding a constructor, even if an empty one, and calling it from siblings, then it really looks like a false positive. Yet I don't see what we can do here other than by offering to disable the mutator in principle, or on the very line.

**Comment by Bilge** [comment]
Closed via #846.
