### ISSUE TITLE
Support for Simpletest Test Framework

### ISSUE THREAD

**Issue by ramiror** [infection/infection#838]
Add support for Simpletest: ~http://simpletest.sourceforge.net/~ https://github.com/simpletest/simpletest

Thanks!

**Comment by sidz** [comment]
but project is dead. Or did I miss smth?

> [2010/10/29] SimpleTest 1.1alpha is released

**Comment by ramiror** [comment]
> Thanks for creating this feature request.
> 
> But as I can see this project is dead and the last release was more than 9 years ago.
> 
> > [2010/10/29] SimpleTest 1.1alpha is released

Sorry for the old link. The project is still active. See https://github.com/simpletest/simpletest

**Comment by ramiror** [comment]
Sorry for the old link. The project is still active. See
https://github.com/simpletest/simpletest

**Comment by maks-rafalko** [comment]
There is no demand on this feature, and it won't be a part of infection/infection anyway. If someone is interested - please comment here and I can probably help with creating a plugin, like we did for Codeception for example https://github.com/infection/codeception-adapter
