### ISSUE TITLE
Remove or add @inheritdoc blocks

### ISSUE THREAD

**Issue by theofidry** [infection/infection#860]
The codebase is a bit inconsistent regarding this so should we:

- add `{@inheritDoc}` where missing?
- remove `{@inehritDoc}`

In both cases there is an additional action to take. For the first one, we need to ensure it is `@inehritdoc` and not `@inheritDoc` as the former is not well understood by neither phpStorm & PHPDocumentor.

For the second one we should make sure they cannot be added (by an automatic CS fix or something)

**Comment by Bilge** [comment]
>Important

>Currently some applications have DocBlocks containing just the {@inheritDoc} inline tag to indicate that their complete contents should be inherited. This usage breaks with the PHPDoc Standard as summaries cannot contain inline tags and inheritance is automatic; you do not need to define a special tag for it.

https://docs.phpdoc.org/guides/inheritance.html

**Comment by sanmai** [comment]
Before `@inehritdoc` were important for some static analyzers (PHPStan?), but now they can be safely ignored, unless absolutely required on the case by case basis. Therefore I think the second option is the best one.

**Comment by maks-rafalko** [comment]
+1 for removing this particular phpdoc comment
