### ISSUE TITLE
Isolate Infection dependencies

### ISSUE THREAD

**Issue by theofidry** [infection/infection#87]
I'm not sure I should expand too much on why having too many dev dependency is an issue, if that's the case please tell me I'll update that part accordingly. To tack this issue I would like to do the two following suggestions:

A. Use [PhpScoper](https://github.com/humbug/php-scoper) for the PHAR.
B. Split this package in two

A) The code bundled in a PHAR is not isolated (more [here](https://github.com/humbug/php-scoper#goal)) which may be an issue. PhpScoper solves that.

B) There is two cases here.

The first one is I think installing Infection as a composer dependency (I mean at a project level not globally) is a perfectly valid case. Like PhpUnit, it _executes_ code. As a result you need to make sure you PhpUnit/Infection dependencies are compatible with your application dependencies, which is what Composer is about. Having a completely isolated PHAR is IMO the only viable alternative.

Providing an extension point. Let me extend on that. Even if we manage to isolate the PHAR, a feature I would love to see is providing an extension point to let people define their own mutants. To do so, we have two choice: require the user to use Infection as a dev dependency which IMO may easily be an issue due to the number of dependencies Infection has, especially ones like PhpParser that are often source of conflicts that takes ages to fix. The second choice, much cleaner IMO, is to adopt the same strategy as Composer with its plugins: expose an API which would be super lightweight, it just provides the necessary code to allow one to define its own mutant. Then the PHAR when executing can locate those custom mutants.

Related article: [managing your PHP dependencies](https://medium.com/@tfidry/managing-your-dependencies-in-php-321d584441ab)

**Comment by BackEndTea** [comment]
@theofidry Is this still an issue, now that we use PhpScoper?

**Comment by theofidry** [comment]
Nope it has been fixed with it :)
