### ISSUE TITLE
php 7.4 PHP Deprecated:  Unparenthesized

### ISSUE THREAD

**Issue by smpl** [infection/infection#880]
run infection on php 7.4 have message https://travis-ci.com/cekta/di/jobs/264351150#L372
/home/travis/build/cekta/di/vendor/infection/infection/src/TestFramework/PhpUnit/Config/XmlConfigurationHelper.php on line 161

**Comment by BackEndTea** [comment]
It looks like you are running an older version of infection (`0.13.*`).

If you upgrade to a newer version of infection this should be resolved.

**Comment by smpl** [comment]
that help
thx
