### ISSUE TITLE
Add support for PHPUnit <extensions> element

### ISSUE THREAD

**Issue by Khartir** [infection/infection#883]
PHPUnit has an `<extensions>` element in the `<phpunit>` element since version 7.5. However, infection produces an XSD-validation-error when using this element:
` phpunit.xml file does not pass XSD schema validation. [Error] Element 'extensions': This element is not expected.`

**Describe the solution you'd like**
Add support for PHPUnit's `<extensions>` element.(https://phpunit.readthedocs.io/en/8.4/configuration.html#the-extensions-element)

**Describe alternatives you've considered**
Some extension also work using `listeners`. This can be used as a workaround.

**Comment by BackEndTea** [comment]
You may be referencing an old xsd, which is used for the validation.
Could you show your current `phpunit.xml`?

**Comment by Khartir** [comment]
You are right, the schema specified in the `phpunit.xml` was refernecing an old phpunit version.
I completely missed that, I'm sorry. Thanks for the quick help.
