### ISSUE TITLE
Define a level of strictness

### ISSUE THREAD

**Issue by theofidry** [infection/infection#89]
One of the greatest point of mutation testing is that it provides a reliable way to know which part of your application is absolutely tested. A bad point is that it's horribly slow as it's a brute force technique. An easy way to get better performances is to simply play with the number of mutators applied. Indeed applying only 10 mutators is gonna result in a much faster execution time than 100 mutators.

IMO there is a lot of mutators that may not be useful depending of the context in which Infection is used. For example I could care less about the visibility mutator in my application and find it much more useful in my library.

Point is, I think it would be a good idea to provide a way for the user to define which mutators can be applied in the application and maybe providing different default sets. For example we could call that parameter `level` and depending of the value, we apply more or less mutators like for example PhpStan does with their analysis rules.

**Comment by BackEndTea** [comment]
I was thinking about this a little bit, and i think a better way may be to provide `profiles`.

So you would have a `library` profile, which includes the `Visibility` mutants, and an `application` profile which does not.

This could also allow us to have Mutants that are turned off by default, and have some kind of 'I got a 30 minute lunch break' profile which would include all mutants, even the ones that are most likely duplicates, (Like those mentioned in #114)

An even better version of this is to have some way for others to define custom profiles, which they could re-use across projects, or even distribute themselves. Which is similar to how [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) does things.

**Comment by theofidry** [comment]
Maybe `profile` would be a better terminology than `level` here 👍  A thing I like about it (`profile`) is that unlike `level`, we don't have to make a choice about what is stricter than another, so I think it will be easier to define

**Comment by BackEndTea** [comment]
I have been playing around with profiles a bit, what is your opinion on a config like this:

```json
{
  "timeout": 25,
  "source": {
    "directories": [
      "src"
    ],
  },
  "mutators": {
    "@library": true,
    "Plus": false,
    "PublicVisibility": true,
    "TrueValue": false
  }
}
```

This would entail you use the `library` profile, but exclude the `Plus` & `TrueValue` mutators, but include the `PublicVisibility`.

Doing this would also allow us to add configs to mutators at a later stadium

**Comment by theofidry** [comment]
that looks good to me 👍 The only thing is you would need to make sure that if there's a mutator in `@library` which is disabled later, it is actually disabled. For example if `@library` includes `TrueValue`, then with your example above `TrueValue` would be disabled

**Comment by borNfreee** [comment]
Like it, similar to PHPCSFixer which I find very flexible. Also like the notation with `@` for predefined profiles.

Does it conflict with your WIP PR to ignore mutators, e.g. with this config https://github.com/infection/infection/pull/177/commits/19f8d26020e6ec9b84bdb9b6238b048bac9d1faf#diff-9b8b48d7ba9473e9028af061fe11333a ?

**Comment by BackEndTea** [comment]
@theofidry Yeah that was exactly my intention

@borNfreee I'm still thinking on how to add the ignore statements into this in a nice and flexible way, so any suggestions are welcome.

**Comment by borNfreee** [comment]
I beleive we should combine this RFC with https://github.com/infection/infection/issues/79 (Disable certain mutators for certain lines). Would e.g. such config work for both of them?

```js
{
    "timeout": 25,
    "mutators": {
        "@library": true,
        "Minus": true, // included
        "Plus": false, // completely ignored
        "TrueValue": { // ignored for particular cases
            "ignore": [
                "Ignore\\For\\Particular\\Class",
                "Ignore\\For\\Another\\Class::method",
                "Ignore\\For\\**\\*\\Glob\\Pattern\\Or\\Namespace"
            ],
        }
    }
}
```

**Comment by BackEndTea** [comment]
> I beleive we should combine this RFC with #79 (Disable certain mutators for certain lines). Would e.g. such config work for both of them?

Looks good to me. I can work on it together with #79 in #177. But i think that #67 will make the ignore functionality a lot easier, since we can get info on the class that is being processed much easier.

**Comment by borNfreee** [comment]
Yeah, I have to move forward with #67 then
