### ISSUE TITLE
Scoped configuration

### ISSUE THREAD

**Issue by theofidry** [infection/infection#90]
Taking advantage of #88 and #89, there is one more point that I think would be awesome in terms of usability. The idea is that you don't have the same level of exigence for every part of your application. As such, I think it would be really good to be able to define scoped configuration, i.e. define options that would be applied to only a part of the code.

For example, assuming #89 is implemented, I could define a high level of strictness for a specific part of my application which is very important and a lower level of strictness for the rest.

**Comment by BackEndTea** [comment]
If #89 and #79 are implemented, would that resolve this?

**Comment by theofidry** [comment]
Well not exactly :) To be exact what has been implemented allow this but at a global level. What I'm actually thinking of is what we currently have but for smaller subsets. For example you could define that the directory `src/Domain` should be strictly tested so a lot of mutators enabled for it and for another part like `src/Infrastructure` reduce the strictness so apply a lot less mutators.

Right now this would be doable by applying different configuration files and merge the result sort of. But in any case, I think what we have is good enough for now. I'll re-open the issue with more details when I'll have time to dig deeper into this

**Comment by BackEndTea** [comment]
What if, in addition to 'ignoring' mutators on certain namespaces/methods etc, we have a 'whitelist' option ( or another name), that says: only apply this mutator/profile on these namespescapes/methods?

**Comment by theofidry** [comment]
I'm not sure yet tbh. I really prefer to dig into this with a real-life scenario first before going further in what we actually need to make it work :)
