### ISSUE TITLE
Partial parallelism

### ISSUE THREAD

**Issue by theofidry** [infection/infection#91]
Not quite sure how we can make that work, but basically the `thread` option is useless as soon as you have integration tests which rely on a DB or something. As of now a way to deal with it is simply exclude those tests from the execution which is a bit extreme. If you really want to execute Infection on them still, you basically have no choice but to execute Infection two times, one time threaded with the excluded functional tests and another time not threaded with the functional tests only.

A better way IMO would be to find a way to allow a user to say that some tests are more sensitive than other and require to be run in a single thread. To illustrate, if you have the following tests:

- FunctionalTest1
- FunctionalTest2
- UnitTest1
- UnitTest2
- UnitTest3

with three threads, we have a pool of mutants to apply, we make sure all the ones related to a functional test are executed in the same thread while we can parallelise the other. And if by chance we finish with the mutants related to the functional tests first, then the thread used is now free for the other mutants.

**Comment by maks-rafalko** [comment]
We have impemented the approach with `TEST_TOKEN`, see How to run Infection for functional testshttps://infection.github.io/guide/how-to.html#How-to-run-Infection-for-functional-tests

**Comment by maks-rafalko** [comment]
[

**Comment by theofidry** [comment]
>IMO, nothing to implement and complicate here on our (Infection) side

At the time of the issue we did not have anything of the sort and I think the current solution is satisfying.

I would however recommend a more infection specific environment variable than `TEST_TOKEN` though... `INFECTION_THREAD_ID` for example

**Comment by maks-rafalko** [comment]
I would like to have it, but Paratest (which is quite populare, and I already use it) already implemented [`TEST_TOKEN`](https://github.com/paratestphp/paratest#test-token) before.

And the good thing that you can use `TEST_TOKEN` and use both - Paratest and Infection parallelizing tests, no need to use 2 env vars in your app's code to determine what DB to use => good DX.

**Comment by theofidry** [comment]
That's quite unfortunate, but practicality wins over purity IMO
