### ISSUE TITLE
Use existing coverage report

### ISSUE THREAD

**Issue by theofidry** [infection/infection#94]
Unless I missed it, right now are running the tests which requires xdebug or phpdbg to get the coverage data to then be able to do our own stuff.

I think a typical user would already have tests with coverage somehow, so IMO it would make much more sense to provide the data coverage files which when done so would avoid us to have to run the tests once.

**Comment by borNfreee** [comment]
Do you suggest to have an option for providing code coverage data for Infection?

I'm not sure skipping the "Initial test suite run" step is a good idea. 

1. We must run the whole test suite to make sure all tests are in a passing state. Without it, we can't guarantee the correctness of MSI.
2. When user changes the code and/or test, we must to re-generate code coverage.

I'm not sure I got your right though.

**Comment by theofidry** [comment]
I think we're just describing different workflows.

Your workflow fits very well in the case where you run your tests without coverage for quick feedback and then run Infection to get a detailed report.

Another workflow would be to run the tests with coverage and then Infection for the report.

In the second case, running the tests again with coverage is a waste of time. And a use case for that second case is for example if you have to do a weird workaround for running the tests with coverage, if you want to display multiple coverage reports (XML + Text for example) or send the coverage report to another tool.

That said I don't think feature is a high priority one.

**Comment by luispabon** [comment]
Currently, we're running our tests with coverage twice at CI, one with phpunit to get the reports, and another one with infection. 

Each step takes a few minutes as my current project has a number of end to end (eg drilling through the whole symfony stack) tests that are very slow when xdebug and coverage are enabled. Non coverage phpunit runs finish within the second.

If infection could take a coverage report file from a previous phpunit run it would cut our build times down substantially. Infection's initial test run would still run, but without coverage.

Infection could then print a warning that using an external coverage file could give misleading results if stale. It would be the developer's responsibility to ensure that doesn't happen.

**Comment by luispabon** [comment]
An alternative way that would help in my use case would be for infection to honor coverage report generation settings on phpunit.xml including location. This would perhaps be cleaner and safer.

**Comment by ryan7273** [comment]
This would cut down on my build times as well. I like the suggestion of using the `phpunit.xml` settings as it would allow Infection to be more easily integrated into a full CI setup without adding redundancy.

**Comment by borNfreee** [comment]
I see your point guys.

1. Infection now have a feature to set `tmpDir` folder. You can set it to `"tmpDir": "reports"` in `infection.json` file and coverage xml will be generated in `reports/infection/coverage-xml` folder. So, using this setup, you can first run Infection, then get generated coverage and use it whenever you need. However, it works only if Infection runs the same test suite as you run while generating code coverage.

2. Please note that Infection requires not only `coverage-xml` report to work fast and properly, it also requires `junit`. So if your code-coverage setup does not have `junit`, infection can't rely on it

> An alternative way that would help in my use case would be for infection to honor coverage report generation settings on phpunit.xml

As for me, It would be confusing if  I use e.g. `tmpDir=cache`, but coverage-xml is generated to another folder from `phpunit.xml`. But maybe I'm wrong.

Would option 1 work for you?

**Comment by luispabon** [comment]
It wouldn't unfortunately as infection is very specific in requiring the reports it needs to function while stripping my own reports from phpunit.xml. Infection has its needs and other projects have others.

Infection also leaves behind a lot of temporary files that would clutter up my reports.

**Comment by borNfreee** [comment]
> Infection has its needs and other projects have others.

exactly.

So, 

1. if you want infection to use existing reports and skip coverage during Initial Test Run - reports should be `junit` and `xml`.
2. if you want infection to generate coverage to the folder from `phpunit.xml` - infection will be able to generate only `junit` and `xml`, but not html and others

If none of these options suit your needs - it's not clear how to proceed.

**Comment by luispabon** [comment]
Option 1 would totally work I reckon, if we can point infection to the location of them reports

**Comment by borNfreee** [comment]
Then let's do it for 0.8.0 :) I will pick it up.

**Comment by luispabon** [comment]
👍👍👍

**Comment by BackEndTea** [comment]
Another side effect of this is that we don't **need** the user to have Xdebug enabled or run phpdbg, if they have a pre-existing coverage report

**Comment by borNfreee** [comment]
@ryan7273 @luispabon implemented. Feel free to check it in master, not sure when it will be released though.

Example how to use it: 

https://github.com/infection/infection/blob/1966cbb703cc21cc2d39d4bfc3d0231ae3712ca3/.travis.yml#L27-L28

Documentation: https://github.com/infection/site/blob/master/src/guide/command-line-options.md#--coverage

**Comment by luispabon** [comment]
Understood, I'll give this  a spin as soon as I get back to work in the
morning 👍--
Kind regards,
Luis Pabon

**Comment by ryan7273** [comment]
This part works perfectly for me when I use phpdbg. I do run into the #182 issue when I don't run Infection through phpdbg, but it looks as though the fix for that has not been merged yet.

Thanks for all the work on this :+1:
