### ISSUE TITLE
disable colors options

### ISSUE THREAD

**Issue by zdenekgebauer** [infection/infection#99]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.7.0
| Test Framework version | PHPUnit 6.5.5
| PHP version | 7.0.26
| Platform    | Windows 10
| Github Repo | 

The output always contains colors. cmd.exe on Windows 10 does not support them (example bellow) . Can I disable colors?
````bash
←[1m4←[22m mutations were generated:
←[1m       0←[22m mutants were killed
←[1m       4←[22m mutants were not covered by tests
←[1m       0←[22m covered mutants were not detected
←[1m       0←[22m errors were encountered
←[1m       0←[22m time outs were encountered
````

**Comment by theofidry** [comment]
`--no-ansi` is what you are looking for I believe

**Comment by zdenekgebauer** [comment]
Sorry, it doesn't work for me.  Moreover, I did not found parameter "--no-ansi" in https://infection.github.io/guide/command-line-options.html

**Comment by theofidry** [comment]
It should be a parameter available in any Symfony command, but maybe we are breaking something and it doesn't work as expected

**Comment by sidz** [comment]
`--no-ansi` is working fine on my Windows 10 machine. But yeah, we have an issue in xdebugHandler. I'll take a look
